### ISSUE TITLE
Binance: Not able to get fees

### ISSUE THREAD

**Issue by schroedermarius** [whittlem/pycryptobot#100]
I am trying to test your bot for binance. It seems like it is not getting the fees correctly. Maybe their API changed on that point:

![image](https://user-images.githubusercontent.com/7676542/116848266-7cd69000-abec-11eb-8a9c-c9ad5f6447d4.png)

**Comment by denissonpaz** [comment]
Having the same error here. 
It's related to https://github.com/whittlem/pycryptobot/pull/99

**Comment by veskoz** [comment]
Me too:
`Traceback (most recent call last):
  File "/home/pi/ADA-EUR/pycryptobot.py", line 931, in <module>
    executeJob(s, app, trading_data)
  File "/home/pi/ADA-EUR/pycryptobot.py", line 902, in executeJob
    executeJob(sc, app, trading_data)
  File "/home/pi/ADA-EUR/pycryptobot.py", line 687, in executeJob
    fee = float(price) * app.getTakerFee()
  File "/home/pi/ADA-EUR/models/PyCryptoBot.py", line 1482, in getTakerFee
    return api.getTakerFee()
  File "/home/pi/ADA-EUR/models/Binance.py", line 104, in getTakerFee
    return float(fees['taker_fee_rate'].to_string(index=False).strip())
ValueError: could not convert string to float: 'Series([], )'
`

**Comment by whittlem** [comment]
I've reverted that change for Binance until I find some time to have a look at it in more detail. Do a "git pull" and let me know if your issue is resolved for the time being?

**Comment by denissonpaz** [comment]
@whittlem , the reverted code worked. thanks!

**Comment by sickness0666** [comment]
reverted code works for me also

**Comment by whittlem** [comment]
Thanks for letting me know. This is a weird one because the Binance API has individual fees for every market which are 0.001 but I think that is way lower than the actual fees. I manually set it back to 0.005 and it seems to be working for you. The fee structure for Binance is a little strange.
