### ISSUE TITLE
Binance marketSell list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by denissonpaz** [whittlem/pycryptobot#102]
Hi all, I just observed this message and the trade didn't happen:

BNB balance before order: 0.2927
BUSD balance before order: 0.0
04-05-2021 00:33:51 Binance marketSell list indices must be integers or slices, not str
BNB balance after order: 0.2927
BUSD balance after order: 0.0

Running as:

                             Python Crypto Bot                                

               Release : v2.0.0 (commit: 6)                                   

              Bot Mode : LIVE - live trades using your funds!                 
           Bot Started : 2021-05-03 23:53:14.090838                           

          Sell At Loss : 1  --sellatloss 1                                    
     Sell At Resistance : True  --sellatresistance                            
       Trade Bull Only : True  --disablebullonly                              
         Buy Near High : True  --disablebuynearhigh                           
          Use Buy MACD : True  --disablebuymacd                               
           Use Buy OBV : True  --disablebuyobv                                
     Use Buy Elder-Ray : True  --disablebuyelderray                           
    Sell Fibonacci Low : True  --disablefailsafefibonaccilow
    Sell Fibonacci High : True  --disableprofitbankfibonaccihigh
    Candlestick Reversal : True  --disableprofitbankreversal                    
              Telegram : True  --disabletelegram                              
                   Log : True  --disablelog                                   
               Tracker : True  --disabletracker                               
*** smart switch from granularity '1h' (1 hour) to '15m' (15 min) ***

**Comment by whittlem** [comment]
I've not seen that error message before. Did it give you any other debug output?

**Comment by denissonpaz** [comment]
It happened again a couple of hours ago.
Same message.. I've checked the log file, there's nothing else there.

**Comment by denissonpaz** [comment]
I found something here that could help:

https://stackoverflow.com/questions/66485691/typeerror-list-indices-must-be-integers-or-slices-not-st

**Comment by whittlem** [comment]
Are any devs using Binance able to help me resolve this? I use Coinbase Pro and not able to re-create this issue.

**Comment by github-ptaylor** [comment]
Ok.

@denissonpaz, please share the **exact market pairs** that experienced this problem. You stated it happened twice after the original time.. It would be cool to know if it's the same market pair.

@whittlem 

The reference to the error on Stackoverflow gave a hint on how to look a this.. some piece of logic in Binance.py tried to reference a result that should have had a list of arrays (with key/value pairs),  instead it found a list strings.

I believe it was a call to the (get_symbol_info) function in the binance.client module.

The error comes from (Try/Except) block in the (marketSell) function in Binance.py:

```
    def marketSell(self, market='', base_quantity=0):
        """Executes a market sell providing a crypto amount"""

        # validates the market is syntactically correct
        if not self._isMarketValid(market):
            raise ValueError('Binance market is invalid.')

        if not isinstance(base_quantity, int) and not isinstance(base_quantity, float):
            raise TypeError('The crypto amount is not numeric.')

        try:
            df_filters = self.getMarketInfoFilters(market)
            step_size = float(df_filters.loc[df_filters['filterType'] == 'LOT_SIZE']['stepSize'])
            precision = int(round(-math.log(step_size, 10), 0))

            # remove fees
            base_quantity = base_quantity * 0.9995

            # execute market sell
            stepper = 10.0 ** precision
            truncated = math.trunc(stepper * base_quantity) / stepper
            print ('Order quantity after rounding and fees:', truncated)
            return self.client.order_market_sell(symbol=market, quantity=truncated)
        except Exception as err:
            ts = datetime.now().strftime("%d-%m-%Y %H:%M:%S")
            print (ts, 'Binance', 'marketSell',  str(err))
            return []
```

Since the error message doesn't display the message "Order quantity after rounding and fees",  i'll guess the error is being through from the  function call in this expression  [**step_size = float(df_filters.loc[df_filters['filterType'] == 'LOT_SIZE']['stepSize'])**]  in the 2nd line of the (try) block:

The first statement in the try block makes a function call to:

```
    def getMarketInfoFilters(self, market):
        return pd.DataFrame(self.client.get_symbol_info(symbol=market)['filters'])
```

Anywhooo, something is happening when a specific set of data is returned for the (market pair) that was being used.. hence, the need to know what market pair was being processed at that time.

The data for the binance.client stat the structure should come back like:

```
{
    "symbol": "ETHBTC",
    "status": "TRADING",
    "baseAsset": "ETH",
    "baseAssetPrecision": 8,
    "quoteAsset": "BTC",
    "quotePrecision": 8,
    "orderTypes": ["LIMIT", "MARKET"],
    "icebergAllowed": false,
    "filters": [
        {
            "filterType": "PRICE_FILTER",
            "minPrice": "0.00000100",
            "maxPrice": "100000.00000000",
            "tickSize": "0.00000100"
        }, {
            "filterType": "LOT_SIZE",
            "minQty": "0.00100000",
            "maxQty": "100000.00000000",
            "stepSize": "0.00100000"
        }, {
            "filterType": "MIN_NOTIONAL",
            "minNotional": "0.00100000"
        }
    ]
}
```

**Comment by denissonpaz** [comment]
@github-ptaylor , it happened with two different markets pairs.

Find the configuration of them below:

BNB/BUSD
```
{
    "binance" : {
        "api_url" : "https://api.binance.com",
        "api_key" : "",
        "api_secret" : "",
        "config" : {
            "base_currency" : "BNB",
            "quote_currency" : "BUSD",
            "live" : 1,
            "verbose" : 0,
            "smartswitch" : 1
        }
    },
    "telegram" : {
        "token" : "",
        "client_id" : ""
    }
}
```

And DOGE/USDT

```
{
"binance" : {
        "api_url" : "https://api.binance.com",
        "api_key" : "",
        "api_secret" : "",
        "config" : {
            "base_currency" : "DOGE",
            "quote_currency" : "USDT",
            "live" : 1,
            "verbose" : 0,
            "smartswitch" : 1,
            "sellatloss" : 0
        }
    },
    "telegram" : {
        "token" : "",
        "client_id" : ""
    }
}
```

**Comment by github-ptaylor** [comment]
@denissonpaz thanks, and i just saw that you mentioned that in the first post, doh! ;)

can you share the exact configuration settings that you used as well (for granularity, selllower, sellupper, etc...)

i'll see if i can get the error to happen in test mode.

**Comment by denissonpaz** [comment]
@github-ptaylor just these ones in the config. the rest was all default values.

**Comment by fepetoo** [comment]
2021-05-05 02:00:00 | ETHEUR 15m | Close: 2789.21 | BUY

ETH balance before order: 0.0
EUR balance before order: 127.13
05-05-2021 04:02:27 Binance marketBuy list indices must be integers or slices, not str
ETH balance after order: 0.0
EUR balance after order: 127.13

ETHEUR

"binance" : {
        "api_url" : "https://api.binance.com/",
        "api_key" : "",
        "api_secret" : "",
        "config" : {
            "base_currency" : "ETH",
            "quote_currency" : "EUR",
            "granularity" : "15m",
            "live" : 1,
            "verbose" : 0,
            "disablebullonly" : 1,
            "disablebuyobv" : 1,
            "disablebuyelderray" : 1,
            "sellatloss" : 0,
            "disablebuynearhigh" : 1,
            "sellatresistance" : 1
        }
    }

**Comment by github-ptaylor** [comment]
hey everyone, good morning!

i haven't replicated the issue yet. 

i passed the market pair to the (get_symbol_info) function where i thought the problem originated from, but it was successful on multiple attempts:

admin@Dopes-MacBook-Pro python % python Binance_Client.py

```
[   {   'filterType': 'PRICE_FILTER',
        'maxPrice': '1000.00000000',
        'minPrice': '0.00001000',
        'tickSize': '0.00001000'},
    {   'avgPriceMins': 5,
        'filterType': 'PERCENT_PRICE',
        'multiplierDown': '0.2',
        'multiplierUp': '5'},
    {   'filterType': 'LOT_SIZE',
        'maxQty': '9000000.00000000',
        'minQty': '0.10000000',
        'stepSize': '0.10000000'},
    {   'applyToMarket': True,
        'avgPriceMins': 5,
        'filterType': 'MIN_NOTIONAL',
        'minNotional': '10.00000000'},
    {'filterType': 'ICEBERG_PARTS', 'limit': 10},
    {   'filterType': 'MARKET_LOT_SIZE',
        'maxQty': '9955538.26587908',
        'minQty': '0.00000000',
        'stepSize': '0.00000000'},
    {'filterType': 'MAX_NUM_ORDERS', 'maxNumOrders': 200},
    {'filterType': 'MAX_NUM_ALGO_ORDERS', 'maxNumAlgoOrders': 5}]
Order quantity after rounding and fees: 49.9
```

I'll keep troubleshooting.

Note: This issue is occurring for both (marketBuy) and (marketSell)

**Comment by fepetoo** [comment]
when you create some debug logs.. i can let my bots running with that.. then in case this happens i can put the logs here..

**Comment by ghamarian** [comment]
I got the same issue on Binance with ING/USDT.

**Comment by fepetoo** [comment]
current_price = self.getTicker(market) could, theoretically cause the issue.. i think... in case the market is empty. in that case, more than one price will come back.. can this fail with the error above?
        if 'price' in resp:
            return float('{:.8f}'.format(float(resp['price'])))<--?
            
 i don't think, getMarketInfoFilters will cause this, because the index is always a string, not a variable whatsoever..
 
 so the only pace, where this could occur:
 step_size = float(df_filters.loc[df_filters['filterType'] == 'LOT_SIZE']['stepSize'])
 
 in case df_filters['filterType'] == 'LOT_SIZE' results not a slice... only a simple string... which can be only then, when only one comes back as result (kind of cloudly for me, because i don't know how this works exactly, java is much simpler ;))
 
 i assume, None cannot be a result, it will - probably - fail with a different kind of error..
 
 the try/catch block should be smaller and in the catch part, traceback.print_exc() should be there, to get some more info what exactly happening.. (logging the exact result somehow?)

**Comment by fepetoo** [comment]
but maybe i am wrong.. :(
`df_filters.loc[df_filters['filterType'] == 'LOT_SIZE']` will result - according to the documentation - 
```

Raises
    KeyError
        If any items are not found.
    IndexingError
        If an indexed key is passed and its index is unalignable to the frame index.
```

but... 

`.loc is strict when you present slicers that are not compatible (or convertible) with the index type. For example using integers in a DatetimeIndex. These will raise a TypeError.`

and that is exactly what is happening here..  but without the exact data/response.. i don't think we can examine this issue further..

**Comment by schroedermarius** [comment]
I've got that error twice now. If someone provides me with code or a branch to check with, i will be happy to assist. Unfortunately, I am not really into python.

**Comment by fepetoo** [comment]
i have changed a little bit in my fork.. you can test with it if you want..  
a little bit, i changed the code.. some refact :) to be able to do the simulation more "live" like..  and added stacktrace logging in case shtf.. :)

**Comment by veskoz** [comment]
had my first buy ever, unfortunally:
`--------------------------------------------------------------------------------
|                             Python Crypto Bot                                |
--------------------------------------------------------------------------------
|               Release : v2.0.1 (commit: 4)                                   |
--------------------------------------------------------------------------------
|              Bot Mode : LIVE - live trades using your funds!                 |
|           Bot Started : 2021-05-06 21:38:21.791404                           |
================================================================================
|          Sell At Loss : False  --sellatloss 0                                |
|    Sell At Resistance : False  --sellatresistance                            |
|       Trade Bull Only : False  --disablebullonly                             |
|         Buy Near High : True  --disablebuynearhigh                           |
|          Use Buy MACD : True  --disablebuymacd                               |
|           Use Buy OBV : False  --disablebuyobv                               |
|     Use Buy Elder-Ray : False  --disablebuyelderray                          |
|    Sell Fibonacci Low : True  --disablefailsafefibonaccilow                  |
|  Candlestick Reversal : True  --disableprofitbankreversal                    |
|              Telegram : True  --disabletelegram                              |
|                   Log : True  --disablelog                                   |
|               Tracker : False  --disabletracker                              |
================================================================================
`


` 2021-05-07 12:00:00 | ADAEUR 1h | Close: 1.4 | BUY

ADA balance before order: 0.0
EUR balance before order: 50.0
07-05-2021 14:01:14 Binance marketBuy list indices must be integers or slices, not str
ADA balance after order: 0.0
EUR balance after order: 50.0
`

config.json
`{
    "binance" : {
        "api_url" : "https://api.binance.com",
        "api_key" : "secret",
        "api_secret" : "secret",
        "config" : {
            "base_currency" : "ADA",
            "quote_currency" : "EUR",
            "granularity" : "1h",
            "live" : 1,
            "sellatloss" : 0,
            "disablebullonly" : 1,
            "disablebuyobv" : 1,
            "disablebuyelderray" : 1,
            "disablelog" : 0,
            "disabletracker" : 1,
            "buypercent" :30
        }
    },
    "telegram" : {
        "token" : "secret",
        "client_id" : "secret"
    }
}`

**Comment by schroedermarius** [comment]
@fepetoo 
Got an output for you. Did it with your fork:

```
eth     | 2021-05-07 13:00:00 | ETHUSDT | 15m | Close: 3505.04 | *^ EMA12/26: 3463.76 > 3461.77 ^* | ^ MACD: 1.99 > -1.38 ^ | BUY | Last Action: SELL
eth     | 
eth     |  2021-05-07 13:00:00 | ETHUSDT 15m | Close: 3505.04 | BUY 
eth     | 
eth     | ETH balance before order: 0.0
eth     | USDT balance before order: 119.6891
eth     | 07-05-2021 15:03:05 Binance marketBuy list indices must be integers or slices, not str
eth     | Traceback (most recent call last):
eth     |   File "/app/models/Binance.py", line 137, in marketBuy
eth     |     base_quantity = base_quantity - (base_quantity * self.getTradeFee(market))
eth     |   File "/app/models/Binance.py", line 193, in getTradeFee
eth     |     if resp['success']:
eth     | TypeError: list indices must be integers or slices, not str
eth     | 
eth     | During handling of the above exception, another exception occurred:
eth     | 
eth     | Traceback (most recent call last):
eth     |   File "pycryptobot.py", line 974, in <module>
eth     |     s.run()
eth     |   File "/usr/lib64/python3.8/sched.py", line 151, in run
eth     |     action(*argument, **kwargs)
eth     |   File "pycryptobot.py", line 737, in executeJob
eth     |     resp = app.marketBuy(app.getMarket(), last_buy_amount, app.getBuyPercent())
eth     |   File "/app/models/PyCryptoBot.py", line 1579, in marketBuy
eth     |     return api.marketBuy(market, quote_currency, self.is_live == 0)
eth     |   File "/app/models/Binance.py", line 149, in marketBuy
eth     |     traceback.print_exc()
eth     | NameError: name 'traceback' is not defined
```

**Comment by fepetoo** [comment]
thanks, so the traderfee it is.. @schroedermarius great work :)

**Comment by fepetoo** [comment]
pull.. and it should work now.. it was a dependency issue, the docker image will be created i think by @whittlem

**Comment by r-brown** [comment]
> pull.. and it should work now.. it was a dependency issue, the docker image will be created i think by @whittlem

@fepetoo what was the pull request nr.? can you link it here please?

**Comment by fepetoo** [comment]
that was dependency problem... @whittlem  fixed it, so no PR as such you will find

**Comment by gregario** [comment]
Hi all! Sorry to be an absolute pain! What was the dependency issue with this and how was it solved? I'm not running via docker and I experienced this bug today on binance (ETHBUSD). I am running the most recent version of the code (pulled at 8.45AM 14/15/2021). 

> 2021-05-14 09:00:00 | ETHBUSD 15m | Close: 3946.74 | BUY
> 
> ETH balance before order: 0.0
> BUSD balance before order: 206.0559
> *** getTradeFee(ETHBUSD) - missing "success" ***
> [{'symbol': 'ETHBUSD', 'makerCommission': '0', 'takerCommission': '0.001'}]
> *** getTradeFee(ETHBUSD) - missing "tradeFee" ***
> [{'symbol': 'ETHBUSD', 'makerCommission': '0', 'takerCommission': '0.001'}]
> 14-05-2021 09:12:10 Binance marketBuy list indices must be integers or slices, not str
> ETH balance after order: 0.0
> BUSD balance after order: 206.0559
> 2021-05-14 09:14:14 | ETHBUSD | 15m | Current Price: 3949.98
>
