### ISSUE TITLE
Binance marketBuy APIError(code=-2010): Account has insufficient balance for requested action.

### ISSUE THREAD

**Issue by 180-180** [whittlem/pycryptobot#103]
First of all, thanks for sharing your bot project on GitHub :-) I have some trouble on buying  action.

Here is my configuration:
 ```config" : { "base_currency" : "IOTA", "quote_currency" : "USDT", "granularity" : "5m", "live" : 1, "sellatloss" : 0, "disablebullonly" : 1, "disablebuyobv" : 1, "disablebuyelderray" : 1, "disablelog" : 1, "disabletracker" : 1 }```

I have about USDT$ 221 and IOTA 0 balance at Binance and when the bot wants to buy after 5 hours, I got the error below.

2021-05-04 04:25:00 | IOTAUSDT | 5m | Close: 1.96 | *^ EMA12/26: 1.94 > 1.94 ^* | ^ MACD: 0.0 > -0.01 ^ | BUY | Last Action: SELL
2021-05-04 04:25:00 | IOTAUSDT 5m | Close: 1.96 | BUY

IOTA balance before order: 0.0
USDT balance before order: 221.3514
Order quantity after rounding and fees: 112.82
04-05-2021 04:25:19 **Binance marketBuy APIError(code=-2010): Account has insufficient balance for requested action.**
IOTA balance after order: 0.0
USDT balance after order: 221.3514

2021-05-04 04:30:00 | IOTAUSDT | 5m | Close: 1.96 | ^ EMA12/26: 1.95 > 1.94 ^ | ^ MACD: 0.0 > -0.01 ^ | WAIT | Last Action: BUY | -0.42% (delta: 0.0)
support: 1.9634, resistance: 2.0344, fibonacci (l): 1.91, fibonacci (u): 1.97

Could you please explain why the bot fails to buy. Did I configure something wrong? Thanks.

**Comment by delphsmith** [comment]
Looks like my issue few days ago  #74

I found several people mentioning it on other trading project...seems to be a problem with USDT pair ?!
I switched to BUSD and no issue since..

**Comment by whittlem** [comment]
I'm unable to re-create this issue you are seeing. If you are able to provide any additional debug or maybe if someone who is seeing the issue can provide a fix that would be great.

**Comment by 180-180** [comment]
I changed Binance.py as suggested in #74 and set in config.json "verbose" : 1

# remove fees
#base_quantity = base_quantity * 0.9995
base_quantity = base_quantity * 0.75

If the buying problem repeats, I'll reopen the issue with more detailed log. Thanks.

**Comment by delphsmith** [comment]
I wanted to try again and just got a buy on binance with usdt pair...So i still don't know what was the problem before.


2021-05-05 11:51:43 | XVSUSDT (BULL) | 1h | Current Price: 121.021
2021-05-05 11:56:53 | XVSUSDT (BULL) | 1h | Current Price: 121.249
* Candlestick Detected: Hammer ("Weak - Reversal - Bullish Signal - Up")

2021-05-05 10:00:00 | XVSUSDT (BULL) | 1h | Close: 121.55 | *^ EMA12/26: 119.1 > 118.96 ^* | ^ MACD: 0.14 > -0.77 ^ | BUY | Last Action: SELL

 2021-05-05 10:00:00 | XVSUSDT 1h | Close: 121.55 | BUY

XVS balance before order: 0.0
USDT balance before order: 203.166
Order quantity after rounding and fees: 1.669
XVS balance after order: 1.6674
USDT balance after order: 0.1598

Timestamp still funny (UTC+2 for me here), but not a worry
