### ISSUE TITLE
Check between quote_quantity and current price on Binance.py marketBuy()

### ISSUE THREAD

**Issue by stefanoregis** [whittlem/pycryptobot#104]
Guess here's a problem on market buy method 

|             Close : 663.63                                                   |
|             EMA12 : 656.87                                                   |
|             EMA26 : 652.39                                                   |
|    Crossing Above : False                                                    |
|   Currently Above : True                                                     |
|    Crossing Below : False                                                    |
|   Currently Below : False                                                    |
|         Condition : EMA12 is currently above EMA26 and has crossed over      |
|             SMA20 : 660.61                                                   |
|            SMA200 : 593.84                                                   |
--------------------------------------------------------------------------------
|              MACD : 4.47                                                     |
|            Signal : 5.88                                                     |
|   Currently Above : False                                                    |
|   Currently Below : True                                                     |
|         Condition : MACD is currently below Signal and has crossed over      |
--------------------------------------------------------------------------------
|            Action : BUY                                                      |
--------------------------------------------------------------------------------
|                      *** Executing LIVE Buy Order ***                        |
--------------------------------------------------------------------------------
BNB balance before order: 0.0
USDT balance before order: 316.1751
###### before quote check marketBuy  ####### 316.1751 total USDT < 663.67 current price of BNB
BNB balance after order: 0.0
USDT balance after order: 316.1751

In this case is impossible to buy a part of crypto

Guess the problem is related to this part of code in marketBuy of Binance.py

```
 if (quote_quantity < current_price):
                return []

```

I forced the BUY in order to test it because i received some BUY messages on Telegram but the orders were not placed on Binance

Thanks @whittlem :)

**Comment by edrickrenan** [comment]
This just happened here:

```
05/04/2021 10:47:25 AM - INFO: 2021-05-04 09:45:00 | BNBEUR 15m | Close: 547.8 | BUY
05/04/2021 10:47:28 AM - INFO: []
```

**Comment by whittlem** [comment]
I don't recall why I added that. Maybe a failsafe of sorts. I don't think it's adding much value as the Binance API would reject a problematic order anyway so I've removed this. You can "git pull" for the update.
