### ISSUE TITLE
why not use cctx library for connect to exchange

### ISSUE THREAD

**Issue by blademckain** [whittlem/pycryptobot#109]
hey all,
great project, very nice works!
is there a reason why the [cctx library](https://github.com/ccxt/ccxt) is not used which would allow you to connect to many more exchanges?

**Comment by whittlem** [comment]
I want to have as little 3rd party dependencies as possible. I also wanted to standardise all the responses and functionality so that features like the test and simulation modes work. I wont be adding CCTX to my project but you are more than welcome to fork the code and add it yourself.
