### ISSUE TITLE
Bot not sell after ! Profit Bank Triggered (Selling At Resistance)

### ISSUE THREAD

**Issue by yassirkachri** [whittlem/pycryptobot#110]
My Bot is not sell even after ! Profit Bank Triggered (Selling At Resistance)

Coinbase Pro
Market : ADA-EUR
 
   config :          "sellatresistance" : 1,

is it normal or have I to wait ?

**Comment by whittlem** [comment]
It will sell at the resistance level provided the profit for the trade is over 1%. It won't sell at a resistance if it results in a loss.

**Comment by JShezz** [comment]
@whittlem I have the same issue? Surely it should have triggered a sell here? 
![image](https://user-images.githubusercontent.com/82228534/117144908-6a09ba00-adaa-11eb-9ea7-dca7e031134b.png)
