### ISSUE TITLE
sellatresistance selling at little to no profit.

### ISSUE THREAD

**Issue by JShezz** [whittlem/pycryptobot#112]
Hi,

I have recently turned on sellatresistance.

Since then my ETH-GBP bot has made a single buy and sell but for whatever reason it only achieved a 0.13% profit.

![image](https://user-images.githubusercontent.com/82228534/117180431-15773680-adcc-11eb-97c4-8d12407ab6f4.png)

I though it was meant to make atleast 1% before it sold?

Config is as follows:
   "config": {
      "base_currency": "ETH",
      "quote_currency": "GBP",
      "live": 1,
      "sellatloss": 0,
      "disablebullonly": 1,
      "disablebuyobv": 1,
      "disablebuyelderray": 1,
      "disablebuynearhigh": 1,
      "sellatresistance": 1,
      "disablelog": 1,
      "disabletracker": 1
    }

**Comment by djhemp** [comment]
I had a this too. Some did well.  Seems that the timeframe should shorten when that triggers if they start tanking quickly. @whittlem is that possible?  To change granularity to 5 or even 1 min when sellatresitance triggers?

**Comment by iThom** [comment]
Hello,

I also noticed that with sellatresistance=1, it sells very close to the buying price and sometimes it sells lower than the buying price even with sellatloss=0 when it goes with anegative margin and come back to positive that's what's happened to me today.

Config as below:
```
"config" : {
            "base_currency" : "ETH",
            "quote_currency" : "EUR",
            "live" : 1,
	    "sellatloss": 0,
	    "trailingstoploss": -2,
	    "disablebullonly" : 1,
            "disablebuyobv" : 1,
            "disablebuyelderray" : 1,
	    "sellatresistance": 1,
	    "disablebuynearhigh": 1,
	    "disablelog": 1,
	    "disabletracker": 1
 }
```

Here is my logs:

```
2021-05-05 18:28:09 | ETH-EUR | 900 | Current Price: 2825.47
! Profit Bank Triggered (Selling At Resistance)

2021-05-05 16:30:00 | ETH-EUR | 900 | Close: 2843.51 | *^ EMA12/26: 2796.52 > 2792.29 ^* | *^ MACD: 4.23 > 0.91 ^* | SELL | Last Action: BUY | 0.59% (delta: 26.72)
support: 2820.91, resistance: 2906.44, fibonacci (l): 2785.03, fibonacci (u): 2929.7

 2021-05-05 16:30:00 | ETH-EUR 900 | Close: 2843.51 | SELL
 Fibonacci Retracement Levels: {'ratio0_286': 2785.03, 'ratio0': 2929.7}

ETH balance before order: 0.5305
EUR balance before order: 0.0
{'product_id': 'ETH-EUR', 'type': 'market', 'side': 'sell', 'size': 0.5305}
ETH balance after order: 0.0
EUR balance after order: 1494.23
2021-05-05 18:38:13 | ETH-EUR | 900 | Current Price: 2835.27
2021-05-05 18:43:14 | ETH-EUR | 900 | Current Price: 2836.1
2021-05-05 16:45:00 | ETH-EUR | 900 | Close: 2860.0 | ^ EMA12/26: 2804.75 > 2796.57 ^ | ^ MACD: 8.18 > 2.38 ^ | WAIT | Last Action: SELL
2021-05-05 18:53:16 | ETH-EUR | 900 | Current Price: 2860.3
```

Here we see that the bot want to sell at €2843.51 but when I see my order history on Coinbase Pro it sold at €2,826.54 so this make a 0.59% difference.

I think maybe it's needed to make limit orders or to reduce timeframe.

**Comment by whittlem** [comment]
@JShezz, the margin calculation in the bot seems under calculated. I plan to look at it this evening. It should not sell under 1% but as it's miss calculating the margin too low it's selling too low.

@djhemp, can look at reducing the polling. The reason I set it to 5 is a lot of API calls happen each time it polls. I didn't want the exchange to start dropping requests if multiple bots are running. I will reduce it to 3 minutes and see how that goes.

@iThom, I know the resistance level or Fibonacci band can be very close to the buy price sometimes. That is why I said it should only sell if the margin is over 1%. The problem really is the margin is being calculated too low. I will look at this tonight.

I had a couple of buys and sell today which sold at resistance for profit but small amounts sub-1%. I haven't had any losses but it's still not ideal. I'll see what I can do.

**Comment by whittlem** [comment]
Added --lastaction BUY or --lastaction SELL

This will allow you to manually set the starting state, otherwise it will figure it out like it is doing now.

**Comment by JShezz** [comment]
@whittlem Did you close the wrong Issue?

**Comment by iThom** [comment]
It seems so :)

**Comment by whittlem** [comment]
The way the bot is calculating the margin now is wrong. I've been updating it this evening and created a new branch as I want to test it properly myself live before releasing it to all of you. I also noticed that the sell at resistance option wasn't actually checking for a minimum margin. I've added that now so I suggest you pull the update down. This should resolve this issue but I'll leave it open until I've fixed the margin as well.

**Comment by whittlem** [comment]
I've fixed this and pushed and update. Can you confirm it has resolved your issue?

**Comment by JShezz** [comment]
@whittlem It is still possible to get a -1% profit as it doesn't appear to take into account the fee when selling. 

E.g. I just had a trade sell at 1.08% meaning margin was actually only 0.85% due to the 0.35% fee

**Comment by iThom** [comment]
Hello,

I confirm problem with fees calculation with last version of the bot.

I recently had a trade with sellatresistance on (with bug not selling at once in this case it was good for me as the price was even bigger when selling).

Margin calculated by the bot (should be removing fees): 4.51% 
Real margin fees removed: 4.35%

Diff: 0.16% (my Coinbase Pro fees are currently 0.35%)

**Comment by whittlem** [comment]
I increased the minimum margin from 1% to 2%. Did this help?

**Comment by whittlem** [comment]
No response in 25 days. Closing this.
