### ISSUE TITLE
Is a directory: '/app/pycryptobot.log'

### ISSUE THREAD

**Issue by p9qgtjaliucdtygqapv79h5nm1faov8** [whittlem/pycryptobot#115]
```
Traceback (most recent call last):
  File "pycryptobot.py", line 900, in <module>
    logging.basicConfig(filename=app.getLogFile(), format='%(asctime)s - %(levelname)s: %(message)s', datefmt='%m/%d/%Y %I:%M:%S %p', filemode='a', level=logging.DEBUG)
  File "/usr/lib64/python3.8/logging/__init__.py", line 1976, in basicConfig
    h = FileHandler(filename, mode)
  File "/usr/lib64/python3.8/logging/__init__.py", line 1143, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib64/python3.8/logging/__init__.py", line 1172, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
IsADirectoryError: [Errno 21] Is a directory: '/app/pycryptobot.log'
```

Was updating my dockercompose.yml and tried to add logging. Ran into the issue above. My config is:
```
  pycryptobot_btc:
    image: ghcr.io/whittlem/pycryptobot/pycryptobot:latest
    container_name: pycryptobot_btc
    volumes:
      - ./market/btc-usd/config.json:/app/config.json
      - ./market/btc-usd/pycryptobot.log:/app/pycryptobot.log
      - ./market/btc-usd/graphs:/app/graphs
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      restart_policy:
        condition: on-failure
```
It works with the logging line commented out.

**Comment by p9qgtjaliucdtygqapv79h5nm1faov8** [comment]
Solution:
I had not created the pycryptobot.log files before running the compose. Apparently it auto created pycryptobot.log as a folder. To solve this I removed the folders and touched the plycryptobot.log file.

**Comment by letsautom8** [comment]
Right. The template folder contains an empty .log file to avoid the problem described above.

**Comment by whittlem** [comment]
Is this resolved?

**Comment by fepetoo** [comment]
it is s funny one.. yes.. in case you create a volume in the docker-compose and the file not exists, it will create a directory (as is should)

the logfile could be set by an environment variable later... the workaround, create an empty file or remove the line from the compose file

**Comment by p9qgtjaliucdtygqapv79h5nm1faov8** [comment]
Yes this is resolved. I would change the readme to document this:

By default, docker-compose will use the config inside ./market/template. We provide this as a template for any market config. If you create a new folder, make sure to include the config.json and pycryptobot.log files and the graphs folder.

For each market you want to trade, create a copy of this folder under market For example, if you are trading BTCEUR and ETHEUR your market folder should look like this:
```
├── market
│ ├── BTCEUR
│ │ ├── config.json
│ │ ├── pycryptobot.log
│ │ └── graphs
│ └── ETHEUR
│     ├── config.json
│     ├── pycryptobot.log
│     └── graphs
```

**Comment by letsautom8** [comment]
Documentation updated @ #139
