### ISSUE TITLE
Chat server?

### ISSUE THREAD

**Issue by edrickrenan** [whittlem/pycryptobot#118]
Hi @whittlem, 

As per @github-ptaylor's comment on https://github.com/whittlem/pycryptobot/pull/98#issuecomment-831525877, have you considered creating something like a Discord Server or even a slack channel for the people using the bot?

**Comment by whittlem** [comment]
I think maybe a Telegram Channel would be good as people are mostly using Telegram already for the bot. I created a public channel. See if you can join it: https://t.me/pycryptobotchat

**Comment by edrickrenan** [comment]
I joined there, just can't send any message. Maybe you need to enable it?

**Comment by whittlem** [comment]
Seems it needs to be a public Group not Channel. I have updated that.

The invite link is here:
https://t.me/joinchat/09hYKfelbRY2MDNk

But I think you can still access the group here:
https://t.me/pycryptobotchat
