### ISSUE TITLE
Bug: Binance error: marketBuy list indiced must be integers or slices, not str

### ISSUE THREAD

**Issue by schroedermarius** [whittlem/pycryptobot#119]
**Describe the bug**
Got an working ETH / USDT configuration. He was ready to trade and tried to trade ETH:

eth    | 2021-05-06 10:00:00 | ETHUSDT | 15m | Close: 3455.37 | *^ EMA12/26: 3448.44 > 3448.37 ^* | ^ MACD: 0.07 > -3.89 ^ | BUY | Last Action: SELL
eth    | 
eth    |  2021-05-06 10:00:00 | ETHUSDT 15m | Close: 3455.37 | BUY 
eth    | 
eth    | ETH balance before order: 0.0
eth    | USDT balance before order: 119.6891
eth    | 06-05-2021 12:01:57 Binance marketBuy list indices must be integers or slices, not str
eth    | ETH balance after order: 0.0
eth    | USDT balance after order: 119.6891

**Comment by schroedermarius** [comment]
Could it also be, that the bot thinks now, he successfully bought ETH? Getting the following ouputs:

eth    | ! Profit Bank Triggered (Selling At Resistance) 
eth    | 
eth    | ! Ignore Sell Signal (No Sell At Loss) 
eth    | 
eth    | 2021-05-06 12:07:05 | ETHUSDT | 15m | Current Price: 3450.88

**Comment by fepetoo** [comment]
same as #102 
the sell/buy.. there is a new flag to set it manually #107

**Comment by fepetoo** [comment]
can you post your call/config.json? (no api credentials of course)

**Comment by schroedermarius** [comment]
@fepetoo Sure, sorry for the late reply.

```
{
    "binance" : {
        "api_url" : "https://api.binance.com",
        "api_key" : "",
        "api_secret" : "",
        "config" : {
            "base_currency" : "ETH",
            "quote_currency" : "USDT",
            "verbose": 0,
            "live" : 1,
            "sellatloss" : 0,
            "sellupperpcnt": 5,
            "selllowerpcnt": -2,
            "disablebullonly" : 1,
            "disablebuyobv" : 1,
            "disablebuyelderray" : 1,
            "disablelog" : 0,
            "disabletracker" : 1,
            "buypercent" : 25,
            "disablebuynearhigh": 0,
            "sellatresistance" : 1
        }        
    }
}
```

**Comment by fepetoo** [comment]
@schroedermarius  this is pratically a duplicate from #102  hopefully, there will be a new branch/version which is diplaying/logging more info when this occurs...  check out the #102 if you want to put some changes in the code yourself :) i tried to expain the problem there.. (not too much success yet.. sadly)
