### ISSUE TITLE
default granularity is 3600 minutes

### ISSUE THREAD

**Issue by Matterhorn56** [whittlem/pycryptobot#12]
Hey there, and thanks for making this awesome program available to everyone. I noticed that the default granularity is 3600 minutes, but shouldn't it be 60 minutes?

Thanks

**Comment by whittlem** [comment]
Thanks, and I'm glad you like it. Where did you see that? 3600 is definitely seconds not minutes. Maybe it is a typo in a comment somewhere. The granularity is seconds so 1 hour would be 3600 seconds (the default in the bot)
