### ISSUE TITLE
can't even launch the bot

### ISSUE THREAD

**Issue by Pulcow** [whittlem/pycryptobot#120]
**Describe the bug**
python, pip, git installed, everything seems ok, but when i type anything to launch the bot, i got an error

**Expected behavior**
at least, something that's i could search to fix

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 
![Sans titre](https://user-images.githubusercontent.com/20782144/117337663-ee893500-ae9d-11eb-8637-dca2a8b9372b.png)

**Comment by JShezz** [comment]
Please can you share you config.json, it appears to be a problem with the api url you are providing.

**Comment by Pulcow** [comment]
actually i didn't put anything in there, is it obliged? i though this could work only with arguments as mentionned in the last part.

![Sans titre2](https://user-images.githubusercontent.com/20782144/117338396-cc43e700-ae9e-11eb-8e6f-156c658f6a97.png)

**Comment by Pulcow** [comment]
i didn't mentionned that i use pipenv, could this be the problem ?

**Comment by JShezz** [comment]
> actually i didn't put anything in there, is it obliged? i though this could work only with arguments as mentioned in the last part.
> 
> ![Sans titre2](https://user-images.githubusercontent.com/20782144/117338396-cc43e700-ae9e-11eb-8e6f-156c658f6a97.png)

What do you mean by "actually i didn't put anything in there"?

If you config is the same as what you have above it shouldn't be throwing this error.

Can you try added a slash (/)to the end of your api_url

**Comment by Pulcow** [comment]
i tried with this config.json, and still the same error
![Sans titre3](https://user-images.githubusercontent.com/20782144/117340930-c8fe2a80-aea1-11eb-929c-b84b81cf53cc.png)
![Sans titre4](https://user-images.githubusercontent.com/20782144/117340935-cb608480-aea1-11eb-8af2-7d7c53a4246b.png)

**Comment by JShezz** [comment]
Okay I think I have been able to simulate your error.

Make sure that your key, secret and passphrase are surrounded by double quotes not single. As below:
```
    "api_key": "",
    "api_secret": "",
    "api_passphrase": "",
```

**Comment by Pulcow** [comment]
there were already in double quotes unfortunately
![Sans titre5](https://user-images.githubusercontent.com/20782144/117342480-96edc800-aea3-11eb-9689-4d3e389c7292.png)

i don't think the problem is coming from the config.json since i got the same error when im trying directly with arguments

![Sans titre6](https://user-images.githubusercontent.com/20782144/117343693-d5d04d80-aea4-11eb-9b39-041a1ea98bb7.png)

**Comment by JShezz** [comment]
Okay I think I have been able to simulate your error.

{
  "coinbasepro": {
    "api_url": "https://api.pro.coinbase.com",
    "api_key": "",
    "api_secret": "",
    "api_passphrase": "",
    "config": {
      "base_currency" : "BTC",
      "quote_currency" : "EUR",
      "sellatloss": 0,
      "disablebullonly": 1,
      "disablebuyobv": 1,
      "disablebuyelderray": 1,
      "disablebuynearhigh": 1,
      "sellatresistance": 1,
      "disablelog": 1,
      "disabletracker": 1
    }
  },
}
Please remove the , at the end of line 21 that should sort your issue.

**Comment by Pulcow** [comment]
rofl, a comma, thanks you and sorry for your time 

![Sans titre7](https://user-images.githubusercontent.com/20782144/117344917-4035bd80-aea6-11eb-81ff-449a33fa79ca.png)

**Comment by JShezz** [comment]
@Pulcow No Worries, this should probably be handled in a better way rather than erroring out like it did. I will raise another issue so this can be fixed.
