### ISSUE TITLE
Can u please provide a market scanner feature

### ISSUE THREAD

**Issue by googiealas** [whittlem/pycryptobot#123]
Hey Hello, nice work, Followed u on medium, Got a request here,
 Can u please provide a market scanner feature, instead of manually entering the scrips. let the bot decide which coins to trade based on scanner.

List down all the coins based on certain conditions(Trading volume > 100million/week, also based on set of indicators, that user can pass in a json and talibs doing the honors.

**Comment by whittlem** [comment]
I think this is technically possible but complex.

For example how do you make sure you have funds preloaded for the markets as they switch. If you buy BTC with GBP for example and then swap to another market and it tries to buy with GBP there won't be any funds available.

How would you determine which market is a candidate for switching? I don't think you can just do it on volume. You would need to run a fair amount of analysis on each market to determine its suitability.

How long would a market be active before allowing it to switch to another market?

Although this is a nice idea I think it may not be practical to implement in the bot. What I would suggest is maybe creating a wrapper application which does the scanning and analysis and then controls the bot(s) with arguments. I think the scanning and managing of the bots should be one level above the bots.

I'll see if there are any other requests for this in future but for now I don't think this is something that is a good fit for the bot.

If you have your heart set on doing this I suggest going the wrapper route.
