### ISSUE TITLE
ADA size when selli 

### ISSUE THREAD

**Issue by yassirkachri** [whittlem/pycryptobot#126]
**Describe the bug**
A Sell is occured but can 't be accomplished due to  size

ADA balance before order: 368.7799
EUR balance before order: 0.01
{'product_id': 'ADA-EUR', 'type': 'market', 'side': 'sell', 'size': 368.7799}
error: POST (400) https://api.pro.coinbase.com/orders - size is too accurate. Smallest unit is 0.01000000
ADA balance after order: 368.7799
EUR balance after order: 0.01

**Comment by whittlem** [comment]
Fixed.

  # handling: size is too accurate
  if market.startswith('ADA-'):
      # ADA: Smallest unit is 0.01000000
      quote_quantity = round(quote_quantity, 2)
