### ISSUE TITLE
some timestamps in GMT while others are local

### ISSUE THREAD

**Issue by lattacon** [whittlem/pycryptobot#127]
**Description**
severity - very minor
Timestamps printed to logs appear to be based on different timezones. For instance, if running from EST timezone:
```
2021-05-07 11:00:00 | LTC-USD | 900 | Close: 361.58 | ^ EMA12/26: 363.82 > 361.89 ^ | v MACD: 1.92 < 2.97 v | WAIT | Last Action: SELL
2021-05-07 07:05:19 | LTC-USD | 900 | Current Price: 358.93```

**To Reproduce**
Steps to reproduce the behavior:
1. be in a timezone other than GMT
2. run script
3. observe timestamps in output

**Expected behavior**
timestamps are consistent in log output

**Desktop (please complete the following information):**
 - OS: macOS Big Sur

**Comment by whittlem** [comment]
I've seen this issue with people trading from countries outside of the timezone of the exchange. The top time is the time of the last interval of data from the exchange (the exchange time). The bottom time is your local system time when the price was polled. It is a cosmetic issue even though it is a little irritating. I did try and fix this but adding in the additional API call to get the exchange time caused increased latency. I will have another go and fixing this.

**Comment by whittlem** [comment]
Should be fixed now. Pull down the new code with "git pull".
