### ISSUE TITLE
Small simulation dataset

### ISSUE THREAD

**Issue by Yury-MonZon** [whittlem/pycryptobot#140]
**Describe the bug**
I'm trying to run a simulation with the start date of yesterday. I receive a warning that the dataset is too small, but got exception after that.

**To Reproduce**
`debian@debian10:~/Documents/CryptoBot/pycryptobot$ python3 pycryptobot.py --market BTCUSDT --sellupperpcnt 3 --verbose 1 --graphs 0 --simstartdate 2021-05-09 --sim fast-sample
--------------------------------------------------------------------------------
|                             Python Crypto Bot                                |
--------------------------------------------------------------------------------
|               Release : v2.0.3                                               |
--------------------------------------------------------------------------------
|                Market : BTCUSDT                                              |
|           Granularity : 1h                                                   |
--------------------------------------------------------------------------------
|              Bot Mode : TEST - test trades using dummy funds :)              |
|           Bot Started : 2021-05-10 06:05:57.559919                           |
================================================================================
|        Sell Upper : 3.0%                                                     |
|          Sell At Loss : True  --sellatloss 1                                 |
|    Sell At Resistance : True  --sellatresistance                             |
|       Trade Bull Only : True  --disablebullonly                              |
|         Buy Near High : True  --disablebuynearhigh                           |
|          Use Buy MACD : True  --disablebuymacd                               |
|           Use Buy OBV : True  --disablebuyobv                                |
|     Use Buy Elder-Ray : True  --disablebuyelderray                           |
|    Sell Fibonacci Low : True  --disablefailsafefibonaccilow                  |
|       Sell Upper Pcnt : True  --disableprofitbankupperpcnt                   |
|  Candlestick Reversal : True  --disableprofitbankreversal                    |
|              Telegram : True  --disabletelegram                              |
|                   Log : True  --disablelog                                   |
|               Tracker : True  --disabletracker                               |
================================================================================
Attempting to retrieve data from 09 May, 2021
Attempting to retrieve data from 09 May, 2021
Attempting to retrieve data from 09 May, 2021
Attempting to retrieve data from 09 May, 2021
Attempting to retrieve data from 09 May, 2021
Attempting to retrieve data from 09 May, 2021
Attempting to retrieve data from 09 May, 2021
Attempting to retrieve data from 09 May, 2021
Attempting to retrieve data from 09 May, 2021
Attempting to retrieve data from 09 May, 2021
|    Sampling start : 2021-05-09T00:00:00                                      |
|      Sampling end : 2021-05-21T12:00:00                                      |
|     WARNING: Using less than 300 intervals                                   |
|     Interval size : 31                                                       |
================================================================================
Exception('Data range too small.')
Restarting application after exception...
Attempting to retrieve data from 09 May, 2021
Attempting to retrieve data from 09 May, 2021
Attempting to retrieve data from 09 May, 2021
Attempting to retrieve data from 09 May, 2021
Attempting to retrieve data from 09 May, 2021
Attempting to retrieve data from 09 May, 2021
Attempting to retrieve data from 09 May, 2021
Attempting to retrieve data from 09 May, 2021
Attempting to retrieve data from 09 May, 2021
Attempting to retrieve data from 09 May, 2021
Exception('Data range too small.')
Restarting application after exception...
Attempting to retrieve data from 09 May, 2021
Attempting to retrieve data from 09 May, 2021
Attempting to retrieve data from 09 May, 2021
Attempting to retrieve data from 09 May, 2021
Attempting to retrieve data from 09 May, 2021
Attempting to retrieve data from 09 May, 2021
Attempting to retrieve data from 09 May, 2021
Attempting to retrieve data from 09 May, 2021
Attempting to retrieve data from 09 May, 2021
Attempting to retrieve data from 09 May, 2021
Exception('Data range too small.')
Restarting application after exception...
Attempting to retrieve data from 09 May, 2021
Attempting to retrieve data from 09 May, 2021
Attempting to retrieve data from 09 May, 2021
Attempting to retrieve data from 09 May, 2021
`

**Expected behavior**
Run the simulation with that small dataset

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Version 2.0.3 from github, Binance exchange

**Comment by letsautom8** [comment]
This is because the number of candlesticks is less than ideal to deduce some meaningful assessment. I think we are using 300 candlestick as minimum right @whittlem ?
Try adding granularity like 15m or 5m and let us know the results.

**Comment by whittlem** [comment]
I'm not sure if "--simstartdate 2021-05-09" and "--sim fast-sample" should be used together. Sim start date tells the simulation retrieving the 300 intervals of data. 2021-05-09 is too recent and you won't have enough data. If you want the most recent data then leave that off. Sim fast-sample will go and try and collect 300 intervals of data over the last 5 or so years. Sometimes it needs to retry if for some reason not enough data was found. It sounds like all you should be doing is adding "--sim fast". Leave the other two off.
