### ISSUE TITLE
Field "filled" not present on orders payload

### ISSUE THREAD

**Issue by edrickrenan** [whittlem/pycryptobot#141]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the bot when the last action was BUY

**Additional context**
On https://github.com/whittlem/pycryptobot/blob/main/pycryptobot.py#L73, the filled attribute doesn't exist for Binance orders (At least when I was debugging, it wasn't present there). So, every time I try to start the bot it doesn't start.

```
Traceback (most recent call last):
  File ".../pycryptobot/pycryptobot.py", line 73, in <module>
    state.last_buy_filled = float(df[df.action == 'buy']['filled'])
  File "...\pycryptobot\venv\lib\site-packages\pandas\core\frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "...\pycryptobot\venv\lib\site-packages\pandas\core\indexes\base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'filled'
```

**Comment by whittlem** [comment]
Ok, I know what the problem is. I will fix it. Thanks.

**Comment by edrickrenan** [comment]
This issue seems to be fixed now, @whittlem. Thank you
