### ISSUE TITLE
Don't take trades near resistance

### ISSUE THREAD

**Issue by adriano26010** [whittlem/pycryptobot#145]
**Is your feature request related to a problem? Please describe.**
Described problem was found on CoinbasePro trade, market: MANA-USDC.
Bot took trade as you can see in from .log
`05/10/2021 03:01:36 AM - DEBUG: 2021-05-10 03:00:00 | MANA-USDC | 900 | Close: 1.5 | ^ EMA12/26: 1.49 > 1.47 ^ | *^ MACD: 0.01 > 0.01 ^* | BUY | Last Action: SELL`
`05/10/2021 03:01:36 AM - INFO: 2021-05-10 03:00:00 | MANA-USDC 900 | Close: 1.5 | BUY`

However, when I'm running simulation now, it now longer enters trade as MACD is not flashing:
`05/10/2021 07:18:16  - DEBUG: 2021-05-10 03:00:00 | MANA-USDC | 900 | Close: 1.48 | ^ EMA12/26: 1.48 > 1.47 ^ | v MACD: 0.01 < 0.01 v | WAIT | Last Action: BUY | -2.49% (delta: -0.02)`

As you can see on screenshot in additional context (screenshot 1), MACD was going to reset and flash buy signal. However it meet strong decline (screenshot 2), which caused trend reversal. 

Another posibility is that coinbase has send wrong data. You can see close price differs between live and simulation.
This has caused MACD signal to flash, and took trade.

**Describe the solution you'd like**
One thing is to prevent bot from taking trades near resistance. 

**Describe alternatives you've considered**

**Additional context**
Both screenshots are from trading view
MANA-USDC 15min. Yellow vertical line is entry time (it's 5:00 on it as I'm in Poland which is in UTC+2). White line is entry price.

Screenshot 1
![image](https://user-images.githubusercontent.com/37125018/117709210-f3692400-b1d0-11eb-888d-4c63a026a792.png)

Screenshot 2
![image](https://user-images.githubusercontent.com/37125018/117709242-fcf28c00-b1d0-11eb-9e18-7e55671f58c6.png)

**Comment by whittlem** [comment]
This was maybe because of the incorrect margin calculation. Is this resolved now?

**Comment by adriano26010** [comment]
I don't think it's a margin calculation error, as the bot doesn't look at it when generating the BUY signal.

**Comment by whittlem** [comment]
@adriano26010, since the margin has been fixed in the latest versions is this resolved now?

**Comment by whittlem** [comment]
It's fixed now.
