### ISSUE TITLE
Complexity of Coinbase Pro API Passphrase Arbitarily Limited by Input Validation

### ISSUE THREAD

**Issue by eatsleeproute** [whittlem/pycryptobot#147]
Coinbase allows manual input of the API passphrase, complex strings including uppercase, lowercase, numbers, and special characters are permitted. For example *n3by9t338097^%YGAKUDLID!* is permitted.

This regex, found on models/CoinbasePro.py line 67, is used to validate the API passphrase input:

`^[a-z0-9]{10,11}$`

This arbitarily limits the API passphrase to 11 characters with only lowercase and numbers possible. I haven't made a pull request for an alternative regex as I'm not sure what the actual limits for the field on Coinbase are or whether the currently configured limit is important when the value is used elsewhere in the script and am not sure what would be a still *safe* but looser regex.

I realise this is a very trivial issue in an awesome project but thought I should point it out in case it helps anyone who might be wondering why their custom passphrase isn't accepted.

**Comment by whittlem** [comment]
I didn't realise Coinbase Pro allowed you to specify your own keys. That makes things a little challenging. I will include the special chars you mention above as a start. I will also allow a wider range in key size. We can start with that and see how it goes.

**Comment by whittlem** [comment]
A PR was put through to allow this. Can you confirm it's working now?

**Comment by eatsleeproute** [comment]
The changes from the PR don't seem to be merged, behaviour hasn't changed.

**Comment by whittlem** [comment]
@eatsleeproute, this should be fixed now. Can you please confirm?

**Comment by whittlem** [comment]
I've implemented this. I allowed keyboard characters greater with a length between 8 and 32. That should give enough flexibility.

p = re.compile(r"^[A-z0-9#$%=@!{},`~&*()<>?.:;_|^/+\[\]]{8,32}$")
