### ISSUE TITLE
no response to simstartdate command (v2.0.6)

### ISSUE THREAD

**Issue by Nonkes** [whittlem/pycryptobot#168]
Goodmorning @whittlem,

I have some problems with running simulations from certain date using simstartdate. I implemented it in my config.json (please see below) but it doesn't seem to use the date given. Am I implementing it the wrong way? Thanks in advance. Lourens

my config.json:

{
    "coinbasepro" : {
        "api_url" : "https://api.pro.coinbase.com",
        "api_key" : "xxx",
        "api_secret" : "xxx",
        "api_passphrase" : "xxx",
        "config" : {
            "base_currency" : "BTC",
            "quote_currency" : "EUR",
            "live" : 0,
            "smartswitch" : 1,
            "sellatloss" : 1,
            "disablebuyobv" : 0,
            "disablebuyelderray" : 0,
            "disablebullonly" : 0,
            "disablebuymacd" : 0,
            "disablebuynearhigh" : 0,
	    "sim" : "fast",
	    "simstartdate" : "2021-01-01"
			
			
        }
	}
     
     
}

**Comment by whittlem** [comment]
The simulation commands aren't usually passed in the config.json.

Remove "sim" and "simstartdate" from your config.json and run this:
python3 pycryptobot --sim fast --simstartdate 2021-01-01

Let me know if this works for you.

**Comment by Nonkes** [comment]
No, strange enough does that also not work for me (starts at 2021-05-01). 

(Got a fresh install via git clone https://github.com/whittlem/pycryptobot, got config without sim commands and afterwards ran bot via python pycryptobot.py --sim fast --simstartdate 2021-01-01 // did not work for me)

**Comment by marioK93** [comment]
simstartdate only works with the sample sims, use this in your config:

"sim" : "fast-sample",
"simstartdate" : "2021-05-01"

**Comment by Nonkes** [comment]
Thank you very much! That indeed works nicely!
