### ISSUE TITLE
Telegram client_id not showing up on api.telegram.org/botXXX:YYYYY

### ISSUE THREAD

**Issue by devinat1** [whittlem/pycryptobot#172]
**Describe the bug**
When attempting to connect a bot on telegram, I follow all the steps and am able to get to the point where a new bot is created along with the API token. However, when I attempt to get the client_id by going to https://api.telegram.org/botXXX:YYYYY/getUpdates, I do not have a chat entry in the JSON (Only the ok section and result section): {"ok":true,"result":[]}.

**To Reproduce**
I followed the steps on this article: https://medium.com/coinmonks/pycryptobot-with-telegram-83eed5f230c2

**Expected behavior**
Shows a chat section where I can get the client_id

**Screenshots**
![image](https://user-images.githubusercontent.com/15788108/118125240-01988980-b3f7-11eb-9156-efd262b210d8.png)

**Desktop:**
 - OS: Windows, Linux
 - Browser Firefox, Chrome

**Comment by xLinkOut** [comment]
You missed the endpoint in the url that allows you to receive messages sent to the bot. Use: `https://api.telegram.org/botXXX:YYYYY/getUpdates`.

**Comment by devinat1** [comment]
> 
> 
> You missed the endpoint in the url that allows you to receive messages sent to the bot. Use: `https://api.telegram.org/botXXX:YYYYY/getUpdates`.

My bad, forgot to put the endpoint in the issue but with the endpoint it gives the behavior I mentioned.

**Comment by Yury-MonZon** [comment]
You have to send a text message to your bot before getting an id.

**Comment by devinat1** [comment]
> 
> 
> You have to send a text message to your bot before getting an id.

That fixed that issue thanks! However, when running pycryptobot.py now I am getting "Exception: There is an error in your config dictionary".

**Comment by whittlem** [comment]
Glad you got your Telegram working.

You probably have a syntax issue in your config.json.

Use this as a template and delete/edit the relevant parts.

    {
        "binance" : {
            "api_url" : "https://api.binance.com",
            "api_key" : "",
            "api_secret" : "",
            "config" : {
                "base_currency" : "BTC",
                "quote_currency" : "GBP",
                "live" : 0,
                "sellatloss" : 0,
                "sellatresistance" : 1,
                "disablebullonly" : 1,
                "disablebuynearhigh" : 1,
                "disablebuyobv" : 1,
                "disablebuyelderray" : 1,
                "disablelog" : 1,
                "disabletracker" : 1,
                "autorestart" : 1
            }        
        },
        "coinbasepro" : {
            "api_url" : "https://api.pro.coinbase.com",
            "api_key" : "",
            "api_secret" : "",
            "api_passphrase" : "",
            "config" : {
                "base_currency" : "BTC",
                "quote_currency" : "GBP",
                "live" : 1,
                "sellatloss" : 0,
                "sellatresistance" : 1,
                "disablebullonly" : 1,
                "disablebuynearhigh" : 1,
                "disablebuyobv" : 1,
                "disablebuyelderray" : 1,
                "disablelog" : 1,
                "disabletracker" : 1,
                "autorestart" : 1
            }
        },
        "telegram" : {
            "token" : "",
            "client_id" : ""
        }
    }

If you are not in our Telegram group chat already I suggest you join. A lot of people there who can help you with this.

**Comment by devinat1** [comment]
Ok thanks for the suggestion it worked for me! I will join the telegram group chat.
