### ISSUE TITLE
Unable to add 2nd exchange on Coinbase Pro (ETH-USD)

### ISSUE THREAD

**Issue by devinat1** [whittlem/pycryptobot#173]
**Describe the bug**
I added two portfolios into coinbase pro (BTC-USD and ETH-USD). The bot worked for BTC-USD with the API key, but when attempting the same after creating an API key for ETH-USD and putting in the config.json under a different cloned repo (I followed the steps on this article: https://medium.com/coinmonks/python-crypto-bot-pycryptobot-b54f4b3dbb75) I got the following error after running pycryptobot.py:
Traceback (most recent call last):
  File "/home/qd/ETH-USD/pycryptobot.py", line 18, in <module>
    app = PyCryptoBot()
  File "/home/qd/ETH-USD/models/PyCryptoBot.py", line 1261, in __init__
    raise TypeError('Coinbase Pro API passphrase is invalid')
TypeError: Coinbase Pro API passphrase is invalid

I attempted to run on a different machine with the same behavior (API key, id, etc. works for BTC-USD but not for ETH-USD).
I was also using the "basic" JSON format without binance or any other exchange (just the coinbase pro json block)

**Comment by p9qgtjaliucdtygqapv79h5nm1faov8** [comment]
I have run into this several times and the solution is to generate a new API key. For the issue has been caused by user error. Ex. Not copying the correct passphrase down or accidently deleting a " from the config.json. This type error is the expected result of something being wrong in the config.json. It might help diagnostics if you post a redacted config.json file.

**Comment by devinat1** [comment]
> 
> 
> I have run into this several times and the solution is to generate a new API key. For the issue has been caused by user error. Ex. Not copying the correct passphrase down or accidently deleting a " from the config.json. This type error is the expected result of something being wrong in the config.json. It might help diagnostics if you post a redacted config.json file.

I tried it a couple times and on a linux machine as well to no avail. Perhaps its something with the ETH currency. Here is the config.json:
{
        "api_url" : "https://api.pro.coinbase.com",
        "api_key" : "REDACTED",
        "api_secret" : "REDACTED",
        "api_passphrase" : "REDACTED",
        "config" : {
                "base_currency" : "ETH",
                "quote_currency" : "USD",
                "live" : 1,
                "sellatloss" : 0
        }
}

**Comment by p9qgtjaliucdtygqapv79h5nm1faov8** [comment]
I have a very similar config for ETH and mine works. I still recommend generating a new api key for that portfolio.

```
{
    "api_url" : "https://api.pro.coinbase.com",
    "api_key" : "...",
    "api_secret" : "...",
    "api_pass" : "...",
    "config" : {
        "base_currency" : "ETH",
        "quote_currency" : "USD",
        "live" : 1,
        "verbose" : 0,
        "sellatloss" : 0
    }
}
```

**Comment by whittlem** [comment]
I agree this looks more like a user error.

This is the relevant parts of my config.json.

{
        "coinbasepro" : {
            "api_url" : "https://api.pro.coinbase.com",
            "api_key" : "",
            "api_secret" : "",
            "api_passphrase" : "",
            "config" : {
                "base_currency" : "ETH",
                "quote_currency" : "GBP",
                "live" : 1,
                "sellatloss" : 0,
                "sellatresistance" : 1,
                "disablebullonly" : 1,
                "disablebuynearhigh" : 1,
                "disablebuyobv" : 1,
                "disablebuyelderray" : 1,
                "disablelog" : 1,
                "disabletracker" : 1,
                "autorestart" : 1
            }
        }
    }

Copy your API keys into the placeholders and it should work. Only paste the keys in between the "" to avoid adding any special characters at the end.
