### ISSUE TITLE
Launch with KeyError: 'currency' on Binance

### ISSUE THREAD

**Issue by gregario** [whittlem/pycryptobot#176]
**Describe the bug**
When I launch with Binance trading both EOS EUR and also tried with EOS BUSD, I received the error KeyError: 'currency' 

The code was pulled from the repository directly before trying. See attached for a screenshot. 

![image](https://user-images.githubusercontent.com/2814770/118152603-cc973180-b40c-11eb-87af-9861721ba572.png)

**Comment by whittlem** [comment]
I'm not able to re-create the issue you are having:
% python3 pycryptobot.py --exchange binance --market EOSEUR --live 0
% python3 pycryptobot.py --exchange binance --market EOSBUSD --live 0

Can you make sure you are running the latest code with "git pull" and try again?

**Comment by gregario** [comment]
I was 100% running the latest code at the time. I did a git pull directly before it ran. I'll try to recreate the issue again and give a more detailed output for you, thanks!

**Comment by letsautom8** [comment]
@gregario is this still happening?

**Comment by gregario** [comment]
Heya - The bot didn't work for me for about a week, tried debugging but no joy. I'm not sure if it's still a problem as I spun up my own DCA bot for the dip and have been focusing on that.
