### ISSUE TITLE
Coinbase Pro granularity can't be set from command line args

### ISSUE THREAD

**Issue by taylorasdfjkl** [whittlem/pycryptobot#178]
It looks like the granularity argument is parsed as a string with argparse to support both coinbasepro and binance formats, but
it never gets converted to an int before this line, so it doesn't ever get set.

https://github.com/whittlem/pycryptobot/blob/5ff91ed385074b17d63d0051c427f506ead788ab/models/config/coinbase_pro_parser.py#L82

**Comment by whittlem** [comment]
Fixed, thanks.

        if 'granularity' in config and config['granularity'] != None:
            if config['granularity'].isnumeric() is True:
                config['granularity'] = int(config['granularity'].isnumeric())

            if isinstance(config['granularity'], int):

**Comment by taylorasdfjkl** [comment]
Thanks for the quick fix, but I think you just assigned a 1 (int(True)) to config['granularity']  instead of the granularity integer value.
