### ISSUE TITLE
Release version in incorrectly displayed

### ISSUE THREAD

**Issue by Sekuiya** [whittlem/pycryptobot#181]
Currently, it seems that the bot takes the version directly from the repo.
This may lead the user to think they have the latest version of the bot, when looking at the logs, when in fact they do not.

A manual version change might be needed, at least at every numbered release.
This change also has the advantage of then being able to tell the user, at bot launch, if there's a new version.

https://github.com/whittlem/pycryptobot/blob/e9c99e902b324eeec743aa004daa9b3da1e5579c/models/PyCryptoBot.py#L553

**Comment by Yury-MonZon** [comment]
As far as I can see - this is fixed. Now version number is taken from README file.
