### ISSUE TITLE
Bot not starting anymore (coinbase only, binance OK)

### ISSUE THREAD

**Issue by delphsmith** [whittlem/pycryptobot#184]
**Describe the bug**

Bot on coinbase not starting anymore since last pull (13/05)

**To Reproduce**
start the bot :

python3 pycryptobot.py --config ../Config/ETHconfig.json
Traceback (most recent call last):
  File "pycryptobot.py", line 21, in <module>
    app = PyCryptoBot()
  File "/home/jeedom/delph/pycryptobot/models/PyCryptoBot.py", line 135, in __init__
    coinbaseProConfigParser(self, config['coinbasepro'], args)
  File "/home/jeedom/delph/pycryptobot/models/config/coinbase_pro_parser.py", line 82, in parser
    if config['granularity'].isnumeric() is True:
AttributeError: 'int' object has no attribute 'isnumeric'

**Desktop (please complete the following information):**
Raspberry

**Additional context**
I have granularity set at 3600 in config.json

**Comment by letsautom8** [comment]
Could u pls send your config.json here with API values removed

**Comment by delphsmith** [comment]
yes sure :

{
    "coinbasepro" : {
        "api_url" : "https://api.pro.coinbase.com",
        "api_key" : "",
        "api_secret" : "",
        "api_passphrase" : "",
        "config" : {
            "base_currency" : "ETH",
            "quote_currency" : "DAI",
            "verbose" : 0,
            "graphs" : 0,
            "sellatloss" : 0,
            "granularity" : 3600,
            "live" : 1,
            "disablebuyobv" : 1,
            "disablebuyelderray" : 1,
            "disableprofitbankreversal" : 1
        }
    },
    "telegram" : {
        "token" : "",
        "client_id" : ""
    }
}


It was working fine before yesterday..

**Comment by delphsmith** [comment]
Without granularity set in the .json, it's working

**Comment by edrickrenan** [comment]
@delphsmith, a big refactoring yesterday broke some of the arguments passed via CLI.

**Comment by ThomasLENNE** [comment]
Got the same. According to python documentation, the .isnumeric() method only apply to string

**Comment by delphsmith** [comment]
Thanks @ThomasLENNE , that's ok with "3600" !

**Comment by matteodefelice** [comment]
I had to revert to an old commit because the code was not working any more on my raspberry. @delphsmith can you share your setup? Which python version are you using?

**Comment by delphsmith** [comment]
Hi @matteodefelice  i have python 3.9. You juste need to add the "" on the granularity :

"granularity" : "3600",

Just so you know, it's not the way @whittlem coded it at first, it's an error after the pull from one other guys, and i think it will be fixed back as an integer really soon. at least right know it's working with this "fix" :)

**Comment by matteodefelice** [comment]
How could you install Python 3.9 on the raspberry? I failed in having it with all the needed libs.

**Comment by delphsmith** [comment]
Oh yeah, it was a pain in the ass ...i think the first time, i managed by installing one by one each lib, and not via the requirement.txt

But then i had to format everything again and reinstall JEEDOM (32bits) on my rasp,  and then it went smoothly for the install of the bot...
so i don't really know how to help you more :-/

**Comment by delphsmith** [comment]
and I never succeeded to use the docker version...
