### ISSUE TITLE
balance before order - round up issue

### ISSUE THREAD

**Issue by horamarques** [whittlem/pycryptobot#185]
Purchase failed due to a round up on current balance:

xlm-eur    | XLM balance before order: 0.0
xlm-eur    | EUR balance before order: 510.77
xlm-eur    | error: POST (400) https://api.pro.coinbase.com/orders - Insufficient funds
xlm-eur    | XLM balance after order: 0.0
xlm-eur    | EUR balance after order: 510.77

The total value on Euro account was 510.769.

**Comment by horamarques** [comment]
**way to fix this:**

on models/exchange/coinbase_pro/api.py

on method: 
```
def marketBaseIncrement(self, market, amount) -> float:**
     ...
    #return float(f'%.{nb_digits}f'%(amount))
    return float(np.floor(amount * (10 ** nb_digits)) / (10 ** nb_digits))
```

like this we will never round up and exeed the total amount.

**Comment by marioK93** [comment]
Hi,

Can you make a PR for your change please.

Thanks
