### ISSUE TITLE
Bot didnt buy BTC on buy signal

### ISSUE THREAD

**Issue by ravening** [whittlem/pycryptobot#189]
**Describe the bug**
I see that the bot got the BUY signal and displayed the logs also but it didnt buy any BTC. No error logs also

**To Reproduce**
```
python3 pycryptobot.py  --selllowerpcnt -2 --disablebullonly --sellupperpcnt 5 --trailingstoploss 2 --disablebuyobv
```

**Expected behavior**
The bot was supposed to buy BTC

**Screenshots**
```
2021-05-14 15:00:00 | BTCEUR 1h | Close: 42470.8 | BUY

BTC balance before order: 0.0001
EUR balance before order: <left out on purpose>
BTC balance after order: 0.0001
EUR balance after order: 
```

**Desktop (please complete the following information):**
 - OS: Linux
```
--------------------------------------------------------------------------------
|                             Python Crypto Bot                                |
--------------------------------------------------------------------------------
|               Release : v2.1.0 (commit: 4)                                   |
--------------------------------------------------------------------------------
|              Bot Mode : LIVE - live trades using your funds!                 |
|           Bot Started : 2021-05-14 15:21:31.614837
```

**Additional context**
No errors in log. where else can I find more debug logs?

**Comment by tizbecool** [comment]
the message "<left out on purpose>" come from the binance or coinbase api, there is may be a problem with your portfolio. It was with binance or coinbase ?

**Comment by ravening** [comment]
> the message "left out on purpose" come from the binance or coinbase api, there is may be a problem with your portfolio. It was with binance or coinbase ?

I am using binance

**Comment by whittlem** [comment]
I'm not quite sure to start with this. Has it happened again since you raised this issue? Can you please make sure you are running the latest code with "git pull".

**Comment by ravening** [comment]
It has nothappened again so far because there is no buy signal yet. I have kept it running. I will see if this happens again when buy signal is generated

**Comment by whittlem** [comment]
@ravening Any news? Is this resolved?
