### ISSUE TITLE
Support more exchanges, TA criteria, and real-time websocket connections to exchanges

### ISSUE THREAD

**Issue by rcarmo** [whittlem/pycryptobot#197]
**Is your feature request related to a problem? Please describe.**

I've been looking at ways to make the bot more flexible and efficient, and investigated several solutions.

**Describe the solution you'd like**

Refactoring the bot to use [ccxt](https://pypi.org/project/ccxt/) and [pandas-ta](https://pypi.org/project/pandas-ta/) might significantly reduce the code base (and remove the need to maintain that code).

**Describe alternatives you've considered**

There are also SWIG bindings for [TA-Lib](https://www.ta-lib.org/), but they are harder to deal with, and [copra](https://pypi.org/project/copra/) for Coinbase Pro, which is both async and supports websockets for real-time monitoring (roughly up to 3 ticker updates/s).

**Comment by whittlem** [comment]
Thanks for the feature request but I would prefer not use 3rd party libraries unless I absolutely have too. I want to keep as much control as possible within this project. I've already had issues with python-binance which is out of my control to fix. As the bot is handling people's "money" I don't want to use unknown code. At least with my project the code is fairly simple to follow and everyone knows what it is doing. I appreciate your refactoring and improvements though. You have been a great help.
