### ISSUE TITLE
log file not working after refactoring

### ISSUE THREAD

**Issue by achillebnt** [whittlem/pycryptobot#198]
After refactoring bot is not writing log file.

Problem is caused by file _pycryptobot/models/config/binance_parser.py_ row _91_

logger is invoked before **logging.basicConfig** in the **pycryptobot.py:1035** so module not handle the file.

Quick solution is comment row in bynance_parser.py

**Comment by whittlem** [comment]
A lot of updates have happened since your issue was raised. This may be been fixed already. Can you confirm you are running the latest code and if this is resolved or still an issue for you? I'm not aware of anyone else who is having a problem.

**Comment by 8080git** [comment]
I also have the bug that the log is no longer generated

**Comment by achillebnt** [comment]
Using Python >=3.9 the problem is "_resolved_".

**Comment by 8080git** [comment]
I use python 3.9. the log file is not written

**Comment by achillebnt** [comment]
> I use python 3.9.5 the log file is not written.

If you use binance try to erease line 91 in pycryptobot/models/config/binance_parser.py

**Comment by 8080git** [comment]
I have deleted line 98, but I had no effect. I tried running yes in a standard way than passing the parameter --logfile myfile.log

**Comment by achillebnt** [comment]
> I have deleted line 98, but I had no effect. I tried in a standard way and passing the parameter --logfile myfile.log

You right, i recheck the code and in main file after telegram refactoring the parameter about file was commented.   https://github.com/whittlem/pycryptobot/blob/298accc1d4afcfd490e338fd818065bf51c52494/pycryptobot.py#L990

**Comment by 8080git** [comment]
with the new release I have logs again, great job now it is much more efficient to write logs. 
Thank you so much for the wonderful work.
