### ISSUE TITLE
Cant specify granularity of 1m

### ISSUE THREAD

**Issue by ravening** [whittlem/pycryptobot#20]
Im getting error when specifying 1m as granularity

```
▶ python3 pycryptobot.py --granularity 1m
--------------------------------------------------------------------------------
|                             Python Crypto Bot                                |
--------------------------------------------------------------------------------
|          Bot Mode : TEST - test trades using dummy funds :)                  |
|       Bot Started : 2021-04-01 17:35:31.677124                               |
================================================================================
Exception: Something went wrong!
```

Same error even when mentioning `"granularity" : "1m",` in `config.json`

`5m` works fine though

```
python3 pycryptobot.py --granularity 5m
--------------------------------------------------------------------------------
|                             Python Crypto Bot                                |
--------------------------------------------------------------------------------
|          Bot Mode : TEST - test trades using dummy funds :)                  |
|       Bot Started : 2021-04-01 17:36:40.428803                               |
================================================================================
2021-04-01 15:35:00 | BTCEUR (BEAR) | 5m | Close: 50250.0 | ^ EMA12/26: 50245.46 > 50203.67 ^ | ^ MACD: 41.79 > 40.27 ^ | ^ OBV: -86.2756 (4.13%) ^ | ERI: buy | WAIT
```

**Comment by whittlem** [comment]
It looks like you are trying to use Binance...

python3 pycryptobot.py --exchange binance --granularity 5m

An example of what the config.json looks like provided you want to use both Coinbase Pro and Binance. If not just leave oen of the sections out.

{
    "binance" : {
        "api_url" : "https://api.binance.com",
        "api_key" : "<removed>",
        "api_secret" : "<removed>",
        "config" : {
            "base_currency" : "BTC",
            "quote_currency" : "ZAR",
            "granularity" : "1h",
            "live" : 0,
            "verbose" : 0
        }        
    },
    "coinbasepro" : {
        "api_url" : "https://api.pro.coinbase.com",
        "api_key" : "<removed>",
        "api_secret" : "<removed>",
        "api_passphrase" : "<removed>",
        "config" : {
            "base_currency" : "BTC",
            "quote_currency" : "GBP",
            "granularity" : "3600",
            "live" : 0,
            "verbose" : 0
        }    
    }
}

**Comment by ravening** [comment]
Yes I'm using binance. I have removed all other unwanted configs.

So binance doesn't support 1m internal?

**Comment by whittlem** [comment]
No, I have only enabled the same intervals as Coinbase Pro for consistency. The smallest is 5m. I really would not trade on graphs less than 15m. Otherwise you are guaranteed to lose money. The best is 1h normally and 15m in strong bull conditions.

**Comment by ravening** [comment]
Understood. I was running in test mode and wanted to see how the actual output looks like in short interval
