### ISSUE TITLE
1INCH ticker is not recognized

### ISSUE THREAD

**Issue by Yury-MonZon** [whittlem/pycryptobot#200]
**Describe the bug**
Bot does not recognize 1INCH ticker

**To Reproduce**
`python3 pycryptobot.py --market 1INCHUSDT --verbose 1 --disablebullonly --disablebuynearhigh --disablebuyobv --disablebuyelderray --sellatresistan
Invalid config.json: Binance market invalid: 1INCHUSDT
`
**Expected behavior**
Bot works as usual.

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Version 2.1.0

**Comment by iThom** [comment]
Problem is related to this regex:
https://github.com/whittlem/pycryptobot/blob/61b1b216fd227c0a91571d75379ec0ac6fe6ec76/models/config/binance_parser.py#L8

It should be (currently no time to make a PR):
```python
p = re.compile(r"^[0-9A-Z]{6,12}$")
```
