### ISSUE TITLE
Left over funds may lead to "size is too accurate" error - Coinbase

### ISSUE THREAD

**Issue by Sekuiya** [whittlem/pycryptobot#201]
**Describe the bug**
Currently, the rounding is only done on buying. 

https://github.com/whittlem/pycryptobot/blob/0d07b7827ba0c0726a2ef3e21d911266972a8d26/models/exchange/coinbase_pro/api.py#L285

While this works if you start your portfolio from scratch, if you already had some quote currency on the portfolio, for whatever reason, it may not have the correct rounding so it might fail on sell, since no check is made here.

https://github.com/whittlem/pycryptobot/blob/0d07b7827ba0c0726a2ef3e21d911266972a8d26/models/exchange/coinbase_pro/api.py#L308

**To Reproduce**
1. Add values of the currency below the base increment
2. Have a sell order happen

**Expected behavior**
Sell orders happens normally without error.

**Desktop:**
 - Version 2.1.0

**Additional context**
Just to finish, here's an example of a real situation that happened to me.
Had some leftover XLM from Coinbase's Earn program, leaving my portfolio with 0.61 XLM. Now, XLM only trades in increments of 1 so when the bot buys, it will buy an amount in that increment, but when selling, it will try to sell all that it's available and it will hit a "size is too accurate" error.

**Comment by Nicolas469** [comment]
I've got the same error with the selling of ALGO:
```
{'product_id': 'ALGO-EUR', 'type': 'market', 'side': 'sell', 'size': 90.0268}
error: POST (400) https://api.pro.coinbase.com/orders - size is too accurate. Smallest unit is 1.00000000
```
The solution is maybe to use `marketBaseIncrement()` in `marketSell()` and `limitSell()` ?

**Comment by Sekuiya** [comment]
My temporary solution is to move those decimals to another portfolio, in my case moving the 0.61 XLM to another portfolio.

**Comment by iThom** [comment]
I created the issue #216 which duplicate a part of this issue but with some precision about the buy part.

We need to be careful and to use the base_increment only for sell and quote_increment for buy since it's what is officially checked buy the Coinbase Pro API.

**Comment by iThom** [comment]
The #206 pull request should not be used for this issue as it's only to insure methods respect booleans type in returns.

PR should be as unit as possible to ease the review and not solving several problem at once.
