### ISSUE TITLE
Backtesting in Binance >300 interval size?

### ISSUE THREAD

**Issue by Nokom69** [whittlem/pycryptobot#202]
Hi all,

Is it possible to backtest in binance with more than >300 interval size?
if I run a consecutive session, the MACD is different from the previous test, which results in buying in at different times.

I suppose this should be solvable by integrating a loop in the code? If yes: how i do this?

Any suggestions?

Kind regards!

Grts,
Nokom

**Comment by whittlem** [comment]
Coinbase Pro supports up to 300 records in a response and Binance supports up to 500. I reduced the Binance response to align to Coinbase Pro. It may be possible to allow them to have different response sizes without causing an issue but it would need to be carefully looked at and tested. I'll add it to the roadmap and see what we can do for you.

**Comment by whittlem** [comment]
I'm working on AI modelling now and needed to retrieve more than 300 intervals. I created a function that requests 300 intervals at a time and chains them together. At some stage I'll include this function in the bot code but if you want it early here it is. This functions runs in a class I created but you can just convert this to a normal function. You pass in how many iterations you would like. I put in 100 as a test and it was able to get ~30000 without any kind of blocking from the exchange.

    def getHistoricalData(self, max_interations: int=1) -> DataFrame:
        df1 = self.app.getHistoricalData(self.app.getMarket(), self.app.getGranularity())

        if max_interations == 1:
            return df1

        def getPreviousDateRange(df: DataFrame=None) -> tuple:
            end_date = df['date'].min()
            minutes_diff = (df['date'].max() - df['date'].min()).total_seconds() / 60.0
            new_start = df['date'].min() - timedelta(minutes=minutes_diff)
            return (str(new_start).replace(' ', 'T'), str(end_date).replace(' ', 'T'))

        iterations = 0
        result_df = DataFrame()
        while iterations < max_interations:
            start_date, end_date = getPreviousDateRange(df1)
            df2 = self.app.getHistoricalData(self.app.getMarket(), self.app.getGranularity(), start_date, end_date)
            result_df = concat([result_df, df1, df2]).drop_duplicates()
            df1 = df2
            df2 = DataFrame()
            iterations = iterations + 1

        if 'date'in result_df:
            result_df.sort_values(by=['date'], ascending=True, inplace=True)
        
        return result_df

**Comment by Nokom69** [comment]
Dear Whittlem,

Thanks for the update about my concern. I noticed that you implemented it already inside the code, which is awesome!

However when i run the command for simulation:
"--sim fast-sample --simstartdate 2020-01-01 --simenddate 2021-01-01"
It only runs during the last 12.5 days, can you maybe verify which command triggers the new implementation?

Kind regard,
Nokom69

**Comment by Deleriumdelicious** [comment]
Hello Michael,

I'm also noticing that the simstartdate function doesn't function anymore, is it perhaps linked with the last update in which you indeed included new code for additional historical data pulling? 

Regards,
Deliriumdelicious

**Comment by whittlem** [comment]
This is fixed and if you want to use datasets larger than 300 you can use getHistoricalDataChained() in a script.
