### ISSUE TITLE
Separating Gains From Principal

### ISSUE THREAD

**Issue by p9qgtjaliucdtygqapv79h5nm1faov8** [whittlem/pycryptobot#207]
**Is your feature request related to a problem? Please describe.**
It would be nice if the bot could automatically "bank" the gains into a different profile after a successful sell.

**Describe the solution you'd like**
Move the gains into a different profile.

**Describe alternatives you've considered**
Set a maximum amount of base currency for trading in the config file.
OR
Move the gains to a different currency EX. USDT.

**Additional context**
The first alternative might be the easiest to complete and provide a more unified experience for both supported exchanges.

**Comment by whittlem** [comment]
This is technically possible but adds some risk. It would mean users will need to enable transfer permissions on their API keys.  I personally would not want to enable that permission on my API keys as it does give you some protection. I can see why this would be useful but there is require significant risk associated. I'll add it to the roadmap and see if others are interested in it as well.

**Comment by whittlem** [comment]
Thanks for the feature request but I've given it some thought and I don't think it is safe to implement. Enabling API keys to allow for transfers could potentially allow for accounts to be drained if the API keys fell into the wrong hands. At least now if someone managed to steal API keys all they can do is trade with them. It's just too high of a risk for users and I wouldn't want any mistakes to happen and for people to lose all their funds.
