### ISSUE TITLE
python-binance API - Key Error Problem

### ISSUE THREAD

**Issue by emreeroglu** [whittlem/pycryptobot#209]
**Describe the bug**
Getting a key error from python-binance API from getTakerFee() API call.
Never got the error on live mode though still testing, will update if got anything.
Continuously getting error on simulation mode. 

**To Reproduce**
My config is:

"config" : {
            "base_currency" : "ADA",
            "quote_currency" : "EUR",
            "live" : 0,
            "sellatloss" : 0,
            "sellatresistance" : 1,
            "disablebullonly" : 1,
            "disablebuynearhigh" : 1,
            "disablebuyobv" : 1,
            "disablebuyelderray" : 1,
            "disablelog" : 0,
            "disabletracker" : 1
        }      

**Expected behavior**
App crashs.

**Screenshots**
![image](https://user-images.githubusercontent.com/3215691/118883016-768b2800-b8fd-11eb-9cc2-7b8eb370a19f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 - WSL2 ("Debian GNU/Linux 10 (buster)")
 - Python 3.9.2
 - Working in virtual environment with installed requirements.txt

**Additional context**
-

**Comment by whittlem** [comment]
What version of python-binance are you running?

% python3 -m pip freeze | grep binance
python-binance==0.7.9

% cat requirements.txt | grep binance
binance==0.3
python-binance==0.7.9

There are breaking changes in the newer version of Binance which I need to look at.

If you are running a newer version please downgrade and let me know if it helps.

**Comment by emreeroglu** [comment]
> What version of python-binance are you running?
> 
> % python3 -m pip freeze | grep binance
> python-binance==0.7.9
> 
> % cat requirements.txt | grep binance
> binance==0.3
> python-binance==0.7.9
> 
> There are breaking changes in the newer version of Binance which I need to look at.
> 
> If you are running a newer version please downgrade and let me know if it helps.

I am using exact versions installed in virtual environment via pip install -r requirements.txt

I think there are two possibilities about this: 
1) https://stackoverflow.com/questions/63519424/how-to-get-binance-python-testnet-updating-balance
2) https://dev.binance.vision/t/get-fees-return-me-error-keyerror-success-in-python/1796

I think its a problem about Binance test API (First one, I am getting same error on USDTTRY too)
I am not sure if this problem significant enough to spend time on.

**Comment by whittlem** [comment]
Can you see if upgrading the Binance libraries helps?

python3 -m pip install python-binance binance -U

**Comment by emreeroglu** [comment]
there is something wrong:
2021-05-30 22:46:15 ERROR    error: 'taker_fee_rate' not in fees (using 0.001 as a fallback)
2021-05-30 22:46:16 ERROR    error: 'taker_fee_rate' not in fees (using 0.001 as a fallback)

**Comment by YannickDieter** [comment]
Any news on that?

**Comment by whittlem** [comment]
@emreeroglu and @YannickDieter, do you still have this issue as I think it may have been fixed already.

If you are still having the issues please can you do this:
python3 -m pip install python-binance binance -U

**Comment by whittlem** [comment]
@YannickDieter and @emreeroglu, can you confirm this is a simulation only issue for Binance? I think I have maybe fixed this already. Are you still getting it in the latest version. If so can you provide the config and arguments you ran to run your simulation.

**Comment by whittlem** [comment]
@emreeroglu and @YannickDieter, I think this may have been fixed already.

I used the config.json in this issue and ran this:
python3 pycryptobot.py --exchange binance --sim fast --disable-telegram

Completed without issue. Can you confirm this is this resolved and can be closed?

**Comment by loomsen** [comment]
No reports back for almost 2 months, I think it is safe to assume this is fixed.
