### ISSUE TITLE
Just a quick question: What happens after a restart?

### ISSUE THREAD

**Issue by yanone** [whittlem/pycryptobot#212]
First of all, thanks for putting this out there. I'm currently reading into it and have a question:

What happens when the app accidentally goes offline and comes back online with regards to trading opportunities missed in the meantime, both buying and selling?

Thank you!

**Comment by iThom** [comment]
Hello,
After a start or a restart, the bot will read the last 300 market periods and decide what to do.

**Comment by yanone** [comment]
Excellent, thank you. Closing this.
