### ISSUE TITLE
Logger Improvement

### ISSUE THREAD

**Issue by emreeroglu** [whittlem/pycryptobot#214]
**Is your feature request related to a problem? Please describe.**
Currently we have two logging system implemented, one is python logger second is stdout,
We also have debug flags in the code which activates one of these or both of them. 
These debug flags are hardcoded and needs to switch when testing the code and pushing the code to github.

Another problem with logging-printing to stdout is tailing the log if you do not want to keeping the terminal open all the time
Need to redirect stdout to a file and tail that file when need. 

stdout has a buffer and need to wait getting buffer filled before flushing all the log, which is not useful if app crashes.
To overcome this buffering can be disabled when running the app but its not a good practice.

**Describe the solution you'd like**
Solution would be normalizing the python logging system through the bot and adding log level to config.json,
This way it would not interrupt the development and test process.
Would be one source of log data. (If needed I think Python allows more than one target file with different configurations.)
Easily switchable between log levels.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by whittlem** [comment]
Thanks, is this one you can help with?

**Comment by emreeroglu** [comment]
Yes I can.

**Comment by emreeroglu** [comment]
This feature is merged as today.
