### ISSUE TITLE
CandleStick close time logs gets printed in UTC

### ISSUE THREAD

**Issue by aravindashokkumar** [whittlem/pycryptobot#215]
The logs become slightly misleading on the timing that gets printed as part of the graph process.

>2021-05-21 17:18:05 | LTCBUSD | 15m | Current Price: 204.87
2021-05-21 17:20:06 | LTCBUSD | 15m | Current Price: 204.93
2021-05-21 17:22:08 | LTCBUSD | 15m | Current Price: 204.42
2021-05-21 17:24:10 | LTCBUSD | 15m | Current Price: 204.85
2021-05-21 17:26:12 | LTCBUSD | 15m | Current Price: 206.0
2021-05-21 17:28:14 | LTCBUSD | 15m | Current Price: 206.66
2021-05-21 09:30:00 | LTCBUSD | 15m | Close: 206.33 | v EMA12/26: 203.91 < 204.96 v | ^ MACD: -1.05 > -1.81 ^ | WAIT | Last Action: SELL

The above issue is being faced when running in 'live' version for binance exchange.

1. Setup your bot to run on any granularity
2. Wait for the corresponding closing for the granularity selected by you.
3. You should see final candle stick information containing the technical analysis details is printed in UTC but all the other price information logs are printed in the corresponding timezone.

**Expected behavior**
All the logs print should always be on the user's timezone.

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Version v10.15.7 (19H1030)

**Comment by whittlem** [comment]
Is this on a simulation or live? I fixed this on live a few weeks ago. I know I still need to fix this with simulations. If it can confirm it is with simulations only I will close this as it's already on my backlog.

**Comment by aravindashokkumar** [comment]
This is hitting on live. I did get latest and ran again but it still runs as UTC.

Not sure if its cos there is no strf time on the getTime function.

![image](https://user-images.githubusercontent.com/15028373/119599299-4836ac80-be17-11eb-93cf-a2dbbbf99e0c.png)

The gettime api for coinbase only retrieves the server time. Do advise if you need assistance on fixing this.

**Comment by letsautom8** [comment]
sorry i didnt read clearly. the candle info is displayed in utc.
