### ISSUE TITLE
Wrong Margin calculation, coinbase pro

### ISSUE THREAD

**Issue by ThomasLENNE** [whittlem/pycryptobot#230]
**Describe the bug**
bot seems have weird margin calculation, coinbase pro portfolio.

**Screenshots**
![ltc-eur](https://user-images.githubusercontent.com/62294868/119393231-f8e66400-bcd0-11eb-9f90-593e0c8cec59.png)

i checked on coinbase site :
![coinbase-ltc-eur](https://user-images.githubusercontent.com/62294868/119393543-64303600-bcd1-11eb-9e4f-c7c83b87ec49.png)

**Desktop (please complete the following information):**
 - OS: ubuntu on ec2 instance, western europe region

log file :
[pycryptobot.log](https://github.com/whittlem/pycryptobot/files/6534491/pycryptobot.log)

**Comment by iThom** [comment]
Hello,

Same here with last version of the bot and it makes a loss...

![Capture d’écran de 2021-05-25 10-24-29](https://user-images.githubusercontent.com/219804/119464917-81055180-bd43-11eb-9d91-2359a853e199.png)

Logs:

![Capture d’écran de 2021-05-25 10-22-17](https://user-images.githubusercontent.com/219804/119464682-46031e00-bd43-11eb-85d7-9376a7ce1acd.png)

**Comment by whittlem** [comment]
@marioK93 and @emreeroglu, I thought the margin issue was resolved now -- at least for Coinbase Pro. I'm looking into what is going on here.

**Comment by whittlem** [comment]
I've updated troubleshoot_margin.py to use the new function you guys created.

I plugged in the values from the latest buy and sell from the screenshot above.

  import sys
  
  sys.path.append('.')
  from models.helper.MarginHelper import calculate_margin
  
  buy_filled = 1.13463691
  buy_price = 138.52
  buy_size = 160.37000000
  buy_fee = 0.55
  
  sell_percent = 100
  
  sell_filled = 1.13460000
  sell_price = 138.97
  sell_size = 1.13460000
  sell_taker_fee = 0.55
  sell_fee = 0.0
  
  actual_margin, actual_profit, actual_sell_fee = calculate_margin(buy_size, buy_filled, buy_price, buy_fee, sell_percent, sell_price, sell_fee, sell_taker_fee, True)

This is what I am getting...

  buy_size: 160.37
  buy_filled: 1.13463691
  buy_price: 138.52
  buy_fee: 0.55 
  
  sell_size: 157.68049138
  sell_price: 138.97
  sell_fee: 86.72427026 
  
  buy_with_fees: 160.37
  sell_with_fees: 157.68049138
  sell_minus_fees: 70.95622112
  profit: -89.41377888 
  
  margin: -55.7546791 

I haven't had a chance to check all the figures yet but can you confirm I put the correct inputs into the function?

**Comment by whittlem** [comment]
@iThom, I did notice something weird with your screenshot. Normally the Filled for a buy is more than the sell (after fees). You included two buy and sell pairs but the first one you sell more than you bought. You must have add some additional LTC left over which was sold. This would skew the margin for the first buy/sell pair as you are comparing like for like.

**Comment by iThom** [comment]
> @iThom, I did notice something weird with your screenshot. Normally the Filled for a buy is more than the sell (after fees). You included two buy and sell pairs but the first one you sell more than you bought. You must have add some additional LTC left over which was sold. This would skew the margin for the first buy/sell pair as you are comparing like for like.

@whittlem You probably mean @ThomasLENNE cos mine was about XLM not LTC :)

**Comment by whittlem** [comment]
Well this definitely does not look right...

python3 troubleshoot_margin.py

buy_size: 160.37
buy_filled: 1.13463691
buy_price: 138.52
buy_fee: 0.55 

sell_size: 157.68049138
sell_price: 138.97
sell_fee: 86.72427026 

buy_with_fees: 160.37
sell_with_fees: 157.68049138
sell_minus_fees: 70.95622112      <---     @marioK93 and @emreeroglu, something looks really wrong here 
profit: -89.41377888      <---     @marioK93 and @emreeroglu, this should be sell_with_fees - buy_with_fees right?  

margin: -55.7546791      <---     @marioK93 and @emreeroglu, :S

**Comment by whittlem** [comment]
This may be fixed now. Can you confirm?

**Comment by whittlem** [comment]
@ThomasLENNE and @iThom, I think this should be better now. Can you pull and confirm?

**Comment by ThomasLENNE** [comment]
Sorry, not in front of my computer these days...I'll try as soon as possible

**Comment by iThom** [comment]
> @ThomasLENNE and @iThom, I think this should be better now. Can you pull and confirm?

@whittlem Thanks, I updated the code and just got a buy for XLM-EUR so I wait and will tell you :)

**Comment by iThom** [comment]
Seems Ok even if the sell was with the selllowerpcnt option.

**Comment by ThomasLENNE** [comment]
Seems ok. Got 3 trades with correct margin calculations.
