### ISSUE TITLE
binance granularity

### ISSUE THREAD

**Issue by iceryan354** [whittlem/pycryptobot#24]
granularity option default for binance config is "1h"
will any other variables work such as 30m, 2h or 900?

With default "1h" it is displayed in app run as "Granularity : 1h seconds" which is a little confusing, but assuming its on the hour.

**Comment by whittlem** [comment]
The bot supports 1m, 5m, 15m, 1h, 6h, and 1d for Binance. For Coinbase Pro they are the same but the numeric equivalents in seconds.

I will fix that cosmetic error. I had not updated that when I enabled Binance. Thanks for letting me know.

**Comment by whittlem** [comment]
Fixed
