### ISSUE TITLE
Ignored buymaxsize 

### ISSUE THREAD

**Issue by TICLAB** [whittlem/pycryptobot#250]
Hi All,

  when the Bot was started it did not respect the **buymaxsize** present within the configurations and bought for the entire amount of the **quote_currency**.

` "config" : {
            "base_currency" : "ADA",
            "quote_currency" : "USDT",
            "buymaxsize": 500,
            ....
   }`

Regards.

**Comment by delphsmith** [comment]
Hi,
I had the same issue this morning
My buymaxsize is in my json file

**Comment by whittlem** [comment]
It works for me. "buymaxsize" was only accepting an int before but I've updated it to support both a float and int input. I've tried with arguments and in the config.json and I can see app.getBuyMaxSize() returns the correct value.

The only code which uses this is:

                    # execute a live market buy
                    state.last_buy_size = float(account.getBalance(app.getQuoteCurrency()))
                    if app.getBuyMaxSize() and state.last_buy_size > app.getBuyMaxSize():
                        state.last_buy_size = app.getBuyMaxSize()

I don't see anything obviously wrong. Can you confirm you are running the latest code with "git pull" and see if this is resolved now?

**Comment by delphsmith** [comment]
I had the version from yesterday but i don't think there was change on this part after that. 

Michael I know you are only using coinbasepro ? I actually had the pb on binance. 
Don't know if it's specific

git pull this morning, We'll see on my next buy, i'll get back to you

**Comment by TICLAB** [comment]
Yes I pull this morning, the first buy used all USDT in my wallet after that it got back to working properly.

**Comment by TICLAB** [comment]
Confirmed, I just made a new pull and recreated the containers ... during the first purchase did not respect the buymaxsize and it has bought for the full amount of USDT.

**Comment by biskuizera19** [comment]
Here he also bought the full amount. Not respecting buymaxsize. I use Binance here

**Comment by biskuizera19** [comment]
sorry I haven't tested it today with the latest pull

**Comment by TICLAB** [comment]
Yes, I use Binance. The problem lies in the first purchase, subsequently the buymaxsize is respected correctly and only the first purchase that uses the entire sum of quote_currency

**Comment by 8080git** [comment]
Hi have the same problem (Binance and latest version). I add, that even with the "buypercent" option does not make BUY, while I tried version 2.13.1, so much older and purchases and sales are done correctly.

**Comment by delphsmith** [comment]
still not working :'(

**Comment by whittlem** [comment]
@ronaldderksen, there seems to be an issue with "buymaxsize". You kindly implemented this for us but there is an issue related to it. Can you please take a look?

@djhemp and @dthevenin, you commented on the PR as well. Do you use this feature and is it working for you?

**Comment by ronaldderksen** [comment]
I will take a look this evening

**Comment by ronaldderksen** [comment]
> Yes, I use Binance. The problem lies in the first purchase, subsequently the buymaxsize is respected correctly and only the first purchase that uses the entire sum of quote_currency

I had exactly the same issue with the 'buypercent'. These are probably rellated.

**Comment by delphsmith** [comment]
one of my bot bought ALL my busd and now i'm stuck X'D. Please help asap with this issue :p Thanks guys !!!

**Comment by ronaldderksen** [comment]
> one of my bot bought ALL my busd and now i'm stuck X'D. Please help asap with this issue :p Thanks guys !!!

Can you post your config.json?, without keys and command line arguments?

**Comment by delphsmith** [comment]
yep sure

root@jeedom:/home/jeedom/delph/Config# more binance.json
{
    "binance" : {
        "api_url" : "https://api.binance.com",
        "api_key" : "",
        "api_secret" : "",
        "config" : {
            "verbose" : 0,
            "graphs" : 0,
            "sellatloss" : 0,
            "granularity" : "1h",
            "disablebuyobv" : 0,
            "disablebuyelderray" : 1,
            "disableprofitbankreversal" : 0,
            "autorestart" : 1,
            "sellatresistance" : 1,
            "disablebullonly" : 1,
            "live" : 1,
            "buymaxsize" : "100"
        }
    },
    "telegram" : {
        "token" : "",
        "client_id" : ""
    }
}

i see now... Maybe it should be an INT ???

**Comment by ronaldderksen** [comment]
Yes, it should be int or float. If not it is silently ignored. I just reproduced that.

This evening I will check the config parser. For now just update your config.json

**Comment by delphsmith** [comment]
Thanks Ronald, i did that. I'll let you know
Now just have to wait for my last buy to recover, erffff

**Comment by ronaldderksen** [comment]
It should work. I am running 13 bots, with this option, on binance.

I forced, in code, a buy at startup and noticed the difference.

Ronald

**Comment by TICLAB** [comment]
In my case, however, the value was set correctly to int, see the first comment of the issue.

**Comment by ronaldderksen** [comment]
What do you see at startup? I see
`--------------------------------------------------------------------------------
|                             Python Crypto Bot                                |
--------------------------------------------------------------------------------
|               Release : v2.15.0                                              |
--------------------------------------------------------------------------------
|              Bot Mode : LIVE - live trades using your funds!                 |
|           Bot Started : 2021-05-27 14:49:07.645905                           |
================================================================================
|          Sell At Loss : True  --sellatloss True                              |
|    Sell At Resistance : True  --sellatresistance                             |
|       Trade Bull Only : False  --disablebullonly                             |
|         Buy Near High : False  --disablebuynearhigh                          |
|          Use Buy MACD : True  --disablebuymacd                               |
|           Use Buy OBV : False  --disablebuyobv                               |
|     Use Buy Elder-Ray : False  --disablebuyelderray                          |
|    Sell Fibonacci Low : True  --disablefailsafefibonaccilow                  |
|  Candlestick Reversal : True  --disableprofitbankreversal                    |
|              Telegram : True  --disabletelegram                              |
|                   Log : False  --disablelog                                  |
|               Tracker : False  --disabletracker                              |
|      Auto restart Bot : False  --autorestart                                 |
|          Max Buy Size : 5.0  --maxbuysize <size>                             |
================================================================================
`
Notice the 'Max Buy Size : 5.0' Do you see that line?

**Comment by TICLAB** [comment]
| Log : False --disablelog |
| Tracker : False --disabletracker |
| Auto restart Bot : False --autorestart |
| Max Buy Size : 200 --maxbuysize <size>|

**Comment by ronaldderksen** [comment]
I created a PR, for type, checking for all parameters.

But I cannot reproduce the problem when type is correct. I tried '''{ "base_currency" : "ADA", "quote_currency" : "USDT", "buymaxsize": 5, .... }''' and get correct buy if I force a buy by changing getAction to always return 'BUY'

@TICLAB Do you know what triggered the buy? Do you have console output?

**Comment by TICLAB** [comment]
Given the market trend, I turned off the bot, unfortunately I no longer have the logs. What I can say is that the total purchase happened when I recreated the containers in docker. Sorry for the delay in the response @ronaldderksen.
