### ISSUE TITLE
Self-update of state after manual trade

### ISSUE THREAD

**Issue by yanone** [whittlem/pycryptobot#254]
Hi everyone, I would like to request a feature that’s kind of critical for how I would like to use the bot: That it updates the state on its own after a manual trade.

Currently, I’m using the bot as a safety net, only augmenting my manual trades, not replacing them entirely. Basically, the bot should take over whenever I'm away, asleep, or choose to not pay attention otherwise.

After I manually trade, it would be fantastic if the bot could update itself without interaction, so like every minute or two, whenever you pull and display the price, before trading action is being calculated.

This way, I could log into Coinbase from my phone when I’m away, place a trade if I see fit, and rest assured that the bot would continue to steer correctly after that.

Also, the collected state change should be communicated via Telegram for confirmation when away.

In the same regard, it would be nice if [this line](https://github.com/whittlem/pycryptobot/blob/main/pycryptobot.py#L938) could include the state, as it’s never printed anywhere when I run the bot lately. I would like to explicitly know what state it is in.

Thank you.

**Comment by whittlem** [comment]
If the trades outside the bot are taker (instant) trades this could probably be done. We would just need to periodically check the order history and update the bot accordingly. maker (future) trades could be a potential problem as it puts a hold on the funds and the bot would not be able to access any funds. As a possible solution the bot could go into a sort of paused state if it sees funds are on hold. Sounds like a good feature. I'll add it to the roadmap.
