### ISSUE TITLE
The bot fails to buy and returns an exception when buying via Coinbase API

### ISSUE THREAD

**Issue by SentBackInTime** [whittlem/pycryptobot#258]
The issue in Coinbase has not been fixed.

Describe the bug:
The bot fails to buy and returns an exception when buying via Coinbase API

To Reproduce:
When bots make a purchase via Coinbase API

Expected behavior:
The bot knew conditions were right to buy, the bot checks the balance and can see there is GBP in there. However, the following exception then occurs: TypeError('The funding amount is not numeric.').

Desktop (please complete the following information):
 - Mac OS 11.3.1 (20E241)
 - Visual Studio Code
 - Version: 1.56.2

Log file attached.

[log.txt](https://github.com/whittlem/pycryptobot/files/6544221/log.txt)

__Originally posted by @SentBackInTime in https://github.com/whittlem/pycryptobot/issues/248__

**Comment by whittlem** [comment]
This error you are getting doesn't really make sense. The marketBuy function in Coinbase Pro api.py only accepts a float. I can see from your log.txt that the quote currency amount is 50.47 which is a valid float. It gets past the function argument validation as a float and then fails here:

        # validates quote_quantity is either an integer or float
        if not isinstance(quote_quantity, int) and not isinstance(quote_quantity, float):
            raise TypeError('The funding amount is not numeric.')

Which checks if the quote_quantity is an integer or float.

I see you are running an older version. Please "git pull" to run the latest code.

Have you had this issue before? I'm not aware of anyone else having problems like this.

All I can suggest for now is to add this...

        # validates quote_quantity is either an integer or float
        if not isinstance(quote_quantity, int) and not isinstance(quote_quantity, float):
            print ('Please report this to Michael Whittle: ', type(quote_quantity))
            raise TypeError('The funding amount is not numeric.')

If it happens again it should tell us what the quote_quantity is and the type.

I'll leave this issue open for now but if you see this issue again after updating please post the details here. Thanks

**Comment by devinat1** [comment]
I had the same issue with DOGE-USD on coinbase pro. I have not had the issue except with dogecoin and am on the latest git pull.
