### ISSUE TITLE
Would you consider adding support for CCXT?

### ISSUE THREAD

**Issue by ricosuave73** [whittlem/pycryptobot#26]
The CCXT library unifies many coin exchanges and would allow for a broader audience for pycryptobot.
https://github.com/ccxt/ccxt

**Comment by whittlem** [comment]
I wanted to keep the modules in the bot standard for all exchanges. So there would be quite a lot of development to standardise each one. I personally only use Coinbase Pro and quite a few use Binance. I think for the time being I will just stick with these two. If I need to add others in the future I'll consider this library so thanks for sharing it.
