### ISSUE TITLE
Binance: no buy or sell actions

### ISSUE THREAD

**Issue by 8080git** [whittlem/pycryptobot#261]
**Describe the bug**
With Binance and the latest versions, even after positive signals or Bullish Pattern Up messages, no more purchases are made. No errors appear in the log files and there are no exceptions. Until 3/4 days ago this did not happen. After about 32 hours, no BUY has been made for 4 different coins (MATICEUR, ETCEUR, VETEUR, ADAEUR), in the --sim fast mode, the purchase operations are correctly simulated. Tested on both ubuntu server and Mac OS X. 

**Additional context**
With a commit on May 22nd, this bug does not occur.

**Comment by whittlem** [comment]
Can you please share your config/arguments (without your API keys)?

Can you share a console/log entry where you believe a buy or sell should have happened?

**Comment by 8080git** [comment]
"binance" : {
        "api_url" : "https://api.binance.com",
        "api_key" : "",
        "api_secret" : "",
        "config" : {
            "base_currency" : "ETC",
            "quote_currency" : "EUR",
            "granularity" : "15m",
            "sellatloss": 1,
            "buypercent": 20,
            "selllowerpcnt": -2,
            "disablebullonly" : 1,
            "sellatresistance": 1,
            "disablebullonly" : 1,
            "disablebuyobv": 0,
            "disablebuyelderray" : 0,
            "live" : 1,
            "verbose" : 1
        }
    }

**Comment by rvasilev** [comment]
The same thing. Looks like it was introduced somwhere after v2.14.1 around this addition
https://github.com/whittlem/pycryptobot/blob/d89ff72828d044de89bf2604d9173931de11e4cc/pycryptobot.py#L332-L345

**Comment by 8080git** [comment]
I am also looking in the code, to understand where the bug may be, as it does not crash or exceptions are shown. He just never buys, I am also trying with more combinations and configurations with 5 different bots, but I never have any purchases. Even on different installations (3 bots on PI, 3 on Amazon AWS EC2, and 1 on my Mac OS X). I also have difficulty because it does not write more log files, on this point there is definitely a bug.

**Comment by rvasilev** [comment]
@8080git may be also not a bug and it's all about interplay of market condition and ʼconfig.jsonʼ settings

**Comment by aravindashokkumar** [comment]
@rvasilev  - I guess thats partially true. When i disabled the disablebuyelderray , there was BUY trades done on binance. 

Could I know what are the ideal values for Elder Ray Index (which allows it to make the BUY)? I have been looking at some graphs on Trading View where i can see a bullish power, but the bot does not seem to translate the same.
