### ISSUE TITLE
Arguments not being recognised

### ISSUE THREAD

**Issue by Matthy1981** [whittlem/pycryptobot#262]
**Describe the bug**
Using Windows and powershell, arguments are not being recognised, the bot will only run in demo mode with test funds. - -live 1 using version 2.14.1

**To Reproduce**
Run the bot using any arguments and they will be set  to FALSE, see screenshot below

**Expected behavior**
The bot should run in live mode, also arguments such as disablebullonly should be set to FALSE but stay on TRUE

**Desktop (please complete the following information):**
Windows 10

**Additional context**
Ive re-installed all the bots again from fresh and problem still occurs, ive also added arguments into the config file but they still dont work
![Capture](https://user-images.githubusercontent.com/84898588/119783273-f8162380-bec4-11eb-95d1-f28f3a64c13c.JPG)

**Comment by whittlem** [comment]
I don't use Windows myself so it is difficult to work on this for you. I'm not aware of any other Windows users having problems. Maybe one of the devs using Windows can help you with this.

Can you try pass the arguments as configuration in the config.json as see if it works?

    {  
        "coinbasepro" : {
            "api_url" : "https://api.pro.coinbase.com",
            "api_key" : "",
            "api_secret" : "",
            "api_passphrase" : "",
            "config" : {
                "base_currency" : "BTC",
                "quote_currency" : "GBP",
                "live" : 1,
                "autorestart" : 1
            }
        }
    }

**Comment by Matthy1981** [comment]
Also i forgot to mention, i ran the code for LTC-GBP 

git pull; clear; python3 pycryptobot.py --sellatloss 0 --disablebullonly --live 1

but you can see from the screenshot the market is BTC, the config file also says LTC as base currency

im going to try your config file now also

**Comment by Matthy1981** [comment]
just tried the argument as a config and they are still not working, it did seem to work fine, but when i restarted and updated the bots a couple of days ago is when the issue started

**Comment by lesterbx** [comment]
Hi, same problem here running on Ubuntu. After last update is completely ignoring arguments both from command line or from config.json file.

**Comment by lesterbx** [comment]
Okay, is fixed using new config format.

**Comment by Matthy1981** [comment]
Can you share the config format please?

**Comment by gibbstp** [comment]
I run on Win10 but using WSL2. Maybe a work around would be install and use WSL2 until someone can track down the bug? I'm at work and can't until tonight.

**Comment by Matthy1981** [comment]
Mmm That the one same as I have now

**Comment by Matthy1981** [comment]
Seemed to have solved the issue now, not sure exactly what the problem was but i re-installed the bot and cloned the directories, then used the new style config file
