### ISSUE TITLE
Setup help

### ISSUE THREAD

**Issue by graz68a** [whittlem/pycryptobot#263]
Hello

I'm installing pycrytobot in a Centos 7 server with Python3.9

Sorry me but I do not understand this step

```
Container

Install Docker Desktop
https://docs.docker.com/desktop

From Github image repo

% docker pull ghcr.io/whittlem/pycryptobot/pycryptobot:latest
latest: Pulling from whittlem/pycryptobot/pycryptobot
8f403cb21126: Pull complete
65c0f2178ac8: Pull complete
1091bd628216: Pull complete
cb1eb04426a4: Pull complete
ec065b94ad1c: Pull complete
Digest: sha256:031fd6c7b7b2d08a743127e5850bc3d9c97a46e02ed0878f4445012eaf0619d3
Status: Downloaded newer image for ghcr.io/whittlem/pycryptobot/pycryptobot:latest
ghcr.io/whittlem/pycryptobot/pycryptobot:latest

Local repo

% docker build -t pycryptobot .
```

I have no idea what is a "Container" ; where should I install the Docker Desktop ? In my Windows or in my Centos7 Linux server ?
If linux is it ok if I install docker in this way ?

`% yum install docker`

And where should I run the %docker commands above , in Centos7 command line ?

Thank you

**Comment by gasteazi** [comment]
DOCKER INSTALLATION IN LINUX ENVIRONMENT

        1. Update the operating system:
            $ sudo apt update
        2. Install prerequisite packages that allow apt to use packages over HTTPS:
            $ sudo apt install apt-transport-https ca-certificates curl software-properties-common
        3. Add GPG key for the official Docker repository on your system:
            $ curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add
        4. Add docker repository to APT sources:
            $ sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        5. Update again with the newly added Docker packages:
            $ sudo apt update
        6. Make sure you are about to install from the Docker repository instead of the default ubuntu repository:
            $ apt-cache policy docker-ce

        You should see something like this: 
        Output of apt-cache policy docker-ce
            $ docker-ce:
            $ Installed: (none)
            $ Candidate: 5:19.03.9~3-0~ubuntu-focal
            $ Version table:
                5:19.19.03.9~3-0~ubuntu-focal 500
                500 https://download.docker.com/linux/ubuntu focal/stable amd64 Packages

        7. Finally we install Docker:
            $ sudo apt install docker-ce
        8. To check that the service is installed:
            $ sudo systemctl status docker

            The result will look something like this:
            Output
                ● docker.service - Docker Application Container Engine
                    Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
                    Active: active (running) since Tue 2020-05-19 17:00:41 UTC; 17s ago
                TriggeredBy: ● docker.socket
                    Docs: https://docs.docker.com
                    Main PID: 24321 (dockerd)
                    Tasks: 8
                    Memory: 46.4M
                    CGroup: /system.slice/docker.service
                    └─24321 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock

    /OPERATIONS WITH IMAGES AND CRYPTOBOT CONTAINERS

        Install latest pycryptobot image -> docker pull ghcr.io/whittlem/pycryptobot/pycryptobot:latest

        /docker containers:
            - view installed containers:
                $ sudo docker ps -a
            - view active containers: 
                $ sudo docker ps

        /docker images:
            - View installed images:
                $ sudo docker images
            - Remove images not associated with a container:
                $ sudo docker system prune
            - Remove image
                sudo docker rmi "reference image"(without quotes)
            - Enumerate images
                & docker images -f dangling=true:
            - Remove all unused resources:
                $ sudo docker images purge

**Comment by graz68a** [comment]
Thank you ! I'll try it

**Comment by whittlem** [comment]
Thanks if you need further help please ask in the Telegram group chat. Over 250 people there who can help you.

Here is the invite link:
https://t.me/joinchat/09hYKfelbRY2MDNk
