### ISSUE TITLE
Support to binance.us

### ISSUE THREAD

**Issue by BlackHoleExelion** [whittlem/pycryptobot#275]
Since binance.com is not available in the US, could you please add support to binance.us? For now, using api.binance.us in config file will give an url errror.

**Comment by whittlem** [comment]
I can add the Binance US API into the whitelist and we can try it. I'm hoping that Binance.com and Binance.us will have the same API. That will be a really easy implementation but probably wishful thinking :)

**Comment by whittlem** [comment]
This is done. Just put api.binance.us in the config.json and it should work.
