### ISSUE TITLE
Dashboard Bot Monitoring 

### ISSUE THREAD

**Issue by Bandit253** [whittlem/pycryptobot#279]
I think the inclusion of another docker container running a Dash dashboard, monitoring the running Bots

Things it could include:

- Current positions
- History of trades
- Returns
- summary of current config

This would be a bit better than running the multiple terminals, as depicted in the medium article!

If I manage to get my imagined 'swarm' of bots going, I will hope to develop myself.

**Comment by whittlem** [comment]
@Bandit253, thanks but isn't this like my other project "Coinbase Pro Portfolio Tracker"? I guess it would need to be created for Binance as well but I think this exists in some form already (excluding the Docker part)

**Comment by Bandit253** [comment]
Thanks I was not aware of that project. I'll have a look.
