### ISSUE TITLE
How to define size of the trade?

### ISSUE THREAD

**Issue by shahidkarimi** [whittlem/pycryptobot#28]
Suppose I have 1000 USDT, I want to trade only 30% of this balance. How to define that?

**Comment by whittlem** [comment]
The bot is designed to buy all and sell all. The way I control this is using "portfolios" in Coinbase Pro and "sub-accounts" in Binance. In your example I would just put 300 USDT into a dedicated portfolio/sub-account and let the bot trade that in isolation. I don't have a config option to trade a percentage of the funds available but a few people have asked for this now so I'll look at adding it as a new feature.
