### ISSUE TITLE
Binance auto BNB fee transfer

### ISSUE THREAD

**Issue by emreeroglu** [whittlem/pycryptobot#284]
**Is your feature request related to a problem? Please describe.**
At Binance BNB fees needs to transferred manually, and this would be done automatically.
This also prevent user stopping to bot before making fee transfers.

**Describe the solution you'd like**
After solving issue #283 we can implement a feature with transfers fee's to BNB automatically after every transaction.
This can be enabled or disabled by a config.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by lazydroid** [comment]
could you please help to understand the issue?

as far as I know, if you have enough BNB in your account and enabled using BNB for fees, the fees are automatically deducted from the BNB amount you have in your account. what do you mean by "transferring fees manually" ?
