### ISSUE TITLE
Graphs not working correctly

### ISSUE THREAD

**Issue by t3ch9** [whittlem/pycryptobot#29]
When I run the following command:
python pycryptobot.py --market BTCUSDT --granularity 1h --sim slow --verbose 0 --live 0 --graphs 1

The following is displayed once the simulation ends:

---
Simulation Summary

  Buy Count : 1
  Sell Count : 1

  Margin : 0.03%

  ** non-live simulation, assuming highest fees

---

The graphs folder contain 2 png files. Both are same chart and does not indicate any trade. I have tested on different time frames, markets, and simulation speeds.   For example, if there are 4 orders in the simulation, there will be 4 png files, but all are same chart with no trade displayed.

**Comment by whittlem** [comment]
I added the graphs months ago for troubleshooting but I don't really use them myself. I'll take a look for you and make sure they are working as expected.

**Comment by whittlem** [comment]
I've fixed this. The graphs were reducing the view to make them more readable. I've changed this to show the entire dataframe. 

One other point is that the way you are running the simulations above doesn't look quite right... try this:
python pycryptobot.py --exchange binance --market BTCUSDT --granularity 1h --sim fast --graphs 1

**Comment by t3ch9** [comment]
I updated to the latest code. When I run the following:

python pycryptobot.py --exchange binance --market ENJUSDT --granularity 1h --sim fast --graphs 1

The following is displayed once the simulation ends:

---
Simulation Summary

Buy Count : 3
Sell Count : 3

Margin : -3.98%
---

In the graphs folder, there are 6 png files that look identical. (see attachment)
For reference, can you provide an example of your chart? Is the chart supposed to display any trade information? 

![image](https://user-images.githubusercontent.com/29530317/114062769-e372c300-9865-11eb-928d-d6d4ffaff32a.png)
