### ISSUE TITLE
Request for OBV & ERI values on log console print

### ISSUE THREAD

**Issue by aravindashokkumar** [whittlem/pycryptobot#290]
Currently the log prints EMA, MACD and action information.

It would be better if we could add the decision loop that was taken by the bot, e.g. ERI condition not yet met and so on, to understand why there was no BUY or SELL action.

Here is the current log.

================================================================================
|         Iteration : 53                                                       |
|         Timestamp : 2021-05-31 10:00:00                                      |
--------------------------------------------------------------------------------
|             Close : 2.6000                                                   |
|             EMA12 : 2.5837                                                   |
|             EMA26 : 2.5690                                                   |
|    Crossing Above : False                                                    |
|   Currently Above : True                                                     |
|    Crossing Below : False                                                    |
|   Currently Below : False                                                    |
|         Condition : EMA12 is currently above EMA26 and has crossed over      |
|             SMA20 : 2.5597                                                   |
|            SMA200 : 2.5756                                                   |
--------------------------------------------------------------------------------
|              MACD : 0.0147                                                   |
|            Signal : 0.0067                                                   |
|   Currently Above : True                                                     |
|   Currently Below : False                                                    |
|         Condition : MACD is currently above Signal and has crossed over      |
--------------------------------------------------------------------------------
|            Action : WAIT                                                     |
================================================================================

Expecting a new line saying, which can provide information behind 'WAIT' action criteria. 
example: ERI not yet on BULLISH power. 

The information for MACD and EMA are quite clear, but information about ERI is not getting printed. This will help the various users to toggle the TA that they want to confirm to.

**Comment by whittlem** [comment]
Maybe I can include a sort of trading debug you can turn on which explains why certain conditions are or aren't met.

**Comment by aravindashokkumar** [comment]
Yes that would be great. Cos i have been meddling with a lot of settings but i still am unable to make the ideal buy. 

e.g. I have used the below setting:

| Sell At Resistance : False  --sellatresistance                           | 
|        Trade Bull Only : False  --disablebullonly                            | 
|          Buy Near High : True  --disablebuynearhigh                          | 
|           Use Buy MACD : True  --disablebuymacd                              | 
|            Use Buy OBV : False  --disablebuyobv                              | 
|      Use Buy Elder-Ray : False  --disablebuyelderray          |


The above config means it will check the EMA and MACD only, i have verified both EMA12 is above EMA26 and MA12 is above Signal and its positive. But the BUY still does not happen on the bot.

It would be nice to understand which condition was 'NOT SATISFIED' to basically tune the settings we wish to use.

Regards,
Aravind

**Comment by wireddude** [comment]
nice suggestion!
