### ISSUE TITLE
Medium article for Binance setup

### ISSUE THREAD

**Issue by Daniel-Trung-Nguyen** [whittlem/pycryptobot#292]
I wonder if you could write an article guiding how to set the bot up on Binance like the one you did for Coinbase Pro. Thanks in advance!
Daniel

**Comment by whittlem** [comment]
Sure, will do. I'll close this issue but the next article I write will be this one.

**Comment by whittlem** [comment]
Do you mean like I did in this article?
https://medium.com/coinmonks/python-crypto-bot-pycryptobot-b54f4b3dbb75

**Comment by Daniel-Trung-Nguyen** [comment]
Yes, like that one. Thanks a lot! Starting to explore your bot. It is amazing!

**Comment by Daniel-Trung-Nguyen** [comment]
I tested simulations with ETH, BTC, ADA, DOGE but all returned margins of around -%5 (see photo). I am not sure if my command was correct.
Also, is there an option to limit the amount of money in Binance that can be used for trading?
Thanks,
Daniel
![image](https://user-images.githubusercontent.com/22897462/120806516-4cd33180-c58a-11eb-95b8-1df1f8ead5ec.png)

**Comment by loomsen** [comment]
The documentation is provided in the requested medium article. Closing this issue.

@Daniel-Trung-Nguyen If you have questions about the usage of the software, please feel free to join the [telegram channel](https://t.me/pycryptobotchat)
