### ISSUE TITLE
Pycryptobot rejects currency with name longer than 5 letters

### ISSUE THREAD

**Issue by dbobak** [whittlem/pycryptobot#299]
When trying to configure bot to trade on the Binance on the BAGDER / USDT market, I'm getting the following error:
```
badgerusdt    | Traceback (most recent call last):
badgerusdt    |   File "/app/models/config/binance_parser.py", line 142, in parser
badgerusdt    |     raise TypeError('Base currency is invalid.')
badgerusdt    | TypeError: Base currency is invalid.
badgerusdt exited with code 1
```

The base currency is BADGER. Dante on the Telegram Chat states, that this is because parser is checking for maximum 5 letters. 
Would it be possible to extend the allowable length of the currency name to 6 letters? Or maybe more, I'm not sure if there are longer names,

best
Darek

**Comment by whittlem** [comment]
@dbobak, I am pretty sure this was fixed a while back. Can you upgrade to the latest version and confirm this is still an issue?

**Comment by emreeroglu** [comment]
I am trading TFUELUSDT and not having this problem. New version should solve this.

**Comment by dbobak** [comment]
Yes, it's fixed. I did not noticed, when; but now the problem is gone. Thank you, @whittlem!
