### ISSUE TITLE
Trading at Binance

### ISSUE THREAD

**Issue by cordou4** [whittlem/pycryptobot#300]
Hello

I am having trouble in making the bot trade at Binance. I have created the config file with the following details:

{
    "binance" : {
        "api_url" : "https://api.binance.com",
        "api_key" : "",
        "api_secret" : "",
        "config" : {
            "base_currency" : "ADA",
            "quote_currency" : "EUR",
            "granularity" : "1h",
            "live" : 1,
            "verbose" : 0
        }
    },
    "telegram" : {
        "token" : "",
        "client_id" : ""
    }
}

and the bot seems to run 
![Capture](https://user-images.githubusercontent.com/85314765/120704681-30b29000-c4b7-11eb-9b45-a7b4a67ba8a7.PNG)

However, the bot is not doing any trade. I have let the bot run for a couple of days and no trade took place, while there were opportunities to buy/sell.
Could you please provide any inside on which could be the issue?

I would like to note that in my Binance portfolio, I own some coins but not ADA. Moreover, I have EUR in the account.

Thanks!

**Comment by BishopWolf** [comment]
I am in the same situation, is there some magic to do for the script to actually do the trades? I saw some buy-sell events but they were not executed.
```
* Candlestick Detected: Hammer ("Weak - Reversal - Bullish Signal - Up")
2021-06-13 16:00:00 | BNBEUR (BEAR) | 1h | Close: 276.9100 |  v EMA12/26: 278.5001 < 280.5108 v  | v MACD: -2.0107 < -1.5361 v | ^ OBV: 44208.2479 (0.0600%) ^ | ERI: buy | WAIT | Last Action: SELL
```
It always says WAIT

**Comment by whittlem** [comment]
It's because the bot won't trade in a bear market by default. It will only trade in a bull market. You can disable this check by setting "disablebullonly" to 1 in the config.json in the "config" section.
