### ISSUE TITLE
Pandas issue

### ISSUE THREAD

**Issue by ppx45** [whittlem/pycryptobot#302]
First off, great work! This is amazing,

So I've got it working running the Sim... however when I run the real deal with Coinbase base I get:

`/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/frame.py:4321: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
/Users/username/pycryptobot/models/exchange/coinbase_pro/api.py:227: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['price'] = 0.0
/Users/username/pycryptobot/models/exchange/coinbase_pro/api.py:228: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['filled_size'] = df['filled_size'].astype(float)
/Users/username/pycryptobot/models/exchange/coinbase_pro/api.py:229: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['specified_funds'] = df['specified_funds'].astype(float)
/Users/username/pycryptobot/models/exchange/coinbase_pro/api.py:230: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['executed_value'] = df['executed_value'].astype(float)
/Users/username/pycryptobot/models/exchange/coinbase_pro/api.py:231: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['fill_fees'] = df['fill_fees'].astype(float)
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/indexing.py:1743: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)
`
Please advise.

Many thanks

**Comment by whittlem** [comment]
This is fixed now in the latest release.

**Comment by ppx45** [comment]
Despite being up to date is is still an issue for me

**Comment by waffel183** [comment]
I have gotten the same error after a Live Sale Order with the latest version
