### ISSUE TITLE
Add the Stochastic RSI indicator for buy/sell signals

### ISSUE THREAD

**Issue by delphsmith** [whittlem/pycryptobot#303]
I was simulating with pine editor on tradingview with the "Stoch RSI" indicator, combine with your other buy/sell signals (ema12>ema26 et macd>signal)

I had pretty good results, especially on bought signals, which happened earlier than when ema12 crossing ema26

Hera are some articles on the Stochastic RSI :

https://www.plindia.com/blog/the-stoch-rsi-a-powerful-signal-for-stock-pickers/
https://commodity.com/technical-analysis/stochastic-rsi/

**Describe the solution you'd like**
It would be great to add this new buy/sell criteria, 

I actually use : 
when the stochRSI cross above 15 ==> BUY
when the stochRSI cross below 85 ==> SELL

**Additional context**
I can send you my script on tradingview if it can help, but i don't know how to code it in python so i hope you can implement it :)

Thank you

**Comment by delphsmith** [comment]
Here is an example of my buy sell simulation on trading view , 15 min chart

Buy signal at 10.30pm , market at 395$
Sell signal this morning at 9.30 am, at 423$
Around 7% up

![image](https://user-images.githubusercontent.com/82037153/120887176-af134d00-c5f1-11eb-9663-55509cdf8102.png)


transaction list :

![image](https://user-images.githubusercontent.com/82037153/120887214-d833dd80-c5f1-11eb-992b-35f0a7656ff6.png)


The bot bought at 3.00am , at around 407$ (orange circle). Still no sell (but i think the margin is f*cked up on binance. Issue #283)

**Comment by whittlem** [comment]
I've just implemented this.

  from models.PyCryptoBot import PyCryptoBot
  from models.Trading import TechnicalAnalysis
  
  app = PyCryptoBot()
  df = app.getHistoricalDataChained('BTC-GBP', 3600, 1)
  model = TechnicalAnalysis(df)
  model.addAll()
  df = model.getDataFrame()
  
  print (df[[ 'rsi14', 'stochrsi14', 'williamsr14' ]].tail(10))
  
  Output:
  
                             rsi14  stochrsi14  williamsr14
  ts                                                     
  2021-06-11 12:00:00  58.636627    0.881375     0.164844
  2021-06-11 13:00:00  61.079205    1.000000     0.057566
  2021-06-11 14:00:00  56.894924    0.737800     0.181628
  2021-06-11 15:00:00  49.899680    0.250451     0.420829
  2021-06-11 16:00:00  47.370733    0.000000     0.647915
  2021-06-11 17:00:00  51.736983    0.318507     0.467261
  2021-06-11 18:00:00  55.664786    0.605031     0.261556
  2021-06-11 19:00:00  56.670300    0.678381     0.207090
  2021-06-11 20:00:00  54.583095    0.526124     0.292363
  2021-06-11 21:00:00  50.176846    0.204699     0.623124
