### ISSUE TITLE
Exception: Insufficient Base Funds! (Actual: 0.0, Minimum: 0.0001)

### ISSUE THREAD

**Issue by yassirkachri** [whittlem/pycryptobot#305]
**Describe the bug**
I have made a SELL manually
Exception: Insufficient Base Funds! (Actual: 0.0, Minimum: 0.0001)
after git pull and relaunching the Bot
getting : Exception: Insufficient Base Funds! (Actual: 0.0, Minimum: 0.0001)

**Comment by yassirkachri** [comment]
problem resolved  after executing the BOT with  : python3.9 pycryptobot.py --lastaction SELL

**Comment by dvpetta** [comment]
I'm running into a similar issue:
![image](https://user-images.githubusercontent.com/19885577/122654431-253ea600-d100-11eb-84a0-c3dcb2e13d1b.png)

After I ran the "...--lastaction SELL" I got this error message:
![image](https://user-images.githubusercontent.com/19885577/122654445-40111a80-d100-11eb-8ea9-75ea3d9327b4.png)

I think this is related to other issues but I'm not sure how or what to do to fix this.  
I'm attempting to start a bot for the first time using Coinbase Pro for DOT.
