### ISSUE TITLE
ARIMA price prediction posted to Telegram

### ISSUE THREAD

**Issue by SentBackInTime** [whittlem/pycryptobot#319]
Please can the Seasonal ARIMA machine learning model (which predicts the closing price and prints this message) send the line print to Telegram for each event.

**Comment by CS-Aditya-Rawat** [comment]
Hey, Just go in your pycryptobot.py file and for seasonal ARIMA, There is only a single try block under the If condition pastes the code under logger.info and you are good to go.
```app.notifyTelegram(f'Seasonal ARIMA model predicts the closing price will be {str(round(prediction[1], 2))} at {prediction[0]} (delta: {round(prediction[1] - price, 2)})')```

Like This:
![image](https://user-images.githubusercontent.com/63283520/121812352-22b5f980-cc85-11eb-8258-54e9b5ffabe9.png)

Output is:
![image](https://user-images.githubusercontent.com/63283520/121812407-4d07b700-cc85-11eb-9033-88f209377620.png)

**Comment by SentBackInTime** [comment]
Brilliant, thank you! I've tested and it works @whittlem can we commit this to main? Or at least allow a config option for it if not?

**Comment by SentBackInTime** [comment]
What about this code to only post the update to Telegram on the hour every hour @whittlem? P.S I'm learning Python thanks to this project!

# Seasonal Autoregressive Integrated Moving Average (ARIMA) model (ML prediction for 3 intervals from now)
                if not app.isSimulation():
                    try:
                        prediction = technical_analysis.seasonalARIMAModelPrediction(int(app.getGranularity() / 60) * 3) # 3 intervals from now
                        Logger.info(f'Seasonal ARIMA model predicts the closing price will be {str(round(prediction[1], 2))} at {prediction[0]} (delta: {round(prediction[1] - price, 2)})')
                    except:
                        pass
                # Post ARIMA prediction to Telegram on the hour. 
                if s.enter(60, 1, app.notifyTelegram, (sc,)):
                        app.notifyTelegram(f'Seasonal ARIMA model predicts the closing price will be {str(round(prediction[1], 2))} at {prediction[0]} (delta: {round(prediction[1] - price, 2)})')

**Comment by SentBackInTime** [comment]
I've been working on this fork here: https://github.com/SentBackInTime/pycryptobot

I have now coded a CSV writer to append every ARIMA price prediction to CSV! The plan next is to also post the actual closing prices alongside.

**Comment by whittlem** [comment]
I'm okay with these messages being sent to Telegram but not as a default. There are different logging levels. By default Telegram should only receive buy and sell events. If someone wants to bump up the verbosity of the logs to receive this then the code above would work well.

@emreeroglu, as per the other issue I commented on do you think you can help him add this as a logging option? I think people would like this message every hour but not everyone. I would like it to be an optional log message if people want it.
