### ISSUE TITLE
Consider adding telegram Notification ?

### ISSUE THREAD

**Issue by delphsmith** [whittlem/pycryptobot#32]
Hi,

Woud you consider adding a telegram notification when a buy or sell occurs ?

I'll quickly try and edit your code with these easy steps:

import telegram_send
...
 # if a buy signal
            if action == 'BUY':
                telegram_send.send(messages=["BUY SIGNAL Market xxxxxxxx"])
...
            # if a sell signal
            elif action == 'SELL':
                telegram_send.send(messages=["SEL SIGNAL Market xxxxx"])

Of course it requires setting your own bot before :
https://medium.com/@robertbracco1/how-to-write-a-telegram-bot-to-send-messages-with-python-bcdf45d0a580

Let me know whatyou think,
thanks

**Comment by whittlem** [comment]
Sounds like a great feature. I'll add it as an option. Thanks

**Comment by whittlem** [comment]
If you add your Telegram token and client_id to the config.json you will receive updates.

	{
	    "coinbasepro" : {
	        "api_url" : "https://api.pro.coinbase.com",
	        "api_key" : "",
	        "api_secret" : "",
	        "api_passphrase" : "",
	        "config" : {
	            "base_currency" : "BTC",
	            "quote_currency" : "GBP",
	            "live" : 1,
	            "sellatloss" : 0
	        }
	    },
	    "telegram" : {
	        "token" : "",
	        "client_id" : ""
	    }
	}
