### ISSUE TITLE
A date index has been provided, but it has no

### ISSUE THREAD

**Issue by dw86uk** [whittlem/pycryptobot#320]
When trading with certain pairs on Coinbase Pro I get the attached warning message although the bot continues to function correctly, this happens when trading CRV and SUSHI.
![Screenshot from 2021-06-12 11-52-26](https://user-images.githubusercontent.com/28095779/121773585-be0b7980-cb74-11eb-891b-bb6ca9fa8d38.png)

**Comment by whittlem** [comment]
It's a pity it doesn't say which file or line number that raised that issue. I can maybe look at suppress that warning as it is just a warning.

**Comment by hebawom** [comment]
Hopefully this was resolved in PR #372
@dw86uk any more problems let me know
