### ISSUE TITLE
Error: data frame length is < 300 (243)

### ISSUE THREAD

**Issue by devinat1** [whittlem/pycryptobot#324]
**Describe the bug**
Specifically for DOGE on coinbasepro, I am getting this error when running the bot. It is on Linux and I am running the latest version 2.30.2.

**Comment by rAtKeyboard** [comment]
It is just an indication that there isn't enough historical data. DOGE only started on coinbasepro on 6/3, so this will eventually just disappear.

**Comment by whittlem** [comment]
It's because the market has not existed long enough on the exchange to get enough information to analyse. For example if you are trading hourly graphs (3600) it needs 300 hours of data before it will work. DOGE was only recently added.
