### ISSUE TITLE
Is there any way to limit the funds available to each bot to trade with?

### ISSUE THREAD

**Issue by dv8inpp** [whittlem/pycryptobot#326]
Maybe I have missed this function. It seems the bot will trade with all available funds. Is there anyway to limit it to a base amount?

Yes there is a way for Coinbase, I see that now.

**Comment by delphsmith** [comment]
use : 
--maxbuysize

**Comment by dv8inpp** [comment]
Thanks, always easy to spot when you know what to look for :)

**Comment by dv8inpp** [comment]
OK so I tried the maxbuysize in the config.json but it was ignored. Is this how it should look?


"granularity" : "15m",
"live" : 1,
"maxbuysize" : 40,

**Comment by delphsmith** [comment]
yes i think so

See issue #250 maybe

**Comment by CS-Aditya-Rawat** [comment]
> OK so I tried the maxbuysize in the config.json but it was ignored. Is this how it should look?
> 
> "granularity" : "15m",
> "live" : 1,
> "maxbuysize" : 40,

You are using the wrong command, the command is "buymaxsize". I recently checked it. It is working.

![image](https://user-images.githubusercontent.com/63283520/122014880-3b392780-cddd-11eb-916f-d9b7dec6a93b.png)

**Comment by delphsmith** [comment]
ouppsss .... my bad -_-

**Comment by dv8inpp** [comment]
Haha , my mistake I should have tied up the other resources before trying it. Thanks both of you.
