### ISSUE TITLE
log messages with mixed time (maybe time zone related)

### ISSUE THREAD

**Issue by lozass** [whittlem/pycryptobot#33]
Hi Michael

First, let me congratulate you for the great work and for taking the time to share it. I have installed pycryptobot on my Windows 10 box and it is running, so far no orders were triggered though. I have it using Binance and configured for BTC-BRL pair. 

I noticed that there seems to be a mix of local time in some messages and a different time in others. I am posting a screen capture so you can see. My system is configured for ETC-3 (Brazil). You will see that at the time I took the capture (local time was about 16:44) there are previous messages showing time at 19:30. Maybe some messages derive time from the API of Binance? Or something related to time zones. 

![pycryptobot](https://user-images.githubusercontent.com/8508351/114088891-e5e81380-988b-11eb-95e8-ebc619612652.png)

Let me know if you need more info on the case.

**Comment by whittlem** [comment]
It looks like the data being processed is returning the timestamp from the exchange and the polling of the price is using your local time. I don't think this would actually be causing a problem. It's more of a cosmetic issue. I'll take a look at how I can fix this for you.

**Comment by whittlem** [comment]
I've resolved this issue. The "Current Price" time should now be in the exchange time now instead of your local time.

**Comment by delphsmith** [comment]
I still get that issue,
are we supposed to launch script-get_time.py  everytime we run the bot ?
