### ISSUE TITLE
ValueError: Invalid config.json: [Errno 2] No such file or directory: 'config.json'

### ISSUE THREAD

**Issue by Mobbassir** [whittlem/pycryptobot#330]
When i run pycryptobot i see this error ValueError: Invalid config.json: [Errno 2] No such file or directory: 'config.json' in windows 7

**Comment by delphsmith** [comment]
you missing the file "config.json" in the directory  /pycryptobot. You have to create it and put your coinbase or binance's api keys + others parameters

**Comment by Mobbassir** [comment]
Thx this error is now finished
