### ISSUE TITLE
Coinbase PRO - BTC-EUR - error insufficient funds with small balance

### ISSUE THREAD

**Issue by contix93** [whittlem/pycryptobot#332]
Today my bot tried to place a SELL order of 0.0008 BTC, however it get's an error because i haven't that amount of BTC into my (small) portfolio as you can see from the screenshot below. 

Maybe ther's a rounding issue?
![Cattura1](https://user-images.githubusercontent.com/26085295/122090480-16a67500-ce08-11eb-97ea-9051f285c886.JPG)
![Cattura2](https://user-images.githubusercontent.com/26085295/122090483-173f0b80-ce08-11eb-8ad1-443861ec75a3.JPG)

**Comment by whittlem** [comment]
It does look like a rounding issue. I will look into this.

**Comment by whittlem** [comment]
I've fixed this.
