### ISSUE TITLE
"'NoneType' object has no attribute 'strftime'"

### ISSUE THREAD

**Issue by emreeroglu** [whittlem/pycryptobot#333]
**Describe the bug**

> 2021-06-15 21:43:20 INFO     2021-06-15 21:43:19 | TFUELUSDT | 15m | Current Price: 0.48825 | Margin: -11.92029066 | Profit: -11.89589221
> 2021-06-15 21:45:37 CRITICAL AttributeError("'NoneType' object has no attribute 'strftime'")

**To Reproduce**
Happened whilst normally running, Bot Version 2.30.2

**Expected behavior**
Bot stopped.

**Screenshots**
-

**Desktop (please complete the following information):**
Fedora release 34 (Thirty Four)

**Smartphone (please complete the following information):**
-

**Additional context**

**Comment by whittlem** [comment]
@emreeroglu, are you able to look at this one? I'm not able to re-create this issue and never seen it. The error doesn't seem to give an indication of where in the code this happened.

**Comment by emreeroglu** [comment]
I can check this out.
Also I never seen this before and there were no other log.
And I am running bot at log level DEBUG.

**Comment by delphsmith** [comment]
Hi
got the same thing last night
Bot autorestart itself, no pb

2021-06-16 23:55:53 CRITICAL Restarting application after exception: AttributeError("'NoneType' object has no attribute 'strftime'")

**Comment by lazydroid** [comment]
@arma6655 thank you for the trace, I have made the changes, hopefully it fixed the problem:
https://github.com/whittlem/pycryptobot/pull/389
