### ISSUE TITLE
ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.

### ISSUE THREAD

**Issue by Mobbassir** [whittlem/pycryptobot#334]
When i run the pycryptobot.py in my machine with "granularity" : "60", then it show me value warnings and not predicting values

![error](https://user-images.githubusercontent.com/82751075/122169778-6aae6980-ce9b-11eb-8b39-c7372de9c73d.PNG)

**Comment by Mobbassir** [comment]
I understand that we have to install the latest version of python

**Comment by loomsen** [comment]
The PR to fix this has been merged, closing.
