### ISSUE TITLE
Graphs not working correctly

### ISSUE THREAD

**Issue by t3ch9** [whittlem/pycryptobot#34]
I updated to the latest code. When I run the following:

python pycryptobot.py --exchange binance --market ENJUSDT --granularity 1h --sim fast --graphs 1

The following is displayed once the simulation ends:

---
Simulation Summary

Buy Count : 3
Sell Count : 3

Margin : -3.98%

---

In the graphs folder, there are 6 png files that look identical. (see attachment)
For reference, can you provide an example of your chart? Is the chart supposed to display any trade information? 

![image](https://user-images.githubusercontent.com/29530317/114062919-0e5d1700-9866-11eb-8ec0-e174c4e17af3.png)

_Originally posted by @t3ch9 in https://github.com/whittlem/pycryptobot/issues/29#issuecomment-815965999_

**Comment by whittlem** [comment]
The graphs generated for a buy or sell is sort of a work in progress. I thought it may be useful to have graphs generated to see what was happening at the time of the buy or sell. I've created loads of graphs in the views/TradingGraphs.py file. At the moment the graphs get generated when ever there is a buy or sell so for 3 buys and 3 sells you will create 6 images. Maybe there is more relevant graphs to show or maybe we would want to generate a graph on a buy or sell but not both. If you are interested in graphs being generated let me know what you think would be useful and I'll see what I can do.
