### ISSUE TITLE
Setting granularity in config vs commandline appears to break candlestick detection

### ISSUE THREAD

**Issue by Vashiru** [whittlem/pycryptobot#342]
**Describe the bug**
When I set the granularity through the config file, I no longer see any Candlestick detections in my log / telegram. If I set it via the commandline it does.

**To Reproduce**
1. Setup the following config file:
```
{
    "binance": {
        "api_url": "https://api.binance.com",
        "api_key": "XXXXXXXXXXXXXXXXXXXXXXX",
        "api_secret": "XXXXXXXXXXXXXXXXXXXXXXXXXX",
        "config": {
            "base_currency": "ORN",
            "quote_currency": "USDT",
            "live": 1,
            "autorestart": 1
        }
    },
    "telegram": {
        "token": "XXXXXXXXXXXXXXXXXXXXXXXX",
        "client_id": "XXXXXXXXXXXXXXXXXXXXXX"
    }
}
```
2. Start the bot with `python3 pycryptobot.py --granularity 15m`
The bot will start with the following logfile:
```
|       Auto restart Bot : True  --autorestart                                 |
================================================================================
*** Candlestick Detected: Morning Star ("Strong - Reversal - Bullish Pattern - Up")
2021-06-17 09:45:00 | ORNUSDT (BEAR) | 15m | Close: 8.7590 | v EMA12/26: 8.8029 < 8.8550 v | v MACD: -0.0520 < -0.0436 vv OBV: -211771.2020 (-3.8300%) v | ERI: buy |  | WAIT | Last Action: SELL
```
Note the candlestick detection.

Now repeat with:
1. Use the following config:
```
{
    "binance": {
        "api_url": "https://api.binance.com",
        "api_key": "XXXXXXXXXXXXXXXXXXXXXXX",
        "api_secret": "XXXXXXXXXXXXXXXXXXXXXXXXXX",
        "config": {
            "base_currency": "ORN",
            "quote_currency": "USDT",
            "granularity": "15m",
            "live": 1,
            "autorestart": 1
        }
    },
    "telegram": {
        "token": "XXXXXXXXXXXXXXXXXXXXXXXX",
        "client_id": "XXXXXXXXXXXXXXXXXXXXXX"
    }
}
```
2. Start the bot using `python3 pycryptobot.py`
Observe the first logging:
```
|       Auto restart Bot : True  --autorestart                                 |
================================================================================
2021-06-17 10:00:00 | ORNUSDT (BEAR) | 15m | Close: 8.7390 | v EMA12/26: 8.7920 < 8.8458 v | v MACD: -0.0538 < -0.0458 v^ OBV: -211238.7530 (0.3300%) ^ | ERI: buy |  | WAIT | Last Action: SELL
Seasonal ARIMA model predicts the closing price will be 8.73 at 2021-06-17 10:45:00 (delta: -0.01)
```
Note that it's no longer showing the candlestick detection.

**Expected behavior**
It will detect candlesticks regardless of how I set up my granularity.

I think this /might/ be related to: https://github.com/whittlem/pycryptobot/issues/335 as we both did set granularity in our config.

**Comment by hellresistor** [comment]
i am detected. Setting granularity on config fiel to 15m will work with 1h at same. can you check this too?

**Comment by whittlem** [comment]
@Vashiru, I don't think this is a bug. The candlestick will show if is it detected in the current interval when you start the bot. When you repeated the second step you are onto the next interval so wouldn't see it. There is nothing in the code that would display candlestick info based on granularity. If you are running the bot with the granularity set in the config.json do you never see any candlestick info? I'm sure you must. If not can you send me your pycryptobot.log file when you have the granularity in the config.json.

@hellresistor, I'm not sure what you mean.

**Comment by Vashiru** [comment]
@whittlem When I tested it, I was able to reproduce it multiple times. But I've just set up 2 bots with live 0 to run along with the market. I'll let you know what the outcome of the test is.

**Comment by Vashiru** [comment]
I've left it running for a bit, managed to validate that in both cases they've been detected correctly. Closing ticket.
