### ISSUE TITLE
Coinbase Pro API URL is invalid

### ISSUE THREAD

**Issue by YoShi-2019** [whittlem/pycryptobot#350]
**Describe the bug**
Code throws an error 

**To Reproduce**

in simulation mode
```
pi@piBot:~/pycryptobot$ python3 pycryptobot.py --market ETH-USA --granularity 3600 --sim fast --verbose 0
Traceback (most recent call last):
  File "/home/pi/pycryptobot/models/exchange/coinbase_pro/api.py", line 64, in __init__
    raise ValueError('Coinbase Pro API URL is invalid')
ValueError: Coinbase Pro API URL is invalid

```
in live mode
`pi@piBot:~/pycryptobot$ python3 pycryptobot.py --market ETH-USD --granularity 3600 --verbose 0 --live 1 graphs 1
Traceback (most recent call last):
  File "/home/pi/pycryptobot/models/exchange/coinbase_pro/api.py", line 64, in __init__
    raise ValueError('Coinbase Pro API URL is invalid')
ValueError: Coinbase Pro API URL is invalid
pi@piBot:~/pycryptobot$
`

**Expected behavior**
Code does not progress past the verification of the address. my config.json has the address as per the article and githut description

{
"api_url" : "https://api.pro.coinbase.com",
"api_key" : "removed",
"api_secret" :"removed",
"api_pass" : "removed"
}

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.04 on raspberryPi4
 - python 3.9.5
 - latest pip

**Additional context**
- config.json file is in 'pycryptobot' folder
- API is created and account funded
- all requirements have been installed

**Comment by lilrichy** [comment]
I had this problem too I fixed it by trying the other example of the config file. Try this :

{
	"coinbasepro": {
		"api_url": "https://api.pro.coinbase.com",
		"api_key": "",
		"api_secret": "",
		"api_passphrase": "",
	}
}

**Comment by YoShi-2019** [comment]
Thanks. That worked.
