### ISSUE TITLE
401 request timestamp expired

### ISSUE THREAD

**Issue by devinat1** [whittlem/pycryptobot#357]
**Describe the bug**
I am getting the error: "Auto restarting bot for X after exception: Exception('GET (401)) request timestamp expired" where X is all the currencies I attempted to use the bot on (BTC, ETH, LTC, DOGE). I am running the bot via a terminal on Linux Mint. The issue may be occurring when the bot attempts to buy/sell, although I am unsure as some of the currencies are able to buy/sell, but only sometimes (the issue seems to be a bit random).

**Comment by lazydroid** [comment]
please, make sure your PC clock is set up from NTP and is not drifting for more than a few milliseconds from the actual time.

**Comment by hellresistor** [comment]
What Right timezone config ? GMT +0 or UTC ?

**Comment by lazydroid** [comment]
@hellresistor I believe pycryptobot has no settings for timezone. Besides, GMT+0 is UTC -- what's the difference?

**Comment by hellresistor** [comment]
Edited* sorry

**Comment by lazydroid** [comment]
@hellresistor pycryptobot has no settings for timezone, I'm not sure what is your question about. As far as I know it does not care in what timezone you are, it uses UTC internally, however prints the log messages in your local time.

Anyway, this does not seem like a valid issue, if you need more assistance, please feel free to reopen the issue or ask the question in telegram chats -- you might get more answers there.
