### ISSUE TITLE
Auto-Pull and run bot periodically

### ISSUE THREAD

**Issue by devinat1** [whittlem/pycryptobot#359]
I have been manually stopping the bot via ctrl-c and typing git pull daily just to make sure I have the latest version of the bot. It would be great if this could be automated (perhaps through docker) such that I only have to worry about the bot when I get a telegram message telling me the bots crashed.

**Comment by hellresistor** [comment]
do some script and put it on crontab to run daily :|
read the Run linux  systemd file ;)

**Comment by whittlem** [comment]
I also think this should be handled as an admin script rather than code in the bot. As not everyone will want to force an update. As @hellresistor says, maybe a cron script to do it periodically for you.

**Comment by loomsen** [comment]
I agree, this shouldn't be part of the code base but left to the user as a conscious decision.
Documenting how to set up a cron job is beyond the scope of this project, imo. Closing.
