### ISSUE TITLE
The graphs generated for a buy or sell is sort of a work in progress.

### ISSUE THREAD

**Issue by t3ch9** [whittlem/pycryptobot#37]
Is the chart supposed to display any trade information?
Can @whittlem post an example of a chart for reference?

---

I would like to experiment with different settings and be able to view the trades. 

The graphs generated for a buy or sell is sort of a work in progress. I thought it may be useful to have graphs generated to see what was happening at the time of the buy or sell. I've created loads of graphs in the views/TradingGraphs.py file. At the moment the graphs get generated when ever there is a buy or sell so for 3 buys and 3 sells you will create 6 images. Maybe there is more relevant graphs to show or maybe we would want to generate a graph on a buy or sell but not both. If you are interested in graphs being generated let me know what you think would be useful and I'll see what I can do.

_Originally posted by @whittlem in https://github.com/whittlem/pycryptobot/issues/34#issuecomment-816741096_

**Comment by whittlem** [comment]
The initial idea was for the graph to show the state of the market at the time of a buy or sell signal. Maybe only showing the last few intervals would be more meaningful than the entire dataframe.

I don't use the graphs option now myself. What are you looking to get out of the graphs?
