### ISSUE TITLE
Run bot by command not match with config.file

### ISSUE THREAD

**Issue by hellresistor** [whittlem/pycryptobot#371]
**Describe the bug**
I am executing the bot normally `python3.9 pycryptobot.py` command

My config.json file:
```
{
    "binance": {
        "api_url": "https://api.binance.com",
        "api_key_file" : "binance.key",
        "config": {
            "base_currency": "ADA",
            "quote_currency": "EUR",
            "live": 1,
            "sellatloss": 0,
            "selllowerpcnt": -2,
            "sellatresistance": 1,
            "disablebullonly": 1,
            "disablebuymacd": 0,
            "disablebuynearhigh": 1,
            "disablebuyelderray": 0,
            "graphs": 1,
            "verbose": 1,
            "autorestart": 1
        }
    },
    "logger" : {
        "filelog": 1,
        "logfile": "pycryptobotADAEUR.log",
        "fileloglevel": "DEBUG",
        "consolelog": 1,
        "consoleloglevel": "INFO"
    }
}
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 2.43.0

![pybot](https://user-images.githubusercontent.com/50468493/124388120-4a730d00-dcd9-11eb-98e2-52d36126ade6.png)

**Comment by hellresistor** [comment]
If not declared on config.file. will assume as TRUE.

Its that?

**Comment by hebawom** [comment]
That all looks good to me. selllowerpcnt won't work since you've deactivated sellatloss.

People get confused by the 'disable' term.
So "disablebuynearhigh": 1
Results in:
Buy Near High : False.
Because you are disabling this option.

**Comment by hellresistor** [comment]
@hebawom 👍 got it !! thANK YOU.
