### ISSUE TITLE
How to use getHistoricalDataChained ?

### ISSUE THREAD

**Issue by Terrofmen** [whittlem/pycryptobot#375]
Hey everyone,

I have version 2.45.1.

I see in the code getHistoricalDataChained and want to use it to backtest ideas but I can't figure out how to have the simulation use it and change the number of max_interations. Does someone have an idea of how to communicate to it either through the command line, config file, or something else?  
Thanks in advance

    def getHistoricalDataChained(self, market, granularity: int, max_interations: int=1) -> pd.DataFrame:
        df1 = self.getHistoricalData(market, self.getGranularity())

        if max_interations == 1:
            return df1

        def getPreviousDateRange(df: pd.DataFrame=None) -> tuple:
            end_date = df['date'].min() - timedelta(seconds=(granularity / 60))
            new_start = df['date'].min() - timedelta(hours=300)
            return (str(new_start).replace(' ', 'T'), str(end_date).replace(' ', 'T'))

        iterations = 0
        result_df = pd.DataFrame()
        while iterations < (max_interations - 1):
            start_date, end_date = getPreviousDateRange(df1)
            df2 = self.getHistoricalData(market, granularity, start_date, end_date)
            result_df = pd.concat([df2, df1]).drop_duplicates()
            df1 = result_df
            iterations = iterations + 1

        if 'date'in result_df:
            result_df.sort_values(by=['date'], ascending=True, inplace=True)
        
        return result_df

**Comment by whittlem** [comment]
Here is a small example...

from models.PyCryptoBot import PyCryptoBot
app = PyCryptoBot()
df = app.getHistoricalDataChained('BTC-GBP', 3600, 1)
print (df.shape)

This outputs the "shape" of the dataframe which is 300 rows and 8 columns.
(300, 8)

df = app.getHistoricalDataChained('BTC-GBP', 3600, 10)
print (df.shape)

This outputs the "shape" of the dataframe which is 3000 rows and 8 columns.
(3000, 8)

300 x 10 intervals

It starts with the last 300 hours in this case of BTC-GBP, then prepends the previous 300, then the previous 300 until the iterations are finished. It is really fast.

df will contain the chained dataframe when it finishes.
