### ISSUE TITLE
Exception('GET (401) https://api.pro.coinbase.com/orders?status=done - request timestamp expired')

### ISSUE THREAD

**Issue by SithX** [whittlem/pycryptobot#385]
This error occurs while executing the code about after 20mins

2021-07-12 13:43:05 | BTC-EUR (BEAR) | 3600 | Current Price: 28200.93
Exception('GET (401) https://api.pro.coinbase.com/orders?status=done - request timestamp expired')
Exception: GET (401) https://api.pro.coinbase.com/orders?status=done - request timestamp expired

**Comment by whittlem** [comment]
This will be a system time issue. Make sure you are using NTP.

**Comment by SithX** [comment]
what is NTP?

**Comment by Nephasto** [comment]
In my case (_Raspberry Pi 4, Ubuntu 21.04_) the error was due to the default NTP server not responding. I solved it by changing the configuration (_/etc/systemd/timesyncd.conf_) to this:

> [Time]
> NTP=0.arch.pool.ntp.org 1.arch.pool.ntp.org 2.arch.pool.ntp.org 3.arch.pool.ntp.org
> FallbackNTP=0.pool.ntp.org 1.pool.ntp.org 0.fr.pool.ntp.org

**Comment by SithX** [comment]
the problem persist! :(

**Comment by lazydroid** [comment]
@SithX could you please run this code and report the result?
In your case the absolute time values will be different, but we're interested in `diff` value (the last) one.

```
$ python3
>>> from binance import Client
>>> import time
>>> Client().get_server_time()
{'serverTime': 1626360837488}
>>> time.time()*1000
1626360848862.2197
>>> diff = time.time() * 1000 - float(Client().get_server_time()['serverTime'])
>>> diff
-39.749755859375
```
thanks! =)

**Comment by SithX** [comment]
How do I run this?

**Comment by lazydroid** [comment]
@SithX do you have `python` installed on your PC ? if you type `python` or `python3`, you'll be greeted with `>>>` prompt, and you type the rest of the commands and see the output. `-39.75` is the difference in milliseconds, as long as it's below 100 I would not worry much.

**Comment by SithX** [comment]
Python 3.9.1 (default, Mar 23 2021, 21:04:48)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from binance import Client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'binance'
>>> import time
>>> Client().get_server_time()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Client' is not defined
>>> diff
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'diff' is not defined
>>> time.time()*1000
1626512962632.0774
>>>

**Comment by SithX** [comment]
now¿

**Comment by SithX** [comment]
i cant run this, error persist

**Comment by SithX** [comment]
before went correctly! i dont understand

**Comment by lazydroid** [comment]
`ModuleNotFoundError: No module named 'binance'` -- you need `binance` installed, and if you were able to run the bot before, I believe you have. are you running the bot in docker or a virtual environment?

**Comment by SithX** [comment]
I am using raspberry on raspbianOS and I have used all the steps to install the bot. Using requisiments but I have to use sudo, because without sudo it gives me an error.

**Comment by SithX** [comment]
this error!

copying scipy/_lib/_uarray/__init__.py -> build/lib.linux-armv7l-3.9/scipy/_lib/_uarray
    running build_clib
    customize UnixCCompiler
    customize UnixCCompiler using build_clib
    building 'mach' library
    error: library mach has Fortran sources but no Fortran compiler found
    ----------------------------------------
    ERROR: Failed building wheel for scipy
  Failed to build scipy
  ERROR: Could not build wheels for scipy which use PEP 517 and cannot be installed directly
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/10/26/0fd61f95667e56fd597ecca715dff3623ed1122b6f895ed2b4dfb54afc04/statsmodels-0.12.2.tar.gz#sha256=8ad7a7ae7cdd929095684118e3b05836c0ccb08b6a01fe984159475d174a1b10 (from https://pypi.org/simple/statsmodels/) (requires-python:>=3.6). Command errored out with exit status 1: /usr/local/bin/python3.9 /tmp/pip-standalone-pip-e2nkv18r/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-wl3aos4h/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --extra-index-url https://www.piwheels.org/simple -- setuptools wheel 'cython>=0.29.14' 'numpy==1.15.4; python_version=='"'"'3.6'"'"'' 'numpy==1.15.4; python_version=='"'"'3.7'"'"'' 'numpy==1.17.5; python_version>='"'"'3.8'"'"'' 'scipy>=1.2' Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement statsmodels==0.12.2 (from versions: 0.4.0, 0.4.1, 0.4.3, 0.5.0rc1, 0.5.0, 0.6.0rc1, 0.6.0rc2, 0.6.0, 0.6.1, 0.8.0rc1, 0.8.0, 0.9.0rc1, 0.9.0, 0.10.0rc2, 0.10.0, 0.10.1, 0.10.2, 0.11.0rc1, 0.11.0rc2, 0.11.0, 0.11.1, 0.12.0rc0, 0.12.0, 0.12.1, 0.12.2)
ERROR: No matching distribution found for statsmodels==0.12.2

**Comment by lazydroid** [comment]
sorry, I have no experience running the bot on RPi you might get answers to your question in Telegram support group: https://t.me/pycryptobotchat
