### ISSUE TITLE
error: POST (400) https://api.pro.coinbase.com/orders - funds is too accurate. 

### ISSUE THREAD

**Issue by delphsmith** [whittlem/pycryptobot#39]
Hi,

I keep getting this error message when trading ETH-DAI :

 2021-04-10 16:00:00 | ETH-DAI 900 | Close: 2164.0 | BUY

ETH balance before order: 0.0001
DAI balance before order: 150.4926
error: POST (400) https://api.pro.coinbase.com/orders - funds is too accurate. Smallest unit is 0.01000000
ETH balance after order: 0.0001
DAI balance after order: 150.4926

In fact, i think the issue is that i can't trade 150.4926 but only 150.49.

When i do the trade manually on coinbasepro, that's the amount showing when "MAX" is selected.

I don't know if the problem is present with other currency, i will tryc with usdc

**Comment by stefanoregis** [comment]
same on my side
ETH balance before order: 0.0
USDC balance before order: 337.0835
error: POST (400) https://api.pro.coinbase.com/orders - funds is too accurate. Smallest unit is 0.01000000
ETH balance after order: 0.0
USDC balance after order: 337.0835

**Comment by whittlem** [comment]
It looks like the "quote currency" needs to be rounded to 2 decimal places. I'll update this and push and update this evening.

**Comment by stefanoregis** [comment]
Hello @whittlem thank you for the update, unfortunately i guess still something not working, at the moment in certain cases i receive this message
BTC balance before order: 0.0
USDC balance before order: 675.2751
error: POST (400) https://api.pro.coinbase.com/orders - Insufficient funds
BTC balance after order: 0.0
USDC balance after order: 675.2751

this is because of the round of value before buy

y = 675.2751
x = round(y, 2)
x = 675.28

but 675.28 is bigger than my current amount

Thanks

**Comment by whittlem** [comment]
Ok, I think I need to truncate the float not round it. I'll update it for you today.

**Comment by whittlem** [comment]
Should be working now. Let me know if it fixed your issue.

**Comment by stefanoregis** [comment]
@whittlem thanks, i updated the code from repos, i let you know in case of problems

**Comment by iThom** [comment]
Hi Mike,

I have the same issue even with last version of the bot with truncate (92df5f1 fixed up truncate function).

Here is log extract:

```
2021-04-13 08:00:00 | BTC-EUR (BULL) | 900 | Close: 51395.14 | ^ EMA12/26: 51141.63 > 50994.27 ^ | ^ MACD: 147.36 > 126.75 ^ | ^ OBV: 129.6228 (7.09%) ^ | ERI: buy | SELL | Last Action: BUY | 1.5%

 2021-04-13 08:00:00 | BTC-EUR 900 | Close: 51395.14 | SELL
 Fibonacci Retracement Levels: {'ratio0_286': 50775.35, 'ratio0': 51425.82}

BTC balance before order: 0.001
EUR balance before order: 0.0
{'product_id': 'BTC-EUR', 'type': 'market', 'side': 'sell', 'size': 0.001}
error: POST (400) https://api.pro.coinbase.com/orders - Insufficient funds
BTC balance after order: 0.001
EUR balance after order: 0.0
2021-04-13 10:08:48 | BTC-EUR (BULL) | 900 | Current Price: 51428.4
2021-04-13 10:13:49 | BTC-EUR (BULL) | 900 | Current Price: 51628.42
2021-04-13 08:15:00 | BTC-EUR (BULL) | 900 | Close: 52177.11 | ^ EMA12/26: 51336.13 > 51100.62 ^ | ^ MACD: 235.5 > 152.36 ^ | ^ OBV: 258.2397 (34.65%) ^ | ERI: buy | WAIT | Last Action: SELL
```

My current BTC amount is 0.00099039 so it's less than 0.001

I'm not sure Coinbase Pro API was changed I just think that little by little as BTC price grows, future buy qty will be less and less and make this happened. It's only in Coinbase API cos in the website, we can create a sell for amount less than 0.001. By this if the market is BULL, we have to add some funds to be able to continue to trade with API.

> SIZE
> The size must be greater than the base_min_size for the product and no larger than the base_max_size. The size can be in incremented in units of base_increment. size indicates the amount of BTC (or base currency) to buy or sell.

For BTC-EUR the _base_min_size_ is 0.001
To get this minimum size per product it's needed to make a GET request to the following route:

GET /products/<product-id>

https://docs.pro.coinbase.com/#get-single-product

So nothing to do there, just to add more funds if needed.

Thanks again for your great job :)

**Comment by whittlem** [comment]
Thanks for the update and glad you managed to sort it out.
