### ISSUE TITLE
ValueError: Invalid config.json: Expecting ',' delimiter: line 5 column 9 (char 114)

### ISSUE THREAD

**Issue by SWICloud** [whittlem/pycryptobot#390]
![Unbenannt](https://user-images.githubusercontent.com/80172184/126030709-5f447f16-5727-4dcf-8fcf-1d55905a6010.JPG)
As soon as I want to start the Pycryptobot for the first time I get the following error message : 

I have already created the config.json and binance.key. 

What can be the problem ? 
![Unbenannt2](https://user-images.githubusercontent.com/80172184/126030696-78ac78dc-6848-4c24-9049-f20cb3edbb4a.JPG)
![Unbenannt2](https://user-images.githubusercontent.com/80172184/126030698-5bccc205-8cb4-4381-9467-824e388a981b.JPG)

**Comment by lazydroid** [comment]
`"api_key_file" : "binance.key"` requires a comma -- `,` at the end of the line.
