### ISSUE TITLE
Not Getting profit, just inverse..

### ISSUE THREAD

**Issue by hellresistor** [whittlem/pycryptobot#396]
Hello friend. I am not getting profit.
I am buying and sell on wrong .
My market is ADA/EUR

Actually i Am selling when Low ADA and buy ADA when High.
Should be suppose SELL ADA when High And buy ADA when low?!

```
{
    "binance": {
        "api_url" : "https://api.binance.com",
        "api_key_file" : "binance.key",
        "config": {
            "base_currency": "ADA",
            "quote_currency": "EUR",
            "live": 1,
            "sellatloss": 1,
            "selllowerpcnt": -1,
            "sellatresistance": 1,
            "disablebullonly": 1,
            "disablebuymacd": 0,
            "disablebuyobv": 0,
            "disablebuyema": 1,
            "disablebuynearhigh": 1,
            "disablebuyelderray": 1,
            "disableprofitbankreversal": 0,
            "disablefailsafefibonaccilow": 0,
            "disabletelegram": 0,
            "autorestart": 1,
            "verbose": 1,
            "graphs": 1
        }
}
```

Can give me some help?

Thank you

**Comment by icdmize** [comment]
This is what I run for ADA on Coinbase with USD.  I lose 2% at the most but typically profit.

{
    "coinbasepro": {
        "api_url": "https://api.pro.coinbase.com",
        "config": {
            "base_currency": "ADA",
            "quote_currency": "USD",
            "live": 1,
            "verbose": 1,
            "sellatloss": 1,
	    "selllowerpcnt": -2,
            "disablebullonly": 1,
            "disablebuyobv": 1,
            "disablebuyelderray": 1,
            "autorestart": 1
        },
        "api_key_file": "coinbasepro.key"
    },
    "telegram": {
        "token": "
        "client_id": 
    }
}

**Comment by loomsen** [comment]
@hellresistor Is this fixed? Can we close it?

**Comment by loomsen** [comment]
Actually, we agreed that support questions and questions on how to configure the software are best addressed in the 
[telegram channel](https://t.me/pycryptobotchat)

Closing as this is not an issue with the software.
