### ISSUE TITLE
Docker bots logging exception. 

### ISSUE THREAD

**Issue by D2theR** [whittlem/pycryptobot#398]
**Describe the bug**

I'm getting this log traceback when I run docker-compose to spin up my bots. It looks as though it may be a read-write or filesize issue with pycryptobot.log loggers inside the docker containers. 

ethusdc    |     cls.logger.debug(str)
ethusdc    | Message: '---- EMA1226 1H Check----'
ethusdc    | Arguments: ()
ethusdc    | --- Logging error ---
ethusdc    | Traceback (most recent call last):
ethusdc    |   File "/usr/local/lib/python3.9/logging/handlers.py", line 74, in emit
ethusdc    |     self.doRollover()
ethusdc    | OSError: [Errno 16] Device or resource busy: '/app/pycryptobot.log' -> '/app/pycryptobot.log.2021-07-28'
ethusdc    | Call stack:
ethusdc    |   File "/app/models/helper/LogHelper.py", line 64, in debug
ethusdc    |     cls.logger.debug(str)
ethusdc    | Message: 'bull 1h: True'
ethusdc    | Arguments: ()
ethusdc    | 2021-07-29 08:48:03 | ETH-USDC (BULL) | 900 | Current Price: 2300.45
ethusdc    | --- Logging error ---
ethusdc    | Traceback (most recent call last):
ethusdc    |   File "/usr/local/lib/python3.9/logging/handlers.py", line 74, in emit
ethusdc    |     self.doRollover()
ethusdc    | OSError: [Errno 16] Device or resource busy: '/app/pycryptobot.log' -> '/app/pycryptobot.log.2021-07-28'
ethusdc    | Call stack:
ethusdc    |   File "/app/models/helper/LogHelper.py", line 68, in info
ethusdc    |     cls.logger.info(str)
ethusdc    | Message: '2021-07-29 08:48:03 | ETH-USDC (BULL) | 900 | Current Price: 2300.45'

**To Reproduce**

When I run `docker-compose up -d` and after the bot runs all day or the log file fills up, then it starts throwing this exception. It's actually doesn't seem to effect the trading as long as "autorestart" is enable. 

**Solutions**
If I clear the log file out and reboot the containers it runs like a dream. Add "disablelog" to config.json stops it writing from the file, which seems to work. 

My config.json:

```
{
    "coinbasepro" : {
        "api_url" : "https://api.pro.coinbase.com",
        "api_key_file" : "eth_file.ky",
        "config" : {
            "base_currency" : "ETH",
            "quote_currency" : "USDC",
            "live" : 1,
            "autorestart":1,
            "sellatloss":1,
            "disablebullonly":1,
            "sellupperpcnt":4,
            "selllowerpcnt":-2,
            "disablebuyobv": 1,
            "disablebuyelderray": 1,
            "logger" : {
                "filelog": 0,
                "consolelog": 1,
                "consoleloglevel": "DEBUG"
            }
        }
    }
}

```
I'm really loving this repo btw! I appreciate all the hard work and want to contribute once I have read through the codebase a little more.

**Comment by chiliwax** [comment]
same here,  looking for a workaround 😁

**Comment by stevegregev** [comment]
@D2theR Is this Docker running on Windows or Linux?

**Comment by D2theR** [comment]
I tested it in on: 

Windows 10 -- Docker version 20.10.5, build 55c4c88
&
Ubuntu 20.04 arm64 on Raspberry Pi 4 8GB -- Docker version 20.10.2, build 20.10.2-0ubuntu1~20.04.3
The Pi version I had to fork the repo and rebuild a new Docker image using arm64v8/python:3.9.6-buster in order to get it to work, but it is still showing the same error. 

The only difference between the two with the errors is the Windows version seems to wait for the log file to fill up before it throws and error and the Linux version starts as soon as the containers boot but the weird thing is on the Pi, I can't view the log files, they are just blank, even in the container. If I get a chance I will try and dissect the LogHelper.py file and see what's going on. I'm still a little new to Docker, but I have some Python skills.

**Comment by stevegregev** [comment]
Thanks for the input. I'm also running it on a RPi 4 so I can test it there.
I've been dealing with containers for a while so I'll see if I can understand what's going on inside.

**Comment by stevegregev** [comment]
For this to be handled properly, the bot should print logs to a separate directory and not in the project root. This way we can map an empty logs directory to the container and the logging will work without issue.
This will require a little refactoring, however there is the issue of custom logging configuration, where the user can specify the log file name and location. Maybe the location could be permanent and the log filename should be configurable.
I'd rather have the logs centralized for convenience and because it's cleaner in the project root.
@whittlem What's your take on this? Since the logs directory already exists, were you planning to implement this?

**Comment by loomsen** [comment]
Actually, containers should just log to stdout and stderr and not write logfiles at all, imo. Shouldn't be the responsibility of the App to handle logs.

So, I think we shouldn't do this: 
```
            fileHandler = TimedRotatingFileHandler(filename=logfile, when='midnight',
                                                   backupCount=10)
```

If we look at other popular apps, they might come with a `logrotate.conf` if you install them as a distro package, but none of them implements log file rotating from within the application. This is out of scope and should be left to the user, imo, with the nice add on that this problem will vanish.

**Comment by whittlem** [comment]
@letsautom8 kindly implemented Docker for us. Maybe he can help here as I'm not sure :)

**Comment by whittlem** [comment]
Log rotation should really be out of scope of this project. It should be handled by the OS log rotation. It shouldn't really have been included here.

**Comment by loomsen** [comment]
@D2theR @chiliwax Could you please checkout the beta branch and see if it fixes things for you? The Rotation Handler was set to rotate once per day, so you might have to check two days in a row. Thanks!

**Comment by D2theR** [comment]
> 
> 
> @D2theR @chiliwax Could you please checkout the beta branch and see if it fixes things for you? The Rotation Handler was set to rotate once per day, so you might have to check two days in a row. Thanks!

I got this up and running and will let it run and get back to you in a day or too but it seems like it's working on the Pi so far! Thanks for all your help!

**Comment by D2theR** [comment]
Just and update. This has been running for almost 2 days straight on my Pi-4 without issues. Not sure if anyone else running on RPi can also confirm? I also ran a on-live version on my Windows PC using WSL and Docker for a few hours and it seems to be fine there too!
