### ISSUE TITLE
Backtesting Idea/Question

### ISSUE THREAD

**Issue by Terrofmen** [whittlem/pycryptobot#399]
Hey everyone,

I'm not the strongest Python person yet but I wanted to know if this could be added to the code.

![image](https://user-images.githubusercontent.com/26573843/127684388-635bd8a8-6876-4a07-8bca-8a011a7794f0.png)

In the screenshot, I have --simstartdate 2020-01-01. It goes between 1/1/2020 - 1/13/2020 due to the 300 max internal.

My question is, is there any way to instead have the date period go from 1/1/2020 - Today? Have the system calculate how many 300 intervals are needed and do the entire time period. I have some ideas for back testing and like how this visually is displayed and would like to do the testing this way if possible. I like that it shows where the buy and sell areas are on each line and then if you are positive or negative on that position. I also want to see how the smart switching would act in different time periods during the back testing.

I know Mike has written a Backtesting Trading Strategies article on how to play out different ideas but I'm hoping this idea could be implementing to give everyone options.

**Comment by markhollingworth-worthit** [comment]
this works when using the following on the command line:

python3 pycryptobot.py --sim fast-sample simstartdate 2020-01-01 simenddate now

for long periods such as that it can take a little while for the bot to start analysis as it has to gather lots of data.

Binance may not return any data for anything over 6 months old but coinbase will.

![image](https://user-images.githubusercontent.com/61147577/127883382-f52715b6-f590-4694-a939-98c637ba4630.png)

**Comment by Terrofmen** [comment]
Hey,

Your example is giving me this error.

pycryptobot.py --market BTC-USD --sim fast-sample --autorestart --simstartdate 2020-01-01 --simenddate now

![image](https://user-images.githubusercontent.com/26573843/127917279-ccc919b9-f78f-4a96-99ed-f30996e4442d.png)

I have not made any changes to the source code. Am I doing something wrong here?

If I put the command line code like you did in your example then I get this. It does not do what I want.
![image](https://user-images.githubusercontent.com/26573843/127917636-187bc6f7-c1cb-413f-aee7-36936e76da5a.png)
