### ISSUE TITLE
ValueError: Data not contain date,market,granularity...

### ISSUE THREAD

**Issue by VincentDuf** [whittlem/pycryptobot#409]
**Describe the bug**
After manually installed project, I try to launch a simulation using _$python3 pycryptobot.py --market BTC-GBP  --granularity 3600 --sim fast_.

I get the following error:
`ValueError('Data not not contain date, market, granularity, low, high, open, close, volume')
Traceback (most recent call last):
  File "/Users/user/Desktop/Epargne/Crypto/pycryptobot/models/Trading.py", line 32, in __init__
    raise ValueError('Data not not contain date, market, granularity, low, high, open, close, volume')
ValueError: Data not not contain date, market, granularity, low, high, open, close, volume`

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra
 - Browser: Mozilla Firefox (not sure why it is important...)

To Be Noted: I didn't modify anything special in the core scripts, my config.json follows the pattern

config.json:
`{
    "api_url": "https://api.pro.coinbase.com",
    "api_key_file":"coinbase.key",
    "config": {
        "base_currency": "BTC",
        "quote_currency": "USDT",
        "live": 0,
        "autorestart": 1,
        "sellatresistance": 0,
        "disablebuynearhigh": 1,
        "disablefailsafefibonaccilow": 1,
        "disabletelegram": 1,
        "verbose": 0
    }
}`

**Comment by loomsen** [comment]
Hi @VincentDuf,

try the new config format please, it works for me with this config:

```
{
  "coinbasepro": {
    "api_url": "https://api.pro.coinbase.com",
    "api_key_file": "coinbase.key",
    "config": {
      "base_currency": "BTC",
      "quote_currency": "USDT",
      "live": 0,
      "autorestart": 1,
      "sellatresistance": 0,
      "disablebuynearhigh": 1,
      "disablefailsafefibonaccilow": 1,
      "disabletelegram": 1,
      "verbose": 0
    }
  }
}
```

**Comment by VincentDuf** [comment]
Hey, thanks for answering.
I modified the config.json and realized that my API key wasn't from CoinbasePro but Coinbase... so replacing with the right key it works now ^^

I'm closing the issue, thanks !
