### ISSUE TITLE
Failed to establish a new connection

### ISSUE THREAD

**Issue by adriano26010** [whittlem/pycryptobot#41]
For the last 2 weeks I tested your bot on 6 currency pairs with dummy funds. Amazing gains! :)

Today I have noticed that some bots returned 

> Failed to establish a new connection

and stopped working. It has happen to 2 bots out of 6. So it was probably temporary network issue on my PC, or Binance API. 

However maybe it's worth considering adding retry on this error? 
And if it fails then send error information via Telegram?

Full error message below

![image](https://user-images.githubusercontent.com/37125018/114323363-1bf3f480-9b25-11eb-9a96-656eca8f116a.png)

**Comment by whittlem** [comment]
A few people have asked for this. I'll add it when I have some time.

**Comment by whittlem** [comment]
I've added this feature. The bot will not start if there is no connection to start with. If the connection drops it will keep retrying every 1 minute until the connection comes back.
