### ISSUE TITLE
TypeError: Coinbase Pro market required.

### ISSUE THREAD

**Issue by StevenB23** [whittlem/pycryptobot#416]
I'm running this and getting an error after initial install

`python3 pycryptobot.py --market BTC-USD`

```
TypeError('Coinbase Pro market required.')                                                                            
Traceback (most recent call last):                                                                                    
  File "/home/unixstricken/git/BTC-GBP_Cryptobot/models/exchange/coinbase_pro/api.py", line 650, in getHistoricalData 
    raise TypeError("Coinbase Pro market required.")                                                                  
TypeError: Coinbase Pro market required.

```

It happens even if I specify the --market parameter. I notice even when doing BTC-USD as my market the market var prints out as "BTCGBP" everytime within the getHistoricalData function.

I was able to fix it by finding changing the hard coded market var within "models/Config.py" to BTC-USD but it doesn't seem like a permanent fix although the code runs.

Any ideas?

**Comment by nyllewin** [comment]
can confirm. same issue, same solution

**Comment by loomsen** [comment]
working on a fix

**Comment by loomsen** [comment]
This should be fixed, could you please confirm? @StevenB23

**Comment by StevenB23** [comment]
> This should be fixed, could you please confirm? @StevenB23

Yep it's no longer throwing an error and working now in the new version 3.2
Thanks!
