### ISSUE TITLE
ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by sansal54** [whittlem/pycryptobot#419]
This issue appeared when I migrated to pycryptobot 3.1.1. Even if I have pyyaml latest version installed on linux system, I get following error:

```
Traceback (most recent call last):
  File "./pycryptobot.py", line 12, in <module>
    from models.AppState import AppState
  File "/home/pi/pycryptobot4/models/AppState.py", line 5, in <module>
    from models.PyCryptoBot import PyCryptoBot
  File "/home/pi/pycryptobot4/models/PyCryptoBot.py", line 15, in <module>
    from models.Config import Config
  File "/home/pi/pycryptobot4/models/Config.py", line 7, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

**Comment by jegb** [comment]
how did you fix it?

**Comment by lilrichy** [comment]
I get the same error now after updating 3 bots that were running fine for a few weeks. I spent about 3 hrs trying to track down a fix for this and the only thing I can find is this post with no fix but just a closed issue... Any help would be appreciated.

**Comment by loomsen** [comment]
Hi guys, please read the documentation. It may happen over time, that new requirements are introduced. So if you're not using the docker image, this is part of updating your bots:

`pip install -r requirements.txt`

**Comment by jegb** [comment]
this is because statsmodels works up to python 3.8, commented on it in telegram. I am now trying to use the 64bit rpi image to install the system again with 3.9.6 and attempting the docker image built from scratch locally.

**Comment by aweltig** [comment]
I still have this issue, any fix yet?

**Comment by mimusica** [comment]
pip install pyyaml

Cheers

Op wo 15 sep. 2021 01:30 schreef aweltig ***@***.***>:
