### ISSUE TITLE
binance problem on last action decision

### ISSUE THREAD

**Issue by stefanoregis** [whittlem/pycryptobot#43]
guess i enountered a small issue in the last running, last action was BUY as i had 0.0765 ETH, but on my wallet there was still 0.0973 USDT, in this case 0.09 USDT > 0.07 ETH and the script was going always in last action = SELL

python3 /root/cryptobinance/pycryptobot/pycryptobot.py --exchange binance --market ETHUSDT --live 1 --sellupperpcnt 2 --selllowerpcnt -2 --granularity 15m

base = ETH
quote = USDT
base = 0.0765
quote = 0.0973

--------------------------------------------------------------------------------

|                             Python Crypto Bot                                |

--------------------------------------------------------------------------------

|          Bot Mode : LIVE - live trades using your funds!                     |
|       Bot Started : 2021-04-13 04:01:27.560784                               |

================================================================================

|        Sell Upper : 2.0%                                                     |
|        Sell Lower : -2.0%                                                    |

================================================================================

2021-04-13 02:00:00 | ETHUSDT (BEAR) | 15m | Close: 2167.17 | ^ EMA12/26: 2156.91 > 2151.02 ^ | ^ MACD: 5.89 > 4.38 ^ | ^ OBV: 79451.1662 (0.53%) ^ | ERI: sell | WAIT | Last Action: SELL

after this i added a small constriction to go over 

```
if account.getBalance(app.getBaseCurrency()) < account.getBalance(app.getQuoteCurrency()) and account.getBalance(app.getQuoteCurrency()) > 50 :
        last_action = 'SELL'
elif account.getBalance(app.getBaseCurrency()) > account.getBalance(app.getQuoteCurrency()) and account.getBalance(app.getQuoteCurrency()) < 1 :
        last_action = 'BUY'
print(last_action)


```
just checked if my quote currency had more then 50 USDT in order to decide BUY/SELL

at the second run, infact, the script went over but it immediately sold the order, unfortunately i couldn't debug more on this

python3 /root/cryptobinance/pycryptobot/pycryptobot.py --exchange binance --market ETHUSDT --live 1 --sellupperpcnt 2 --selllowerpcnt -2 --granularity 15m

--------------------------------------------------------------------------------
|                             Python Crypto Bot                                |

--------------------------------------------------------------------------------

|          Bot Mode : LIVE - live trades using your funds!                     |
|       Bot Started : 2021-04-13 04:02:22.184992                               |

================================================================================

|        Sell Upper : 2.0%                                                     |
|        Sell Lower : -2.0%                                                    |

================================================================================

! Profit Bank Triggered (> 2.0%)

* Candlestick Detected: Inverted Hammer ("Weak - Continuation - Bullish Pattern - Up")

2021-04-13 02:00:00 | ETHUSDT (BEAR) | 15m | Close: 2166.82 | ^ EMA12/26: 2156.82 > 2150.97 ^ | ^ MACD: 5.85 > 4.37 ^ | ^ OBV: 79702.5118 (0.85%) ^ | ERI: sell | SELL | Last Action: BUY | 99.41%

 2021-04-13 02:00:00 | ETHUSDT 15m | Close: 2166.82 | SELL
 Fibonacci Retracement Levels: {'ratio0_286': 2155.95, 'ratio0': 2193.9}

ETH balance before order: 0.0765
USDT balance before order: 0.0973
Order quantity after rounding and fees: 0.07646
ETH balance after order: 0.0001
USDT balance after order: 165.5494

**Comment by whittlem** [comment]
Thanks for the info. I can see how the bot may get confused if there is a balance in both currencies of a market. It would start with a buy or sell depending on which balance is higher numerically (and in almost all cases this is correct). Are you just letting me know or are you proposing an update? I think your case is a very rare case.

**Comment by stefanoregis** [comment]
Well it's something that can happen when you start maybe, with a small amount, you can buy a part of a currency like ETH or BTC and when the order is closed it doesn't take all the amount (maybe because USDT had some variations) . If you trade with FIAT, in many countries, like the one I live, at the end of the year, you have to declare all the transactions you have made, and in this case it can be an amount,... I would prefer to declare everything at the end, if I decide to withdraw, that's because i prefer only to trade between a stable and other crypto

But the other problem i think is still missing... Take a look at this log for example, i guess, with binance, there's a problem in the calculation of the buy price and as a consequence, in the margin


|            Market : BCHUSDT                                                  |
|       Granularity : 1h                                                       |
|        Sell Upper : 3.0%                                                     |
|        Sell Lower : -2.0%                                                    |

current price is 694.65
**last buy price 42.759867223126**
change pcnt 1524.5373176096052
! Profit Bank Triggered (> 3.0%)

|         Iteration : 1 (BULL)                                                 |
|         Timestamp : 2021-04-13 07:00:00                                      |


|             Close : 694.65                                                   |
|             EMA12 : 677.17                                                   |
|             EMA26 : 676.75                                                   |
|    Crossing Above : True                                                     |
|   Currently Above : True                                                     |
|    Crossing Below : False                                                    |
|   Currently Below : False                                                    |
|         Condition : EMA12 is currently crossing above EMA26                  |
|             SMA20 : 673.67                                                   |
|            SMA200 : 648.87                                                   |


|              MACD : 0.41                                                     |
|            Signal : -1.54                                                    |
|   Currently Above : True                                                     |
|   Currently Below : False                                                    |
|         Condition : MACD is currently above Signal and has crossed over      |

|            Action : SELL                                                     |

**|            Margin : 93.84%%                                                  |**


|                      *** Executing LIVE Sell Order ***                        |

BCH balance before order: 0.2485
USDT balance before order: 0.0748
Order quantity after rounding and fees: 0.24837
BCH balance after order: 0.0002
USDT balance after order: 171.9065

**Comment by stefanoregis** [comment]
i guess the line 106 in TradingAccount.py :
`                df['price'] = df['size'] * df['value']
`

should be instead like this, in order to get the correct buy price:

`                df['price'] = df['value'] / df['size']`


But tell me if I'm wrong,
Thanks a lot for your support

**Comment by whittlem** [comment]
You are right, I fixed it. I don't use Binance so have very few orders in my history so didn't spot that. If you pull down the latest code it has the fix.

If you create a script and run this you should be able to see if it looks better for you.

    from models.PyCryptoBot import PyCryptoBot
    from models.TradingAccount import TradingAccount

    # Binance Live orders
    app = PyCryptoBot(exchange='binance')
    app.setLive(1)
    account = TradingAccount(app)
    orders = account.getOrders('BCHUSDT')
    print (orders)

**Comment by stefanoregis** [comment]
it's perfect @whittlem thank you!

**Comment by whittlem** [comment]
Good news. Thanks for confirming.
