### ISSUE TITLE
config.yaml vs config.json?

### ISSUE THREAD

**Issue by CaseyJonesIRL** [whittlem/pycryptobot#442]
**Description**
It's unclear from the documentation if I should use a config.json referenced in all the readme documentation or a config.yaml used in the latest code, or both. When using the below config.yaml and trying to run _live_ I get the following traceback.

`(base) caseysteuer@penguin:~/trading/DOGE-USD$ python3 pycryptobot.py --ma
rket DOGE-USD --live 1
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.9/site-packages/pandas/core/indexing.py", line 1298, in _validate_read_indexer
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['created_at', 'market', 'action', 'type', 'size', 'filled', 'fees',\n       'price', 'status'],\n      dtype='object')] are in the [columns]"`

I suspect this is a key issue because I _am_ able to successfully run simulation mode.

I'm running python3.9 on Debian10 and have verified all my requirements are up to date.

My config yaml looks like (with proper indentation):
coinbasepro:
  api_url: https://public.sandbox.pro.coinbase.com
  config:
    base_currency: USD
    quote_currency: DOGE
    live: 0
  api_key_file: coinbasepro.key

and my coinbasepro.key looks like (placeholders used instead of actual values):
Key
Secret Key
Passphrase

**Comment by loomsen** [comment]
Hi, you may use either or. I prefer yaml as it's for humans, but you could als go json if you like quotes, commas and brackets :)

I haven't seen the error yet, but it's not related to the config.

**Comment by CaseyJonesIRL** [comment]
Thank you @loomsen! Yes I prefer the more humany yamls for my bots to eat lol. Okay, that's good to know it's likely not related to config. Any other thoughts regarding the error message? I find it peculiar that my simulated runs work perfectly and this error is isolated only to when I set the --live 1 argument.

**Comment by basilschneider** [comment]
> **Description**
> It's unclear from the documentation if I should use a config.json referenced in all the readme documentation or a config.yaml used in the latest code, or both. When using the below config.yaml and trying to run _live_ I get the following traceback.
> 
> `(base) caseysteuer@penguin:~/trading/DOGE-USD$ python3 pycryptobot.py --ma rket DOGE-USD --live 1

I assume that whitespace inside "market" is a copy paste error?

**Comment by CaseyJonesIRL** [comment]
Yes, that is a copy paste error. To confirm that whitespace was not in the actual run above I executed a run successfully using the argument --fast sim, then I ran the same command (up arrow) but changed only the --fast sim argument to --live 1. This still produced the same exact error.

**Comment by DisgruntledJaeger** [comment]
Hate to be the necromancer here, but is there a fix to this? I'm getting the exact same error and this is the only place I can find it mentioned.
