### ISSUE TITLE
make the config.json files keep the initial structure

### ISSUE THREAD

**Issue by wellingtonf-souza** [whittlem/pycryptobot#457]
**Describe the bug**
This is a very basic question, but I'm not familiar with docker-compose.

I created two folders to evaluate two markets. I performed the configuration of the config.json files passing api_key, api_secret, api_passphrase and other necessary parameters. When I run docker-compose up -d, the containers are run, but when I go into the config.json files, they don't have api_key, api_secret, api_passphrase. Instead the api_key_file parameter appears.

How do I make the config.json files keep the structure I initially defined? Again, I think it's basic, but I'm not familiar with docker-compose. I appreciate the help and commitment in the development of this project.

My docker-compose.yaml:

~~~
version: "3.9"

services:
  dotusdt:
      build:
        context: .
      container_name: dotusdt
      volumes:
        - ./market/DOTUSDT/config.json:/app/config.json
        - ./market/DOTUSDT/pycryptobot.log:/app/pycryptobot.log
        - ./market/DOTUSDT/graphs:/app/graphs
        - /etc/localtime:/etc/localtime:ro
      environment:
        - PYTHONUNBUFFERED=1
      deploy:
        restart_policy:
          condition: on-failure

  maskusdt:
      build:
        context: .
      container_name: maskusdt
      volumes:
        - ./market/MASKUSDT/config.json:/app/config.json
        - ./market/MASKUSDT/pycryptobot.log:/app/pycryptobot.log
        - ./market/MASKUSDT/graphs:/app/graphs
        - /etc/localtime:/etc/localtime:ro
      environment:
        - PYTHONUNBUFFERED=1
      deploy:
        restart_policy:
          condition: on-failure
~~~

My config.json before `docker-compose up -d`

~~~
{
    "coinbasepro": {
        "api_url": "https://api.pro.coinbase.com",
        "api_key" : "0000000000000000000",
        "api_secret" : "0000000000000000000000000000",
        "api_passphrase" : "000000000000000000",
        "config": {
            "base_currency": "DOT",
            "quote_currency": "USDT",
            "live": 0,
            "verbose": 0,
            "sellatloss": 0,
            "autorestart": 0,
            "sim": "fast",
            "granularity": 3600
        }
    },
    "telegram": {
        "token": "00000000000000000000000000000000000000",
        "client_id": "000000000000"
    }
}
~~~

My config.json after `docker-compose up -d`

~~~
{
    "coinbasepro": {
        "api_url": "https://api.pro.coinbase.com",
        "config": {
            "base_currency": "DOT",
            "quote_currency": "USDT",
            "live": 0,
            "verbose": 0,
            "sellatloss": 0,
            "autorestart": 0,
            "sim": "fast",
            "granularity": 3600
        },
        "api_key_file": "coinbasepro.key"
    },
    "telegram": {
        "token": "00000000000000000000000000000000000000",
        "client_id": "000000000000"
    }
}
~~~

**Comment by espensgr** [comment]
You need to add the key into volumes:
`- ./market/MASKUSDT/coinbasepro.key:/app/coinbasepro.key`

and in the config file:
`"api_key_file": "/app/coinbasepro.key"`

**Comment by aweltig** [comment]
Is API passphrase just your password for the account?

**Comment by wellingtonf-souza** [comment]
@aweltig when creating a new API key in Coinbase, the passphrase appears right below the permissions

**Comment by aweltig** [comment]
Yup I figured that out. Now what is the line of code to start the bot?
python3 pycryptobot.py just seems to run a simulation.
