### ISSUE TITLE
XLM problem 

### ISSUE THREAD

**Issue by yassirkachri** [whittlem/pycryptobot#46]
Hi 
   I got an error when the bot triggered an Order for XLM
XLM balance before order: 190.81
EUR balance before order: 0.0
{'product_id': 'XLM-EUR', 'type': 'market', 'side': 'sell', 'size': 190.81}
error: POST (400) https://api.pro.coinbase.com/orders - size is too accurate. Smallest unit is 1.00000000
XLM balance after order: 190.81
EUR balance after order: 0.0

**Comment by whittlem** [comment]
I think I fixed this a few days ago. Can you do a "git pull" to make sure you are running the latest code. If you still have problems let me know.

**Comment by yassirkachri** [comment]
thank you
I will keep you in touch
