### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 49 (char 48)

### ISSUE THREAD

**Issue by whittlem** [whittlem/pycryptobot#48]
I swapped XLM-EUR for ADA-EUR yesterday. I've had this crash twice.

2021-04-16 11:46:53 | ADA-EUR (BULL) | 3600 | Current Price: 1.171
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 49 (char 48)
ADA-EUR % 

Anyone else getting it as well? Or is it ADA specific?

**Comment by paolodina** [comment]
fwiw, I did the same a couple of weeks ago (XLM-EUR --> ADA-EUR) and the bot run two days with ADA-EUR, it didn't raise any exception.

**Comment by maqzi** [comment]
not sure if this is connected, but after running an ETH-USD bot for a day, mine broke at the first buy signal:

AttributeError: 'str' object has no attribute 'decode'

**Comment by whittlem** [comment]
@paolodina Thanks, I'll turn on stack tracing and see what causes it.

@maqzi Not seen that before. If you see it again let me know.
