### ISSUE TITLE
Auto transfer of remaining funds to default portfolio

### ISSUE THREAD

**Issue by alan-insitu** [whittlem/pycryptobot#492]
After a sell there can be some base currency left over, either as dust or a deliberate percentage for accumulation. In these situation it would be helpful if the remaining funds could be automatically transferred to a specific portfolio for holding. For example the default portfolio on Coinbase.

This could also be done with the remainder of the quote currency after a buy, but less important.

Both of these features would also remover the returned insufficient funds error that is returned when there is only a small amount of base or quote currency left.

Happy to help work on this, but I've not even started to look at the code yet.

**Comment by whittlem** [comment]
This won't be included because it would require enabling the API keys for transfers. This poses a big risk if mistakes are made. At the moment if someone got hold of someones API keys they could just trade. If you enable transferring it would mean all funds can be transferred out.
