### ISSUE TITLE
Buy and Sell Count is Zero when testing?

### ISSUE THREAD

**Issue by robotron2084** [whittlem/pycryptobot#50]
I'm testing the bot and I'm seeing no buy or sell activity. I have sim'ed, as well as waited over the course of a couple days.

Configuration: 
   "config" : {
        "cryptoMarket" : "BTC",
        "fiatMarket" : "USD",
        "live" : 0,
        "sellatloss" : 1
    }

I'm using Coinbase Pro. Is there anything I'm doing wrong? Does my account need to have BTC in it in order for purchasing to occur?

**Comment by whittlem** [comment]
I wrote this article on Medium which shows the configuration I am using.
https://medium.com/coinmonks/pycryptobot-results-and-config-57fb6625a6d9

This will answer your question.
