### ISSUE TITLE
Stops with timeout within some  minutes

### ISSUE THREAD

**Issue by yk2kus** [whittlem/pycryptobot#51]
--------------------------------------------------------------------------------
|                             Python Crypto Bot                                |
--------------------------------------------------------------------------------
|            Market : ADAEUR                                                   |
|       Granularity : 1h                                                       |
--------------------------------------------------------------------------------
|          Bot Mode : LIVE - live trades using your funds!                     |
|       Bot Started : 2021-04-16 21:32:57.015384                               |
================================================================================

================================================================================
|         Iteration : 1 (BULL)                                                 |
|         Timestamp : 2021-04-16 20:00:00                                      |
--------------------------------------------------------------------------------
|             Close : 1.19                                                     |
|             EMA12 : 1.18                                                     |
|             EMA26 : 1.19                                                     |
|    Crossing Above : False                                                    |
|   Currently Above : False                                                    |
|    Crossing Below : False                                                    |
|   Currently Below : True                                                     |
|         Condition : EMA12 is currently below EMA26 and has crossed over      |
|             SMA20 : 1.18                                                     |
|            SMA200 : 1.11                                                     |
--------------------------------------------------------------------------------
|              MACD : -0.01                                                    |
|            Signal : -0.01                                                    |
|   Currently Above : True                                                     |
|   Currently Below : False                                                    |
|         Condition : MACD is currently above Signal and has crossed over      |
--------------------------------------------------------------------------------
|            Action : WAIT                                                     |
================================================================================
2021-04-16 21:38:05 | ADAEUR (BULL) | 1h | Current Price: 1.2
2021-04-16 21:43:09 | ADAEUR (BULL) | 1h | Current Price: 1.20164
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=20)

During handling of the above exception, another exception occurred:

requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=20)

![image](https://user-images.githubusercontent.com/6999933/115095525-8e941400-9f19-11eb-9fea-915656fd627d.png)
****

**Comment by whittlem** [comment]
That looks like a connection issue to me. Are you sure your Internet connection is stable?
