### ISSUE TITLE
market error 

### ISSUE THREAD

**Issue by hellresistor** [whittlem/pycryptobot#515]
**Describe the bug**
Cannot run simulation. KeyError: 'market' . have try many..
f I put a wrong, he detect not exist that market

**To Reproduce**
Run command  `python3 pycryptobot.py --market ADA-BTC --sim fast --simstartdate 2021-08-1 --simenddate 2021-10-1`

**Expected behavior**
```
ADA-BTC
ADABTC
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'market'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/domato/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    raise KeyError(key) from err
KeyError: 'market'
```

**Comment by jegb** [comment]
I discovered similar error on --stats, you need to set live: 1 in order to pick it up and comment out the sim configs on the json file. In this case looks like the -BTC side may not be supported, only use fiat/stable currency

**Comment by mannerz** [comment]
Is there any update on this? I just installed the bot last night and wanted to simulate before using in real case. 
But I get this same error with arguments:
--exchange binance --market BTC-USDT --sim fast

**Comment by designboxcom** [comment]
Have you ever found a solution to this problem ? No matter what I am trying to change in the config.json file, it always returns this error.
