### ISSUE TITLE
Insufficient quote funds on some pairs

### ISSUE THREAD

**Issue by Kyconic44** [whittlem/pycryptobot#528]
Get Insufficient quote funds message on some pairs after last update. 

Basically use one GBP pot which all my bots fight over. 
Coins I have tried which give message: ADA, XRP, DOGE, SHIB, DAT
Coins which dont have the message: DOT
All bots use the same config file set up as below:

{
    "binance": {
        "api_url": "https://api.binance.com",
        "api_key_file": "binance.txt",
        "config" : {
            "base_currency" : "(what ever coin bot is set up for)", 
            "quote_currency" : "GBP",
            "live" : 1,
            "sellatloss" : 1,
	    "selllowerpcnt" : -5,
            "sellatresistance" : 1,
            "trailingstoploss" : -1.5,
            "trailingstoplosstrigger" : 5,
            "nosellmaxpcnt" : 3,
            "nosellminpcnt" : -3,
            "disablebullonly" : 1,
            "disablebuynearhigh" : 0,
            "buynearhighpcnt" : 3,
            "disablebuymacd" : 0,
            "disablebuyobv" : 0,
            "disablebuyelderray" : 1,
            "disablefailsafefibonaccilow" :0 ,
            "disableprofitbankreversal" : 0,
            "disabletracker" : 1,
            "disabletelegram" : 0,
            "autorestart" : 0,
            "graphs" : 0,
            "verbose" : 0,
            "enableinsufficientfundslogging": 1,
            "stats" : 0
        }
    },
   "telegram": {
        "token": "HIDDEN",
        "client_id": "HIDDEN"
    }
}
 

Have plenty of quote funds in account (bots are quoting that there is £0) 

Running on Raspberry pi 4 and a Pi zero both behave the same. 

**Additional context**
![pycry](https://user-images.githubusercontent.com/92570592/137449565-2b1781de-0637-44e3-8dcb-b62cba481c85.PNG)

Thanks for looking

**Comment by ramiss** [comment]
same

**Comment by Kyconic44** [comment]
Done some testing on another PI, managed to get 3 bots working fine but the 4th which was made the same way came up with the issue. Then restarted one and the error moved to that one. Just having 4 identical bots and some show errors and some don't really confuses me.
