### ISSUE TITLE
How can I solve this issue

### ISSUE THREAD

**Issue by mantakeke** [whittlem/pycryptobot#53]
During handling of the above exception, another exception occurred:

urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'Varolan bir bağlantı uzaktaki bir ana bilgisayar tarafından zorla kapatıldı', None, 10054, None))

During handling of the above exception, another exception occurred:

requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'Varolan bir bağlantı uzaktaki bir ana bilgisayar tarafından zorla kapatıldı', None, 10054, None))

**Comment by whittlem** [comment]
That looks like a connection issue to me. Are you sure you have a stable Internet connection and your connection isn't being firewalled?
