### ISSUE TITLE
UnboundLocalError("local variable 'margin_text' referenced before assignment")

### ISSUE THREAD

**Issue by MadScrewdriver** [whittlem/pycryptobot#535]
![Screenshot from 2021-10-19 20-09-39](https://user-images.githubusercontent.com/33846428/137966784-b040d66d-9270-4089-938f-8d51b87c1755.png)
Varaible `margin_text` is not assigned but it is used sometimes.

Probably here: [https://github.com/whittlem/pycryptobot/blob/main/pycryptobot.py#L1092](url) python goes in to `elif` before `margin_text` is assigned  (before `state.last_action  == "BUY"`) throwing exception.

**Comment by esaravanakumar89** [comment]
i have defined like this to solve this issue.

####Added Margin_text
1116                     if state.last_buy_size > 0:
1117                         margin_text = truncate(margin) + "%"
1118                     else:
1119                         margin_text = "0%"
