### ISSUE TITLE
Live trading with mocked funds (simulation)

### ISSUE THREAD

**Issue by asm-cygu** [whittlem/pycryptobot#545]
Hello !

I Would like to test your bot in live case but, with "mock funds"
I would like to set an amount of $ and see the behavior with my config.json setup.

I would like to catch only trade decision (BUY/WAIT/SELL) without action ;-)

thank you !

**Comment by edrickrenan** [comment]
You can run the bot with `"live": 0` in the config and you should get the result you want.

**Comment by asm-cygu** [comment]
ok, I will test it later,
"live": 0 need "coinbase.key" file ?
The start amount is configurable ?

**Comment by asm-cygu** [comment]
Completly what I need ! Thanks ;-) !
