### ISSUE TITLE
Unable to pull docker image

### ISSUE THREAD

**Issue by linds14sr20det** [whittlem/pycryptobot#56]
I'm unable to pull the docker image, seeing this permission error:
`Error response from daemon: pull access denied for ghcr.io/whittlem/pycryptobot/pycryptobot, repository does not exist or may require 'docker login': denied: permission_denied: read_package`

I've setup a personal access token with the required read package and I've also verified I'm logged in.

**Comment by robotron2084** [comment]
Similar issue:
```
:~$ docker pull ghcr.io/whittlem/pycryptobot/pycryptobot:latest
Error response from daemon: Head https://ghcr.io/v2/whittlem/pycryptobot/pycryptobot/manifests/latest: unauthorized
```

**Comment by alexandreafc** [comment]
I had the same issue, to solve it you can build the image in your pc, got to where you have the Dockerfile and execute the command below:

docker build -t pycryptobot

**Comment by whittlem** [comment]
Thanks for answering this. Does this need to be added to the documentation?

@lvlie kindly added the Docker functionality. Maybe he can confirm?

**Comment by lvlie** [comment]
Oh cool I was still using my own version. That is "pullable" for unauthenticated users because the package is set to public. 
Did you make sure to set it to public in your Profile > Packages section. On mobile it should look something like this: 

![Screenshot_20210419-191650_Chrome](https://user-images.githubusercontent.com/8437831/115277022-0a71a480-a144-11eb-85af-6147c8ba1ebe.jpg)

**Comment by alexandreafc** [comment]
Hi @whittlem I think yes, you can add the both information, how to buiild a image and how to run a image.

Build your won image if necessary:
docker build -t pycryptobot_xx_yy .

where xx = ADA
where yy = EUR

Running a docker image:
docker run -d --rm --name pycryptobot_xx_yy_container pycryptobot_xx_yy

**Comment by whittlem** [comment]
Thank you. I will improve the instructions as per your message.

**Comment by whittlem** [comment]
Thanks @lvlie, I made the package Public now.

Can you all try again please? It should work now.

**Comment by whittlem** [comment]
@lvlie and @alexandreafc, does this article look okay to you:
https://whittle.medium.com/pycryptobot-docker-container-cffe38a344bf?sk=4d4ea66e5f1af74cf675b78ace3b73e8

**Comment by lvlie** [comment]
Looks good to me, good write up :-)

**Comment by whittlem** [comment]
Great, thanks.
