### ISSUE TITLE
Insufficient Fund in CoinBase Pro

### ISSUE THREAD

**Issue by esaravanakumar89** [whittlem/pycryptobot#562]
Hi,

   I am trying the cryptobot for the first time, As i passed the information in config file and passed the config as argument using '--config' --option, when i trigger the bot, i am getting insufficient funds."Exception: Insufficient Funds! (BTC=0.0, USD=0.0)
", As i am having 50USD as balance in my wallet. 

Here is my config file.

[root@crypto1 pycryptobot]# cat btc.json 
{
    "coinbasepro": {
        "api_url": "https://api.pro.coinbase.com",
        "api_key_file": "/opt/my.key",
        "config" : {
            "base_currency" : "BTC",
            "quote_currency" : "USD",
            "live" : 1,
            "sellatloss" : 0,
            "sellatresistance" : 0,
            "trailingstoploss" : -1.5
      }
}

**Desktop (please complete the following information):**
 - OS: [RHEL 7]
 
 - Version [4.2.1]

![image](https://user-images.githubusercontent.com/6051059/140861970-38934a37-858f-4769-a0f7-844a4513211f.png)

**Comment by chriskoepf** [comment]
This is more likely a config file issue than a code issue.  Many people have similar problems on first start because something is not quite right in their config file.  Recommend checking the telegram channel.  Many people to help there that have most likely had the same problem.

https://t.me/pycryptobotchat

**Comment by esaravanakumar89** [comment]
Thank you let me check.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
