### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by yassirkachri** [whittlem/pycryptobot#59]
Hi
I'm getting this error "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)" 
in ETH-EUR / XLM-EUR and ADA-EUR

any idea ?

Thanks

**Comment by whittlem** [comment]
It's difficult to tell from that output alone. I suspect this is related to a bug I fixed a while ago. Run "git pull" to get the latest updates. it should resolve your issue.

**Comment by yassirkachri** [comment]
I already have the last version and run git bull only this morning
I only have this information there are no additional information on the screen

**Comment by whittlem** [comment]
When

**Comment by whittlem** [comment]
When do you get this error message? The minute the bot starts? That could be a problem with your config.json.

**Comment by yassirkachri** [comment]
for ADA I got the message after the first Signal but for others coins I got it after some hours of working 
--------------------------------------------------------------------------------
|          Bot Mode : LIVE - live trades using your funds!                     |
|       Bot Started : 2021-04-19 13:18:44.384256                               |
================================================================================
|        Sell Upper : 3%                                                       |
|      Sell At Loss : 0                                                        |
================================================================================
2021-04-19 13:15:00 | ADA-EUR (BEAR) | 900 | Close: 1.03 | v EMA12/26: 1.04 < 1.05 v | ^ MACD: -0.01 > -0.01 ^ | v OBV: -308827.1600 (-14.27%) v | ERI: sell | WAIT | Last Action: BUY | 0%
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by whittlem** [comment]
That is a bit strange. All my bots are working and I'm not aware of anyone else having issues.

Can you please run this...
git reset --hard
git pull

And try start your bots again.

**Comment by yassirkachri** [comment]
done. I'll keep you in touch

**Comment by maqzi** [comment]
Using the latest version. I just saw this too after 116 iterations on ATOM-USD

![image](https://user-images.githubusercontent.com/21354842/115324304-a8bb3580-a157-11eb-96a7-7af9e09b7096.png)


Here's my config:

{

    "coinbasepro": {
        "api_url": "https://api.pro.coinbase.com",
        "api_key": "x",
        "api_secret": "x",
        "api_passphrase": "x",
        "config": {
            "base_currency": "ATOM",
            "quote_currency": "USD",
            "live": 1,
            "verbose": 1,
            "selllowerpcnt": -10,
            "sellatloss": 1,
            "granularity": 60
        }
    },
    "telegram": {
        "token": "x",
        "client_id": "x"
    }
}

**Comment by whittlem** [comment]
A granularity of 60 is very short. You almost surely will make a loss with this configuration. You don't have enough time to make the trade and recover the fees before the sell. I would remove the granularity and let the bot "smart switch" automatically between the 1 hour and 15 minute graphs.

I wrote an article on Medium which explains my configuration which works really well for me.
https://medium.com/coinmonks/pycryptobot-results-and-config-57fb6625a6d9

I'm going to turn on more detailed stack traces so when these errors happen it will be easier to identity where they happened.
