### ISSUE TITLE
KeyError: 'market'

### ISSUE THREAD

**Issue by Chezes** [whittlem/pycryptobot#592]
Hello, i try to run script on Raspberry pi 4 and also on Windows 10.
Here and here i have similar problem:

`
C:\pycryptobot-main\BTC-USDT>python3 pycryptobot.py --market BTC-USDT
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'market'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\sarec\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\core\indexes\base.py", line 2897, in get_loc
    raise KeyError(key) from err
KeyError: 'market'
`

Is there any solution for this problem?

**Comment by Chezes** [comment]
Hello again.
It looks like after cloning separate instance of repo for exact exchange (example BTC-USDT) - if I`m trying to start bot from this directory I have an error. But if I start bot from main directory it`s ok. 
So:
C:\pycryptobot-main\BTC-USDT>python3 pycryptobot.py --market BTC-USDT # this is not working
C:\pycryptobot-main>python3 pycryptobot.py --market BTC-USDT # this is working

Is this meant to be like this or I`m still doing something wrong?

**Comment by notoriousBLP** [comment]
thats because all of the bot's librarkies reside in the root (main) folder
and the paths need to stay the same. you can pass in a config file from
wherever with --config /path/to/config/file.json and still start the bot
where it needs to be.

**Comment by iwasnothing** [comment]
I got the same error no matter which folder I run the command.  Same error even I use the docker to run the image.

However, if I change the config.json to use coinbasepro instead of binance, there is no such error.

Is there a bug in binance code?

**Comment by TUstudents** [comment]
This 'market' error is also shown, if incompatible options are given in the config.json file, e.g. , if "live" : 0 and "stats" : 1. The error is very general and not specific, pointing to the problem.
