### ISSUE TITLE
Having open orders (from telegram bot) ordered alphabetically

### ISSUE THREAD

**Issue by Rainking80** [whittlem/pycryptobot#595]
**Is your feature request related to a problem? Please describe.**
I like to compare my open orders with the cryptos on the platform. The bot is not sending them ordered.

**Describe the solution you'd like**
Open orders sent by telegram bot should be ordered alphabetically.

**Describe alternatives you've considered**
-

**Additional context**
![image](https://user-images.githubusercontent.com/5574367/144310375-10c9056a-da1f-4894-b854-9a93a7534929.png)

**Comment by chriskoepf** [comment]
Revised in current beta 4.6.x
