### ISSUE TITLE
Implement CCXT to support more markets

### ISSUE THREAD

**Issue by crapher** [whittlem/pycryptobot#600]
**Describe the solution you'd like**
Implement the CCXT to allow to choose between almost any Crypto Exchange
https://github.com/ccxt/ccxt

**Additional context**
The CCXT library currently supports 110 cryptocurrency exchange markets and trading APIs including Kucoin, Binance, and Coinbase that are already supported by pycryptobot.
This also solves the addition of new markets.

**Comment by notoriousBLP** [comment]
Yes, but their websockets interface is a licensed product.

**Comment by crapher** [comment]
You are right, I didn't realize that you need CCXT Pro for websockets.

But, even with that issue, adding the CCXT without websockets, I think would be a great addition to the project.
Those who want/need to use websockets can continue using the current implementation for coinbase / binance / kucoin, but those that don't need it can use any other crypto exchange.

It is just a suggestion / improvement. :)

**Comment by whittlem** [comment]
I don't want the reliance on 3rd party libraries. CCTX has loads of open issues. I implemented the Binance official library and it was a disaster. I had to rewrite it all from scratch.

**Comment by crapher** [comment]
Crystal clear! Thanks Michael!

**Comment by lazydroid** [comment]
as of 2 month ago binance never had an "official" library. there were a bunch of 3rd party libraries, but "official" binance support channel clearly indicated they do not support or condone any existing library as official.
