### ISSUE TITLE
If an stop-limit order is existing for a traded currency pair, bot will fail selling (ok) but enters margin sold 0% in data.json (nok)

### ISSUE THREAD

**Issue by Rainking80** [whittlem/pycryptobot#609]
**Describe the bug**
I do have some stop-limit orders at Binance. The bot (scanner) choose sometimes those currencies to trade. The bot then tries to sell the amount on a sell signal (which fails because the order is blocked). But it logs it as a sucessful trade with 0% margin (see screenshot). Also it tries to sell multiple times per day.

**To Reproduce**
1. Create a bot with the same curreny like an open stop-limit order.
2. let it run

**Expected behavior**
A 0% margin should not be logged as a successful trade. Also avoid selling a stop-limit order would be great.

**Screenshots**
![image](https://user-images.githubusercontent.com/5574367/144927288-f531d7cb-8385-4298-b502-d216c64116fd.png)

**Desktop (please complete the following information):**
-

**Smartphone (please complete the following information):**
-

**Additional context**
Idk if that behaviour is observable on cross platform. I just saw it at Binance.

**Comment by notoriousBLP** [comment]
I'm pretty sure somewhere in the docs it is mentioned to not run the bot in
the same portfolio/account as one you are already using for trades. It will
do exactly this type of stuff. Also, your other transactions throw the
bot's decision making and stats off, as you've already clearly experienced.
RTFM?

**Comment by Rainking80** [comment]
Thx, for pointing that out. I cannot remember that I read that.
