### ISSUE TITLE
Support for websockets v9.1?

### ISSUE THREAD

**Issue by SolosoftNL** [whittlem/pycryptobot#613]
**Is your feature request related to a problem? Please describe.**
Hi,

I encounter a problem when installing the program. See below 

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
unicorn-binance-websocket-api 1.30.0 requires websockets==8.1, but you have websockets 9.1 which is incompatible.

i cannot downgrade because of other programs than run under websockets 9.1
When does websockets get support for pycryptobot?

**Comment by whittlem** [comment]
Try this:
git checkout main
git pull
python3 -m pip install -r requirements.txt -U

If you are still getting library conflicts on your system you can install them into a virtual environment.

python3 -m venv venv
source venv/bin/activate
python3 -m pip install -r requirements.txt

**Comment by SolosoftNL** [comment]
Many many thanks in advance whittlem. Will try this tomorrow. Especially the tip about virtual environments I wasn't aware of. Need more time to read me in this concept/topic. This project already took my whole weekend😁
