### ISSUE TITLE
General installation issues on Raspberry pi 4

### ISSUE THREAD

**Issue by Tobiah10** [whittlem/pycryptobot#629]
**Describe the bug**
while following the manual install steps to install the trading bot onto a raspberry pi 4, running the requrment.txt install step pandas will install but the installed version does not satisfy the version requirements. the version required is 1.1.4 and the versions listed go from 0.1 to 0.24.2. I have followed the steps to manually install the newest version of pandas (1.3.5) and it did not fix the issue. 

**To Reproduce**
follow the manual install steps.

**Desktop (please complete the following information):**
 - OS: [Raspberry pi OS Buster]

**Additional context**
I apologize if I did not provide enough information, if any more is needed i will do my best to supply it.

**Comment by warrmr** [comment]
Try this? 

https://github.com/yanone/raspberrypycryptobot

**Comment by Tobiah10** [comment]
i did realize that i was trying to install it with just python and not python3 but an even longer list of issues and errors came up. im going to start a fresh install and try again maybe me installing a newer version of pandas caused some errors. i will add another message if i run into more issues or it it fixes it. thank you though, i will try the docker install next if this doesn't fix it

**Comment by Tobiah10** [comment]
after starting a fresh install of Raspbian Buster, the install worked. i guess the manual install of Pandas caused issues. the only issue found was that the Numpy version was incompatible. the installed version is 1.16.2 and the required is 1.16.5 to 1.23.0. everything else installed properly. will this prevent the bot from running properly or should it be okay? another message that come up was that test.py and another file were in a non-PATH location and should be moved. will that be okay?

**Comment by Tobiah10** [comment]
i have been able to fix the Numpy version issue by running "$pip3 install --upgrade --user numpy" this fixed the version issue, but it created another issue that directed me to the Numpy website. running the recommended command "$sudo apt-get install libatlas-base-dev". this updated the libraries and corrected that issue. after setting up the config file and Key file. I'm currently running into an error with Pandas - KeyError: 'Market' i am unsure how to fix this or even where to begin. any help with this new error would be helpful. thank you.

**Comment by warrmr** [comment]
@Tobiah10  have a look at #592 the last post should help hopefully.

**Comment by Tobiah10** [comment]
okay i figured out my issue, thank you. i was trying to run the bot using "$Python3 pycyptobot.py --stats". i couldnt seem to find a clear instruction on how to setup the run command. i used the command from the other thread and it started working. now i just have to figure out how to set up the rest of the config stuff. is there any reference to all the settings for the config.json file so i can better understand what each setting does and how to change them?

**Comment by Tobiah10** [comment]
![2021-12-26-173722_1920x1080_scrot](https://user-images.githubusercontent.com/24900937/147421584-78e1b64e-2f4b-47d8-b530-563037c4d3fb.png)

im running into an issue where my api keys are not being accepted. i have set them up on Binance and double checked that they are correct. ive also tried manually putting them into the Config.json file (i realize that is not recommended, but i was trying to troubleshoot) but it just transferred them to a new Binance.Key file and still didn't accept them. ive tried a second API with new keys and it still dint accept them. Any idea on how to fix this?

**Comment by Tobiah10** [comment]
i apologize for editing this post so much but i did find a few more things out and got the bot working.
1. Raspberry pi os (Buster) does not have the appropriate python version installed and from what I've tried, updating the version breaks the pip installer. 
2. raspberry pi os (Bullseye) has the required version but running the manual install steps does result in a few issues after preforming the install requirements.txt command.
3. adding sudo to the install requirements.txt command seems to fix the library install issue.
4. there is a different API URL for Binance users in the US "https://api.binance.us". attempting to use my US api credentials for the international binance api url resulted in invalid api errors. 

thank you for assisting me thought my issues. I'm still pretty unsure on what all the settings in the config file do, so if there is a document or video explaining them that would be grateful. also, my program is only updating every 1 min or so, is that normal or is there a way to speed it up?
