### ISSUE TITLE
empty Docker logs

### ISSUE THREAD

**Issue by horamarques** [whittlem/pycryptobot#65]
Logs are not available when using docker logs (docker logs -f btc-eur).

To fix it include the environment var "PYTHONUNBUFFERED"
```   btc-eur:
        image: ghcr.io/whittlem/pycryptobot/pycryptobot:latest
        container_name: btc-eur
        environment:
            - PYTHONUNBUFFERED=1
 ```

**Comment by whittlem** [comment]
@lvlie, I noticed this as well. I didn't see any logs when I tried it out last night. Any ideas?

**Comment by lvlie** [comment]
Ah, yeah indeed, the way python logs does not play nicely with docker logs. The environment variable I added in my config as well, forgot to PR it :) 
With the PYTHONUNBUFFERED var Python will spit out its logs to stdout in a way it will show. Good to include that in the compose example

**Comment by lvlie** [comment]
You can also change the entrypoint to use `ENTRYPOINT [ "python3", "-u", "pycryptobot.py" ]` (notice the -u). That way users don't need to set the PYTHONUNBUFFERED environment variable

**Comment by DmitriyLyalyuev** [comment]
https://github.com/whittlem/pycryptobot/pull/69

**Comment by DmitriyLyalyuev** [comment]
PR merged. This can be closed I think.
