### ISSUE TITLE
Bug in BUY strategy?

### ISSUE THREAD

**Issue by MrDeadLock** [whittlem/pycryptobot#656]
Strategy.py, line ~135:

I could be wrong, but it seems like buy signal 2 is requiring both crossovers (`ema12gtema26co` and `macdgtsignalco`) to be True?
I believe this should be `ema12gtema26` (without the -co) and `macdgtsignalco`, as buy signal 1 is triggering for the opposite, `ema12gtema26co` and `macdgtsignal`

**Comment by alexfromvl** [comment]
Use backtest with debug ema12gtema26co and macdgtsignalco
