### ISSUE TITLE
Not buying in binance

### ISSUE THREAD

**Issue by letsautom8** [whittlem/pycryptobot#66]
I tried simulator multiple times and whatever crypto-quotation combination I use, the bot only wait and wait.
It does not do buy.
It sold some of the coins but never buy back and I see many trends that are missed because of the wait time.
I tried live funds as well and my fund sits in USDT be it BTC/USDT, DOGE/USDT, or ETH/USDT for 3 days without any buy.
Could it be an issue?

**Comment by whittlem** [comment]
It's difficult to tell without seeing your configuration. 

This article covers the configuration I'm using:
https://medium.com/coinmonks/pycryptobot-results-and-config-57fb6625a6d9

The markets have been very quiet the last few days after the crash last weekend. It's starting to bounce back now. I had a good BCH trade yesterday. ETH, BTC, LTC, XLM, and ADA have not had anything on them for a few days. I expect we will get something soon. I suspect your config and bots are fine and it's just market conditions.

**Comment by whittlem** [comment]
I've just had an ETH buy and sell today on Coinbase Pro for 2.2%
