### ISSUE TITLE
Bot Won't Run Outside Test Mode

### ISSUE THREAD

**Issue by Kazaguya** [whittlem/pycryptobot#676]
I've added my api information for coinbase pro, but it still runs on test mode instead of actually going live. Not sure if I'm doing something wrong or missed a step in setup, please help :pray:

**Comment by JamesSimpson** [comment]
config.json file - make sure live = 1

**Comment by Kazaguya** [comment]
It wasn't that but you did help me realize that I had left it as config.json.sample and forgot to just make it a json file. Bonehead mistake but the bot is running now, thank you!
