### ISSUE TITLE
--simstartdate  and --simenddate are ignored

### ISSUE THREAD

**Issue by virdb** [whittlem/pycryptobot#679]
Step to reproduce:

1.  run `python3 pycryptobot.py --market BTC-EUR --disablebullonly 1 --disablebuymacd 1 --disablebuyobv 1 --disablefailsafefibonaccilow 1 --disablelog 1 --disableprofitbankreversal 1 --sim fast --verbose 1 --tradesfile BTCEUR-trades.csv`
2. run `python3 pycryptobot.py --market BTC-EUR --disablebullonly 1 --disablebuymacd 1 --disablebuyobv 1 --disablefailsafefibonaccilow 1 --disablelog 1 --disableprofitbankreversal 1 --sim fast --simstartdate '2021-01-01' --simenddate '2021-12-31' --verbose 1 --tradesfile BTCEUR-trades.csv`
3. verify the result is the same

**Comment by jakob1482** [comment]
If you use `--sim fast-sample`, the issue should resolve.
