### ISSUE TITLE
dockerised binance stopping for some reason

### ISSUE THREAD

**Issue by letsautom8** [whittlem/pycryptobot#68]
When using coinbase config, pycryptobot.log is updating accordingly - i mapped the file on dockerhost and tailed it and it refreshes every 15 min.
In the case of binance config, the log stops updating after the initial 2 lines,

The bot is updating the log correctly if run from host - but when run from container, it stops - only if it is binance.

Sample log using binance config:
04/22/2021 06:55:28 PM - DEBUG: * Candlestick Detected: Inverted Hammer ("Weak - Continuation - Bullish Pattern - Up")
04/22/2021 06:55:28 PM - DEBUG: 2021-04-22 06:00:00 | BTCDAI (BEAR) | 1h | Close: 54468.32 | v EMA12/26: 54418.95 < 54822.4 v | v MACD: -403.45 < -388.41 v | ^ OBV: -102.0562 (3.79%) ^ | ERI: buy | WAIT | Last Action: SELL
04/22/2021 07:00:34 PM - DEBUG: 2021-04-22 07:00:00 | BTCDAI (BEAR) | 1h | Close: 54438.57 | v EMA12/26: 54415.5 < 54790.56 v | *^ MACD: -375.07 > -386.37 ^* | OBV: -98.9343 (0.0%) | ERI: buy | WAIT | Last Action: SELL
04/22/2021 08:19:30 PM - DEBUG: * Candlestick Detected: Three Black Crows ("Strong - Reversal - Bearish Pattern - Down")

between 7:00 and 8:19 there is nothing. at 8:19 it updated the log because I restarted the container.

**Comment by lvlie** [comment]
See https://github.com/whittlem/pycryptobot/pull/69 and the linked issue. This change (which you can apply before that gets merged by setting the env in your docker-compose file or in the command line (`-e PYTHONUNBUFFERED=1`)) should at least provide you with a more functional log which might explain why it dies.

**Comment by letsautom8** [comment]
cool ill try to change the Dockerfile temporarily and see why it stops
