### ISSUE TITLE
SellLastBuySize option

### ISSUE THREAD

**Issue by YalicolbDenizen** [whittlem/pycryptobot#682]
I'd like to start an investment strategy that seeks to collect coins over time instead of money. In the US we are taxed on realized income, when the coin is sold for USD, but not unrealized, a held coin. 

I'm hoping for a SellLastBuySize. This would sell enough coin to generate what I spent and leave the remaining in whatever coin I purchased. This way I can avoid (totally legally as the tax is accrued on sold crypto) US Capital Gains Tax and still generate crypto assets.

It would need to sell all coins up to the last buy size if margin went negative if sellatloss is enabled.

SellPercent is close in that I can guess the average margin but the goal is to maximize coin generation and not increase realized income.

**Comment by hubov** [comment]
You can trade crypto with stable coins like Tether (USDT). It represents the value of a USD but is no FIAT (it's a cryptocurrency). I think it resolves your tax problem.

**Comment by whittlem** [comment]
Thanks for responding @hubov
