### ISSUE TITLE
How to trade with positive outcome

### ISSUE THREAD

**Issue by IGGI923** [whittlem/pycryptobot#688]
**Introduction to different trading strategies**
Hey there, 
I'm new to pycryptobot and have a technical background. Therefore I read the code and understand the concepts but have problems with the short explanations for the parameters in the repository. 
Some examples of how the different parameters effect the trading behavior would be good or some links. Best would be an explanation with graphs. 
I know this might be a stupid question for a long term trader but for me it's quite overwhelming. Or maybe some configs in comparison that end up in a different but predictable behavour in different situations (bull, bear, upward trend, high fluctuation, downward trend etc.)

Thank you in advance for your help. 

Best wishes, 
IGGI923

**Comment by loomsen** [comment]
Hi @IGGI923, 

Very valid question, and indeed, this can all be very overwhelming. Every concept, indicator, whatever is meant to help you to **predict** certain situations.
Nobody can predict the future, if we could, we wouldn't use a crypto bot. There's no wrong and right, no setting that will always lose, no setting that will always win. There's a simulation mode, that you can use to test settings on the past data. But obviously, it doesn't mean it will properly predict the future. 

If however you manage to find such a setting, please PM me with the details 😁 

Best
Norbert

**Comment by loomsen** [comment]
Questions like these are better asked in the [telegram community channel](https://t.me/joinchat/09hYKfelbRY2MDNk), I'll close this issue.
