### ISSUE TITLE
Insufficient funds

### ISSUE THREAD

**Issue by cparsell** [whittlem/pycryptobot#702]
**Describe the bug**
I'm trying to understand why it's not returning the balance correctly.
2022-04-30 22:00:56 WARNING  Insufficient Funds! (BTC=0.0, USD=0.0)

**To Reproduce**
Config file:
{
    "coinbasepro": {
        "api_url": "https://api.pro.coinbase.com",
        "config": {
            "base_currency": "BTC",
            "quote_currency": "USD",
            "live": 1,
            "sellatloss": 1,
            "sellatresistance": 0,
            "trailingstoploss": -1.5,
            "trailingstoplosstrigger": 5,
            "nosellmaxpcnt": 3,
            "nosellminpcnt": -3,
            "disablebullonly": 0,
            "disablebuynearhigh": 1,
            "disablebuymacd": 0,
            "disablebuyobv": 1,
            "disablebuyelderray": 0,
            "disablefailsafefibonaccilow": 1,
            "disableprofitbankreversal": 0,
            "disabletracker": 1,
            "disabletelegram": 1,
            "autorestart": 0,
            "graphs": 1,
            "verbose": 1,
            "stats": 0,
            "enableinsufficientfundslogging": 1,
            "enabletelegrambotcontrol": 1,
            "websocket": 0,
            "disablelog": 0,
            "buypercent": 99,
            "sellpercent": 99,
            "buyminsize": 0,
            "sellsmartswitch": 0,
            "trailingbuypcnt": 0.5,
            "telegramtradesonly": 0,
            "granularity": "3600",
            "enableml": 0,
            "recvwindow": 20000
        }
    },
    "logger" : {
        "filelog": 1,
        "logfile": "pycryptobot.log",
        "fileloglevel": "DEBUG",
        "consolelog": 1,
        "consoleloglevel": "DEBUG"
    }
}

Any insight into what I can do to set it straight? I've tried --recvWindow 20000 and I've tried to make sure system time is synced. Those were the only fixes I could find from googling around.  I also tried the beta branch to see if any update would help. 

Thanks.

**Comment by ciupas** [comment]
I've had similar issue, recreating API Key fixed it.

**Comment by cparsell** [comment]
Thanks, I'll give that a shot. Much appreciated.

**Comment by sharif1224** [comment]
I am having similar issues.  It appears I keep getting Insufficient Funds! exception every time I run the bot.  I am not sure it is really even using my API key as it checks for correctness and format, but I have intentionally put in a wrong key to see, and I receive the same Insufficient Funds! error.  Any ideas to see if the key is really connecting to my coinbase account?

**Comment by whittlem** [comment]
A new major version was released this year. Please upgrade to v7.0.34 or later and if you are still having a problem, raise an issue.
