### ISSUE TITLE
Panda Error

### ISSUE THREAD

**Issue by asmaarm1** [whittlem/pycryptobot#710]
I am a newby to python - can you please explain how to resolve the issue below please.

------------------------------------------------------------------------------------------

c:\Crypto\Experiment\pycryptobot-main -Bitcoin\pycryptobot-main>python pycryptobot.py --live 1
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexes\base.py", line 5845, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['created_at', 'market', 'action', 'type', 'size', 'filled', 'fees', 'price', 'status'] not in index"

c:\Crypto\Experiment\pycryptobot-main -Bitcoin\pycryptobot-main>

**Comment by whittlem** [comment]
A new major version was released this year. Please upgrade to v7.0.34 or later and if you are still having a problem, raise an issue.

Make sure all your packages are up to date:
python3 -m pip install -r requirements.txt -U
