### ISSUE TITLE
why requiring python 3.9?

### ISSUE THREAD

**Issue by matteodefelice** [whittlem/pycryptobot#72]
Any specific reason? I am struggling to install all the packages on a Raspberry, a lower version would be much easier. Is there any reason?

**Comment by lvlie** [comment]
The docker container also uses 3.8, which for me runs fine with Binance. Btw, running docker (or podman) is probably easier than installing python yourself.

**Comment by matteodefelice** [comment]
FYI. Ok, I managed to have it installed and running on a Raspberry 4 with Python 3.7. I just needed to install the required packages and `sudo apt-get install libatlas-base-dev` to fix an issue when importing `numpy`.

**Comment by whittlem** [comment]
Great, thanks for the update and glad you got it working.
