### ISSUE TITLE
V7.0.28 The bot crashes with an error in the simulation if you enable the setting "smartswitch": 1

### ISSUE THREAD

**Issue by ArlanovCsb** [whittlem/pycryptobot#756]
**Describe the bug**
The bot crashes with an error in the simulation if you enable the setting "smartswitch": 1
UnboundLocalError("local variable '_technical_analysis' referenced before assignment")

**To Reproduce**
1. Add the setting "smartswitch": 1 to the file config.json
2. Run a simulation
3. See error

**Expected behavior**
I see the error in the execute_job() method in the PyCryptoBot.py file

**Screenshots**
![image](https://user-images.githubusercontent.com/19302421/213346543-f84892d1-6cd1-4c77-a840-058ceedad8cc.png)
![image](https://user-images.githubusercontent.com/19302421/213346692-934be658-77fd-466e-a7c3-fb9783f6ec33.png)

**Comment by whittlem** [comment]
I was looking into this now. I'm not getting the error. I possibly have fixed this already. Can you try the latest version and confirm?
