### ISSUE TITLE
No bots running after scanner process is complete

### ISSUE THREAD

**Issue by alangrima** [whittlem/pycryptobot#764]
pycryptobot, [26 Jan 2023 at 12:37:42]:
Scan Complete.

Fido checking for hung bots..

stopping bots..

Starting binance (USDT) bots...

Ignoring LINKDOWNUSDT binance (USDT) Leverage Pairs (enableleverage is disabled)...

binance (USDT) ⏳ 
MITHUSDT  //--//  atr72_pcnt: 8.74%  //--//  buy_next: True
ADXUSDT  //--//  atr72_pcnt: 8.57%  //--//  buy_next: True
ANCUSDT  //--//  atr72_pcnt: 4.68%  //--//  buy_next: True
BEAMUSDT  //--//  atr72_pcnt: 3.64%  //--//  buy_next: True
NBTUSDT  //--//  atr72_pcnt: 3.29%  //--//  buy_next: True

Scanner Operation Complete.
- 5 started
- 5 running

Checking for bot status then returns:

Bot Count (0)

**Comment by whittlem** [comment]
I know there was a discussion about this in the Telegram chat. Mark was looking into this. Is it fixed or still outstanding?

**Comment by alangrima** [comment]
Still outstanding i'm afraid. These are the contents of data.json after the scanner has identified the trading pairs:

{
    "trades": {},
    "markets": {},
    "scannerexceptions": {}
}

**Comment by whittlem** [comment]
I don't use the scanner myself. So you create a data.json that looks like yours. Then how do you run it?

**Comment by beads99** [comment]
I'm also seeing the same behaviour, but using CoinbasePro. 

Not sure it's related, but I'm also seeing the below error in the log:

 Bot1  2023-01-30 14:22:22  BTC-GBP  3600  TypeError("'>' not supported between instances of 'NoneType' and 'int'") 

Interestingly BTC-GBP is not one of the pairs being recommended:

coinbasepro (GBP) ⏳ 
NU-GBP  //--//  atr72_pcnt: 4.74%  //--//  buy_next: True
UMA-GBP  //--//  atr72_pcnt: 2.37%  //--//  buy_next: True
NKN-GBP  //--//  atr72_pcnt: 1.88%  //--//  buy_next: True
MIR-GBP  //--//  atr72_pcnt: 1.62%  //--//  buy_next: True

Happy to break out in to another issue if not related.

**Comment by alangrima** [comment]
Following Mark H's suggestion on the telegram chat to change enabletelegrambotcontrol to telegrambotcontrol, issue seems to have been resolved
