### ISSUE TITLE
So what exchanges, markets, and config are you all using?

### ISSUE THREAD

**Issue by whittlem** [whittlem/pycryptobot#79]
According to Github there are 333 of you regularly updating your bots. I'm glad you are finding it useful :)

I was just curious how all of you are doing?

1. Which exchange(s) are you using? Coinbase Pro, Binance, or both?
2. How many bots are you running?
3. How much are you trading per bot?
4. Which markets are you trading?
5. What config is working well for you?

I'll start off...

1. I'm using Coinbase Pro only
2. I have 5 bots running (in case you didn't see Coinbase Pro now supports 10 portfolios!)
3. Up until yesterday I was trading £500 per bot. When ever the bots have a successful trade I transfer the profits to my bank account. I increased this to £1500 a bot yesterday.
4. I'm trading "ADA-GBP", "BCH-GBP", "BTC-GBP", "ETH-GBP", and "LTC-GBP". I was trading "XLM-EUR" but I found it too unreliable, too volatile for my liking. From my analysis ADA looks like a better option as it looks more stable and also more independent from Bitcoin and Ethereum.
5.  I'm actually trying out a new config from this morning. I have disabled "sellatloss" for a few weeks and it has been working really well for me. The change I made this morning was to "disablebullonly", "disablebuyobv", and "disablebuyelderray". The reason I disabled them is because they were there to prevent losses but I have "sellatloss" disabled so they are redundant with that on. I would rather be more liberal with my trades and trade more often. So I'm only using EMA crossovers and MACD with sell at loss disabled. I'll let you know how this works out.

As an example my BTC-GBP config.json looks like this (with my keys removed):

	{
	    "coinbasepro" : {
	        "api_url" : "https://api.pro.coinbase.com",
	        "api_key" : "",
	        "api_secret" : "",
	        "api_passphrase" : "",
	        "config" : {
	            "base_currency" : "BTC",
	            "quote_currency" : "GBP",
	            "live" : 1,
	            "sellatloss" : 0,
	            "disablebullonly" : 1,
	            "disablebuyobv" : 1,
	            "disablebuyelderray" : 1
	        }
	    },
	    "telegram" : {
	        "token" : "",
	        "client_id" : ""
	    }
	}

**Comment by jazha** [comment]
Which exchange(s) are you using? 
Coinbase Pro, Binance, or both? Coinbase Pro, because of the split portfolio feature that I dont have access to on Binance

How many bots are you running? 
5

How much are you trading per bot?
Private, but under 1000EUR

Which markets are you trading?
ADA, BCH, BTC, ETH, LTC to EUR

What config is working well for you?
I've run the bots for a few days, just changed my config to try to make them to a trade, they all seem to be stuck in "WAIT" mode for now.

I do this mostly for fun and my own understanding of the technical analysis of the trades, not to become a millionaire. Thanks for sharing your project!

**Comment by whittlem** [comment]
@jazha, thanks for the feedback. The markets have been a mess the last week or so. It's made trading conditions tough and by default the bot will avoid trading in bad conditions unless you disable those checks like I have done. It seems to be improving so hopefully we'll be back to trading a lot again soon.

**Comment by JShezz** [comment]
Which exchange(s) are you using? Coinbase Pro, Binance, or both?
CoinbasePro

How many bots are you running?
4

How much are you trading per bot?
~ £300

Which markets are you trading?
BCH, ETH, LTC, XTZ to GBP

What config is working well for you?
I am running with default config but with sellatloss: 0

Currently a significant loss on 2 of the bots as they brought just before the crash.... eeeeeek

BCH - GBP: Brought at £694 10% down as of today
LTC - GBP: Brought at £231 26% down as of today

Due to the bots crashing they are not currently running for BCH and LTC as I do not want them to sell at a loss.

Any advice would be much appreciated.

**Comment by iThom** [comment]
> Which exchange(s) are you using? Coinbase Pro, Binance, or both?
Coinbase Pro

>How many bots are you running?
6

> How much are you trading per bot?
~150-300€

> Which markets are you trading?
BTC, ETH, CGLD, NU, MATIC, ADA

> What config is working well for you?
For now I didn't got many "buy" but I was switching to your config, let's see :)

Thanks for sharing your configuration and your analysis.

**Comment by delphsmith** [comment]
Which exchange(s) are you using? Coinbase Pro, Binance, or both?
both

    How many bots are you running?
4

    How much are you trading per bot?
~200

    Which markets are you trading?
BTC-USDC & ETH-DAI on coinbase pro
BTC-USDC & ALGO-BUSD on binance

    What config is working well for you?
No sell at loss + granularity forced to 1h

But I actually modify a bit your code (buy/sell criteria - see below)
- If Bull market : buy when ema12 cross over ema26 and macd>signal OR when macd cross over signal and eam12 > ema26
- If Bear market : buy when sma50 is starting to be bullish again (added this in Trading.py :  self.df['bullsma50'] = self.df['sma50'] > self.df['sma50'].shift(1))
- No SELL if Bear market 

---
        bullsma50 = bool(df_last['bullsma50'].values[0])

        # criteria for a buy signal
        if macdgtsignal == True and goldencross == True and ema12gtema26co == True and is_crypto_recession == False and last_action != 'BUY':
            action = 'BUY'
        elif macdgtsignal == True and goldencross == False and bullsma50 == True and is_crypto_recession == False and last_action != 'BUY':
            action = 'BUY'
        elif ema12gtema26 == True and goldencross == True and macdgtsignalco == True and is_crypto_recession == False and last_action != 'BUY':
            action = 'BUY'
        elif ema12gtema26 == True and goldencross == False and bullsma50 == True and is_crypto_recession == False and last_action != 'BUY':
            action = 'BUY'
        # criteria for a sell signal
        elif ema12ltema26co == True and macdltsignal == True and elder_ray_sell == True and last_action not in ['','SELL']:
            action = 'SELL'


            #no sell if bearmarket except recession
            if action == 'SELL' and goldencross == False and is_crypto_recession == False:
                action = 'WAIT'
                last_action = 'BUY'
                log_text = '! Ignore Sell Signal (Bear market)'
                print (log_text, "\n")
                logging.warning(log_text)


----


 Thanks for sharing your project!

**Comment by whittlem** [comment]
@delphsmith, thanks for sharing and no problem.

I don't trade DAI. Is it good?

Interesting the changes you made to the buy/sell criteria. How is that working out for you? If it's a solid tried and tested strategy maybe I can include it as a configurable option so you don't need to have to waste time with code updates every time I push an update.

I see you are running quite old code now. All those options in the buy and sell criteria can now be enabled or disabled with options.

**Comment by delphsmith** [comment]
Well, i use dai as a stable coin, as i could use USDC. Sometimes I change it, I still don't know which one is the best.. I just don't want to trade with fiat because of taxes here (France)

The market is not great recently so i can't really tell, but I still got a pretty decent trade with Algo today
I tested it in a lot in simulation tho, and i found out I got better result than with yours, so..Fell free to try it also :)

It would be awsome if you could add it as option, or if we could configure (and share) our own strategy, yes !! At this moment I rewrite it everytime yes, the disabled options not enough, because I add a new criteria (sma50)

**Comment by whittlem** [comment]
Thanks for the feedback. I'll add some config options to allow your strategy to work easily without editing the code. I am keen to try it out too.

**Comment by whittlem** [comment]
What does "bullsma50" do? It looks like a boolean variable. Is that SMA50 > SMA200? That is what my "goldencross" variable is so may be duplicated.

I see you don't use OBV or Elder-Ray. This can now be disabled with config options (--disablebuyobv and --disablebuyelderray). You can remove those now without editing your code.

I would be careful with this "ema12gtema26 == True". That means that the buy will be triggered if the EMA12 and greater than the EMA26 (which may be the absolute peak before it comes down). The "ema12gtema26co" is the actual interval where it crosses over. With yours I expect if you restart the bot at the wrong time you will buy at a really high price.

"ema12gtema26 == True and goldencross == True and macdgtsignalco == True" is interesting. So you allow a buy to happen after the EMA crossovers have happened if the MACD was not positive when it crossed but crosses over later. That could be a nice option.

I like some of your additions but I think some may be risky. I expect in some conditions you may have an unexpected result. I'll do some testing and see.

**Comment by delphsmith** [comment]
- What does "bullsma50" do? 
It's when the SMA50 is starting to go bullish again
=> in Trading.py : self.df['bullsma50'] = self.df['sma50'] > self.df['sma50'].shift(1)

- I see you don't use OBV or Elder-Ray. 

Yes i add trouble with that, i think i missed lots of entry with it, eri always looked funny at the wrong (buy) moment...it was working great in sim but not IRL...
You are right, I can disable it with options, but as i rewrite the code every time, i already had my lines written and copy-pasted it ^^

- I would be careful with this "ema12gtema26 == True".
That's why I put it WITH macdgtsignalco. I actually add this because once or twice the bot sell after a Strong Reversal detected (which is nice) but price started to go up again, before the ema12 cross under ema26...so the price went higher and it could not reenter cause ema12 was already above ema26.
And if you are talking about ema12gtema26 == True and goldencross == False and bullsma50 == True, the buy will happened if sma50 is starting to go up again also, so getting better after a dump.
Maybe it's a risky move...if there is a "second" dump...

Like jazha said earlier, i do it "for fun and my own understanding of the technical analysis of the trades" and I might be wrong :) I like that you take time to reply to everyone of us and the effort you put in your code !

**Comment by whittlem** [comment]
Wow @JShezz, those buy prices are very high. Not to worry, it will bounce back. If you disable "sellatloss" either with the "--sellatloss 0" argument or '"sellatloss": 0' config.json config option the bot won't sell until it is positive.

@iThom, not heard of CGLD, NU, and MATIC. Why did you select those? Have they been working well for you?

@delphsmith, I've added a few of your criteria to the bot. I added the parts I thought have the biggest benefit. Try it out and see how it goes for you.

The markets seem to be bouncing back nicely. I've had two ADA trades in the last 24 hours and four of my bots have active buys now, three of which are slightly positive but the buys only happened recently.

**Comment by JShezz** [comment]
@whittlem I am running a very similar configuration to you, have I done something wrong for my bots to have traded at such a high point?

**Comment by iThom** [comment]
> @iThom, not heard of CGLD, NU, and MATIC. Why did you select those? Have they been working well for you?

@whittlem It's a test for now, I read an article somewhere speaking about some of these promising new tokens. Let's see. 2 of them triggered a buy this night.

**Comment by whittlem** [comment]
It would be great to know if they work well for you. I had a go and creating a machine learning model to look for correlated markets, well more importantly non-correlated markets. I was trying to find markets which are less affected by crashes or what Bitcoin and Ethereum are doing. ADA was one of the coins which seemed to be less affected.

**Comment by iThom** [comment]
> It would be great to know if they work well for you.

@whittlem I just got a sell of MATIC-EUR with +5% in approximately 12h. I'll keep the bot running to so see how it's going on.

**Comment by JShezz** [comment]
@whittlem I have only had one by on ADA buying at £0.9737.
Have i got something wrong with my configuration. I thought I had similar to you?
Will a bot trade more if you have more £ as stack in each trade?

**Comment by whittlem** [comment]
I have tried a new config on my bots and I've had so many buys today.

This is an example for BTC-GBP but all my bots have the same config (side from the market):

        "config" : {
            "base_currency" : "BTC",
            "quote_currency" : "GBP",
            "live" : 1,
            "sellatloss" : 0,
            "disablebullonly" : 1,
            "disablebuyobv" : 1,
            "disablebuyelderray" : 1,
            "disablelog" : 1,
            "disabletracker" : 1
        }

**Comment by github-ptaylor** [comment]
> I have tried a new config on my bots and I've had so many buys today.
> 
> This is an example for BTC-GBP but all my bots have the same config (side from the market):
> 
> ```
>     "config" : {
>         "base_currency" : "BTC",
>         "quote_currency" : "GBP",
>         "live" : 1,
>         "sellatloss" : 0,
>         "disablebullonly" : 1,
>         "disablebuyobv" : 1,
>         "disablebuyelderray" : 1,
>         "disablelog" : 1,
>         "disabletracker" : 1
>     }
> ```

i haven't had any buys yet.

The ability to configure the bot on how to behave in the market is great but, i had to google "buy elder ray" to understand what  it was used for, the same for "buy obv" :)

I had some ideas for new functionality:

1.  dynamically read in configuration settings "on the fly". 
2.  store different configurations
3. dynamically switch configurations based upon the state of the market

With this functionality, the main reasons to restart the bot would only be to (use new code, post crash).

**Comment by github-ptaylor** [comment]
> I have tried a new config on my bots and I've had so many buys today.
> 
> This is an example for BTC-GBP but all my bots have the same config (side from the market):
> 
> ```
>     "config" : {
>         "base_currency" : "BTC",
>         "quote_currency" : "GBP",
>         "live" : 1,
>         "sellatloss" : 0,
>         "disablebullonly" : 1,
>         "disablebuyobv" : 1,
>         "disablebuyelderray" : 1,
>         "disablelog" : 1,
>         "disabletracker" : 1
>     }
> ```

@whittlem can you explain why the bot wouldn't be buying on a bullish rise of ETH (from 2,738.00 through 2772.98) with the settings:

            "granularity" : "5m",
            "live" : 1,
            "verbose" : 1,
            "sellatloss" : 0,
            "disablebullonly" : 1,
            "disablebuyobv" : 1,
            "disablebuyelderray" : 1,
            "graphs" : 1,
            "sellupperpcnt": 3,
            "selllowerpcnt": -2,
            "trailingstoploss": -1,
            "logdir" : "./logs",
            "logfile" : "",
            "trade_amount_percentage" : 25

---

04/30/2021 04:56:21 PM - DEBUG: * Candlestick Detected: Hammer ("Weak - Reversal - Bullish Signal - Up")
04/30/2021 04:56:21 PM - DEBUG: -- Iteration: 11 --
04/30/2021 04:56:21 PM - DEBUG: price: 2741.47
04/30/2021 04:56:21 PM - DEBUG: ema12: 2748.54
04/30/2021 04:56:21 PM - DEBUG: ema26: 2753.17
04/30/2021 04:56:21 PM - DEBUG: ema12gtema26co: False
04/30/2021 04:56:21 PM - DEBUG: ema12gtema26: False
04/30/2021 04:56:21 PM - DEBUG: ema12ltema26co: False
04/30/2021 04:56:21 PM - DEBUG: ema12ltema26: True
04/30/2021 04:56:21 PM - DEBUG: sma50: 2762.9
04/30/2021 04:56:21 PM - DEBUG: sma200: 2761.48
04/30/2021 04:56:21 PM - DEBUG: macd: -4.64
04/30/2021 04:56:21 PM - DEBUG: signal: -3.97
04/30/2021 04:56:21 PM - DEBUG: macdgtsignal: False
04/30/2021 04:56:21 PM - DEBUG: macdltsignal: True
04/30/2021 04:56:21 PM - DEBUG: obv: -56739.213890000006
04/30/2021 04:56:21 PM - DEBUG: obv_pc: 0.32
04/30/2021 04:56:21 PM - DEBUG: action: WAIT


why did the bot WAIT? the bull run lasted almost an hour.

**Comment by whittlem** [comment]
@github-ptaylor, several reasons but the core reason is:

EMA12 < EMA26
MACD < Signal

**Comment by whittlem** [comment]
Hope you are all enjoying the trades this morning :) All my bots have sold with nice profit.

There was a really good ETH trade over night. Hope you all got that too.

**Comment by hunter747** [comment]
I was very happy with my eth trades 😊

 

From: Michael Whittle ***@***.***>
Reply to: whittlem/pycryptobot ***@***.***>
Date: Monday, 03 May 2021 at 10:04
To: whittlem/pycryptobot ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [whittlem/pycryptobot] So what exchanges, markets, and config are you all using? (#79)

 

Hope you are all enjoying the trades this morning :) All my bots have sold with nice profit.

There was a really good ETH trade over night. Hope you all got that too.

**Comment by github-ptaylor** [comment]
Hey fellas, good morning!

Should i turn disable the (obc, macd, elderray) algos to get the bot to trade on a rising ETH?

**Comment by hunter747** [comment]
I guess we would also need to turn sellatloss on at the same time

 

From: "Patrick C. Taylor" ***@***.***>
Reply to: whittlem/pycryptobot ***@***.***>
Date: Monday, 03 May 2021 at 10:41
To: whittlem/pycryptobot ***@***.***>
Cc: TEST ***@***.***>, Comment ***@***.***>
Subject: Re: [whittlem/pycryptobot] So what exchanges, markets, and config are you all using? (#79)

 

Hey fellas, good morning!

Should i turn disable the (obc, macd, elderray) algos to get the bot to trade on a rising ETH?

**Comment by akram0zaki** [comment]
No trades were fired by my ETH-EUR bot (version v2.0.0) since 26-Apr. Starting balance is EUR 800 remains the same :)

My config.json:
{
    "coinbasepro" : {
        "api_url" : "https://api.pro.coinbase.com",
        "api_key" : "KEY",
        "api_secret" : "SECRET",
        "api_passphrase" : "PASSPHRASE",
        "config" : {
            "base_currency" : "ETH",
            "quote_currency" : "EUR",
            "live" : 1,
            "sellatloss" : 0
        }
    },
    "telegram" : {
        "token" : "TOKEN",
        "client_id" : "ID"
    }
}

And I start it with:
python3 pycryptobot.py --market ETH-EUR --granularity 3600 --live 1 --verbose 0 --graphs 1

**Comment by iThom** [comment]
Hi,

@akram0zaki you miss some point in the configuration:

Add this in your "config" key will turn off some checks that can block some trades (and keep sellatloss: 0):

```
"disablebullonly" : 1,
"disablebuyobv" : 1,
"disablebuyelderray" : 1,
```
@whittlem No trade on ETH-EUR this night but many yesterday with nice profit :)

**Comment by whittlem** [comment]
Hi all, @iThom and @akram0zaki. Don't disable the "buy checks" above without disabling "sellatloss" as well. The checks are there to prevent losses. The only time it is safe to disable them is if you disable selling at a loss as well.

I added two more this evening which I'm going to try out. 

"disablebuynearhigh" will stop the bot from buying within 5% of the dataframe high. In the last few days the markets have been rocketing and the bot has been buying at high prices. It shouldn't really be a problem unless the market collapses which it often does after a run. I wanted to give the bot enough room to make some profit without buying right at the top. This seems to be working... the bot has been trying to buy LTC at 213.14 which I think it too high. It's recording that the high of the dataframe is 214.51 and because the price is within 5% I'm getting Telegram messages which say this: "LTC-GBP (900) 2021-05-04 00:04:30 | LTC-GBP | 900 | Ignoring Buy Signal (price 213.71 within 5% of high 214.51)"

"sellatresistance" is optional but it's what I do manually. I try and make an easy 1-2% on each trade regularly. I'm trading £1500 a bot so 1% often actually adds up fast. I have been manually adding in limit sells after each buy but I wanted to automate that. This option will sell if the margin is over 1% and the price hits either the resistance or fibonacci band. It may sell too early for your liking but I prefer a smaller "more guaranteed" amount more regularly.

**Comment by iThom** [comment]
Hi,

@whittlem  "disablebuynearhigh" and "sellatresistance" are great options to make safer trade. I can't wait when you will push them in your repo. I think ETH is near to be in such conditions that will need these options !

**Comment by iThom** [comment]
Nice I see that you pushed these new options (8bb72b382dd6086cdc25ce6fdaf6c3c999b21ac9) ! 
Thanks !

**Comment by djhemp** [comment]
I just restarted all my bots to do exactly what you're doing @whittlem.  I think that's the configuration I've been searching for.  I play around too much with configs and don't seem to maintain gains.  I'm working with more capital so I like risk management.  My big question is, with sellatloss @ 0 and all using the new parameters like you are - is the protect for crypto recession still on?  I'm a bit confused on that.  I'd hate to have the bots on for a long time and see gains wiped out due to a major crash/bear market so I love the idea of protecting from crypto recession.  This is my current config. The one things I'm using now that I don't see anyone else is, the buypercent.  I moved all the capital into one portfolio and would rather keep it trading utilizing more capital within there as different buy opportunities come up. It's worked pretty good and had a total of 5 coins in there at once with no issue.  I may change that back to the way you have multiple instances in folders, but it seems to work.  Any reason why it wouldn't in the same folder with multiple coins like that? 

        "config" : {
             "base_currency" : "ETH",
             "quote_currency" : "USD",
            "live" : 1,
            "disablebullonly" : 1,
            "disablebuyobv" : 1,
            "disablebuyelderray" : 1,
            "buypercent" : 50,
            "disablebuynearhig" : 1,
            "sellatresistance" : 1,
            "sellatloss" : 0

**Comment by whittlem** [comment]
HI guys,

Just a few updates...

I reduced "disablebuynearhigh" from 5% to 3%. I think 3% is enough room to trade. 5% may mean we lose opportunities in a strong bull market. I just didn't want the bot buying in new highs which would be very risky.

I also disabled the telegram message for "disablebuynearhigh". If you are running the same config as me you will have been swamped with LTC and ETH messages today which the bot saying it's ignoring the high because it's too high. Seems a little overkill so removed that.

I'm not sure if you saw but I removed the "crypto recession" check. I think it's heavy on resources to keep checking every iteration. All it is checking is making sure the SMA50 is still above the SMA200. Basically we don't want to be in any trades when the SMA50 drops below the SMA200 on the 6H and 1D graphs. The markers will tank badly at that point and probably lose 50% or more in a very short time frame. Just we just keep an eye on it on TradingView.com and just be out in time. If it's getting close I will let you guys know.

On a side note are any of you devs using Binance? There are some weird Binance related issues raised in the repo. I don't use Binance myself and I can't seem to re-create that they are seeing. If you know what they are talking about do you mind helping me resolve it?

**Comment by stefanoregis** [comment]
Hello @whittlem, I'm using binance on a regular basis, i never reported any problem related to ticket for example https://github.com/whittlem/pycryptobot/issues/102#issue-875016168 but if you want me to make some tests, just tell me. Sometimes Binance api has timeouts issues but as far i can see in the last days is going better

**Comment by schroedermarius** [comment]
I just want to check if my trade happens. But i cant get it working doing a trade. Its not reporting any error, so I would assume my balance on my account (EUR) ist good, or do I have to do something with my Balance at Binance?

I am using the following configuration (removed my key and secret):

`{
    "binance" : {
        "api_url" : "https://api.binance.com",
        "api_key" : "",
        "api_secret" : "",
        "config" : {
            "base_currency" : "BTC",
            "quote_currency" : "EUR",
            "granularity" : "5m",
            "verbose": 0,
            "live" : 1,
            "sellatloss" : 0,
            "sellupperpcnt": 5,
            "selllowerpcnt": -2,
            "disablebullonly" : 1,
            "disablebuyobv" : 1,
            "disablebuyelderray" : 1,
            "disablelog" : 0,
            "disabletracker" : 1,
            "buypercent" : 25,
            "disablebuynearhigh": 1,
            "sellatresistance" : 1
        }        
    }
}
`

**Comment by stefanoregis** [comment]
hello @schroedermarius did you try with another pair? Instead of BTC? me i'm using it on binance and I had some buy events with ADA for example

**Comment by schroedermarius** [comment]
> hello @schroedermarius did you try with another pair? Instead of BTC? I'm using it on binance and I had some buy events with ADA for example

Thanks for your reply. Will try with ADA. I already tried with BNB, ETH and BTC.

**Comment by stefanoregis** [comment]
> > hello @schroedermarius did you try with another pair? Instead of BTC? I'm using it on binance and I had some buy events with ADA for example
> 
> Thanks for your reply. Will try with ADA. I already tried with BNB, ETH and BTC, all paired to EUR.

I had one yesterday with BNB/USDT as well, this is an example of my bot command with the options i use:

python3 pycryptobot.py --exchange binance --verbose 1 --market ADAUSDT --sellatloss 0 --disablebullonly --disablebuyobv --disablebuyelderray --disabletracker --live 1 --sellatresistance 0 --disablebuynearhigh

**Comment by schroedermarius** [comment]
@stefanoregis 
Alright, thanks!
Does it require me to have a balance in USDT in my account? Maybe I have to change my "quote_currency" to USDT and convert my balance on binance to USDT?

**Comment by stefanoregis** [comment]
if you want to use the USDT, yes you have to have some USDT in your account, but you can try with EUR as well, i'm sure it will trigger some BUY events

**Comment by vsnomad** [comment]
Hello @whittlem, thanks for keeping this in the public domain.
> Hi all, @iThom and @akram0zaki. Don't disable the "buy checks" above without disabling "sellatloss" as well. The checks are there to prevent losses. The only time it is safe to disable them is if you disable selling at a loss as well.

Could you explain why this is true?

**Comment by robinski93** [comment]
Hi Everyone, 

First of all thanks a lot @whittlem for sharing the cryptoBot. 

Has anyone tried ETH-BTC pair in Binance? any configurations which has been working well for it? 
I understand the coin-coin pairs are a bit more dynamic than the coin-currency pair.. so expecting it to be a bit more challenging. After the bull run of Eth on BTC , expecting this to be a silent week.... but u never know :D

**Comment by whittlem** [comment]
@vsnomad, if you want to sell if the margin drops below -2% you can use:

--selllowerpcnt -2
OR
--trailingstoploss -2

If you are not going to disable sell at loss then don't disable the bull market check, OBV, and Elder-Ray. They are there to make sure the trades have a high chance of success.

@robinski93, it should just work. Same configuration as mine just use "ETH" as the base currency and "BTC" as the quote currency.

I've created a public Telegram channel:
https://t.me/pycryptobotchat

It may be better if we move this chat there.

**Comment by whittlem** [comment]
I had to change the public Channel to a Group as the communication was one way.

The invite for the group is here:
https://t.me/joinchat/09hYKfelbRY2MDNk

You should still be able to access the group link:
https://t.me/pycryptobotchat

Moving this chat to Telegram.
