### ISSUE TITLE
IndexError('index 0 is out of bounds for axis 0 with size 0') after restart 

### ISSUE THREAD

**Issue by demkoma20** [whittlem/pycryptobot#794]
I am using pycryptobot without Docker/Kubernetes, without Telegram. I copied it into folder, install modules and run via Ubuntu terminal. 

I run few markets on Binance (ADAAUD, BTCBUSD, ETHEUR) into custom *.log files. Then market fell and I decided to re-run every market by doing this:

1. Set up LIMIT order (all funds get locked so bot have nothing)
2. Buy base assets (BUSD, EUR, AUD) 
3. Stop services in terminal (ctrl+c)
4. Remove log files
5. Run again all markets - There I got error 

IndexError('index 0 is out of bounds for axis 0 with size 0')

But when I canceled the limit orders and tried to re-run, bot run successfully.

I tried to find files with order history but I didn't find them. Does anyone have a solution?

**Comment by whittlem** [comment]
There is another Issue related to this. This should be fixed in 8.0.7. Give it a go and let me know.

**Comment by demkoma20** [comment]
I tried but I am not able to start. "Invalid API key, IP, or permissions for action". I am sure that keys are right. API setting on screenshot
![image](https://user-images.githubusercontent.com/100209190/234632646-f9ce9845-5fca-44b1-b15c-6e8d564a168f.png)

**Comment by whittlem** [comment]
Are you sure you are using v8.0.7? I've had confirmation from others it's fixed. I'm not having the issue either. Can you provide your config.json, how you are running your bot, and anything else that may be useful to troubleshoot.
