### ISSUE TITLE
Preventloss does not work with declining market

### ISSUE THREAD

**Issue by krzysztofMajchrzak-GIT** [whittlem/pycryptobot#801]
Hi, i think i have spotted the problem. You see when there is preventloss and preventlosstrigger set it seems not to work if margin does not cross the trigger. What i mean is that: This is my config:

```

{
    "binance": {
        "config": {
            "exchange": "binance",
            "api_url": "https://api.binance.com",
            "market": "ETHUSDT",
            "buypercent": 100,
            "sellpercent": 100,
            "sellatloss": 1,
            "preventloss": 1,
            "preventlosstrigger": 1.5,
            "preventlossmargin": 0.6,
            "nobuynearhighpcnt": 1
        },
        "api_key_file": "binance.key"
    }
}
```

So it should trigger a sell when margin reaches 0.6 and the watching should start on 1.5. BUT! if bot buys and the margin is negative on the next step the watching procedure never starts so it does not sell at all. Let me give you an example:

![obraz](https://github.com/whittlem/pycryptobot/assets/58195641/1672b17b-ff10-4354-8893-4e97562f3e7d)

After buy the very next margin is already -4%. This means that the trigger never triggers cause there was no positive 1.5 margin. This way it will hold the position until it reaches 1.5 and declines above 0.6 or there is a selling signal in between.

**Comment by whittlem** [comment]
Closing this as the change was been implemented by a contributor PR.
