### ISSUE TITLE
trading account.py uses the same critical error message for both Coinbase and coinbasepro. 

### ISSUE THREAD

**Issue by wattiii** [whittlem/pycryptobot#804]
line 440 deals with coinbase, but it's critical error exception raised prompts users to an error with coinbase pro. It would be more clear if it said cionbase for the coinbase critical exception, and then said coinbase pro for the coinbase Pro error message.

**Comment by whittlem** [comment]
Thanks, changing it to:

`raise Exception(
    f"TradingAccount: '{self.app.exchange}' API Error while getting balance."
)`
