### ISSUE TITLE
Binance marketBuy APIError(code=-1100): Illegal characters found in parameter 'quantity'

### ISSUE THREAD

**Issue by mrtanishqbhatia** [whittlem/pycryptobot#84]
My configuration:
`"config": {
      "base_currency": "BTC",
      "quote_currency": "USDT",
      "smartswitch": 1,
      "live": 1,
      "verbose": 0,
      "sellatloss": 0
    }`

I have about $500 of BTC and when I ran this after a day, I got this.

```
2021-04-29 | BTCUSDT (BULL) | 15m | Close: 54989.55 | ^ EMA12/26: 54768.97 > 54695.77 ^ | *^ MACD: 73.2 > 72.99 ^* | v OBV: -45928.9466 (-2.62%) v | ERI: buy | BUY | Last Action: SELL

 2021-04-29 | BTCUSDT 15m | Close: 54989.55 | BUY 

BTC balance before order: 0.0084
USDT balance before order: 0.2153
Order quantity after rounding and fees: 3e-06
28-04-2021 20:31:21 Binance marketBuy APIError(code=-1100): Illegal characters found in parameter 'quantity'; legal range is '^([0-9]{1,20})(\.[0-9]{1,20})?$'.
BTC balance after order: 0.0084
USDT balance after order: 0.2153

Process finished with exit code -1
```

**Comment by mrtanishqbhatia** [comment]
Can you explain this error?
I want to know your configuration having sellatloss 0.

**Comment by fepetoo** [comment]
that is the problem: 
"Order quantity after rounding and fees: 3e-06"

there is some rounding issue

**Comment by letsautom8** [comment]
looks like quantity needs to be sanitised before sending to binance.

**Comment by whittlem** [comment]
It looks like with the rounding it is converting it to scientific notation. It will be a little tricky to re-create this issue to fix it but I'll see what I can do.

**Comment by letsautom8** [comment]
What is puzzling with this log is that you already have BTC. And the bot is trying to buy...
2021-04-29 | BTCUSDT (BULL) | 15m | Close: 54989.55 | ^ EMA12/26: 54768.97 > 54695.77 ^ | *^ MACD: 73.2 > 72.99 ^* | v OBV: -45928.9466 (-2.62%) v | ERI: buy | BUY | Last Action: SELL

 2021-04-29 | BTCUSDT 15m | Close: 54989.55 | BUY 

BTC balance before order: 0.0084
USDT balance before order: 0.2153
Order quantity after rounding and fees: 3e-06
28-04-2021 20:31:21 Binance marketBuy APIError(code=-1100): Illegal characters found in parameter 'quantity'; legal range is '^([0-9]{1,20})(\.[0-9]{1,20})?$'.
BTC balance after order: 0.0084
USDT balance after order: 0.2153

Process finished with exit code -1

**Comment by letsautom8** [comment]
@whittlem looks like this is because of the init scenario if trade currency < quote currency then  last action is sell. But in fact the 0.0084 btc is > 0.2153.
#89 Should prevent the error above from happenning.

**Comment by whittlem** [comment]
Thanks @letsautom8. I think you have pushed a PR for this already. Can you confirm this is resolved?
