### ISSUE TITLE
Any market limits?

### ISSUE THREAD

**Issue by Fendo99** [whittlem/pycryptobot#88]
Hey,
is there any limitation to the markets i can trade?
Or can i trade in every market that Binance accepts?

**Comment by whittlem** [comment]
Sort of. The bot executes trades by buying will all funds available and selling everything. The way you create multiple bots on Coinbase Pro is to create multiple portfolios and then assign a bot to each portfolio. They support up to 10 now. You can also be creative by adding two bots to a portfolio provided they don't conflict for example BTC-GBP and ETH-EUR. Binance is a lot more tricky as they have Sub-Accounts but they are not free. People who run multiple bots there just trade non-conflicting markets but you are quite limited on how many you can do. I suggest reading my Medium articles. I have explained this in detail and how to set it all up.
