### ISSUE TITLE
Syncing last_action after failure

### ISSUE THREAD

**Issue by letsautom8** [whittlem/pycryptobot#89]
Hi @whittlem , it seems that the state of the bot differs from orders action after some time. This might be due to error in buying or selling.
I added the following on line 67 of `pycryptobot.py` to set last_action properly. Do you think this is effective?
```
        if str(df.action.values[0]) == 'buy':
            last_action = 'BUY'
            last_buy = float(df[df.action == 'buy']['price'])
        else:
            last_action = 'SELL'
            last_buy = 0.0
```

**Comment by whittlem** [comment]
It looks fine to me. Have you tested it? Did it resolve your issue?

**Comment by whittlem** [comment]
Ok, good news. Thanks for letting me know.
