### ISSUE TITLE
Pycryptobot.py: Odd if statement check on line 1685 (sellUpperPcnt())

### ISSUE THREAD

**Issue by github-ptaylor** [whittlem/pycryptobot#91]
Hey @whittlem @letsautom8 

I came across an if statement that does various checks against (sellUpperPcnt, sellLowerPcnt, allowSellAtLoss). But, if the expression is true it just prints closing section for the  "box" of startup information:

Pycrytobot.py (line: 1685):

`        if self.sellUpperPcnt() != None or self.sellLowerPcnt() != None or self.allowSellAtLoss() == False:
            print('================================================================================')`

**Comment by whittlem** [comment]
All this does is prints a dividing line in the output. It is cosmetic and doesn't have anything to do with the bot mechanics.
