### ISSUE TITLE
Option to set 'last action' manually

### ISSUE THREAD

**Issue by vsamoili** [whittlem/pycryptobot#93]
I recently started experimenting with the bot; really nice work!
Is it possible to specify last action manually instead of automatically?
For me at least, I've had to trigger the run a few times due to connection errors and other reasons, for the same portfolio,
so when it restarts, it'd be nice to be able to specify the state at which my portfolio is currently in.
Thank you in advance!

**Comment by whittlem** [comment]
Sure, I don't think this option would be used very often but I see it could be useful. I'll add it when I get some time.

**Comment by whittlem** [comment]
Added --lastaction BUY or --lastaction SELL

This will allow you to manually set the starting state, otherwise it will figure it out like it is doing now.
