### ISSUE TITLE
BTC - BINANCE marketBuy APIError(code=-1013): Filter failure: MIN_NOTIONAL + Incorrect Iteration TIMESTAMP

### ISSUE THREAD

**Issue by github-ptaylor** [whittlem/pycryptobot#94]
Good Morning!

Note: It is 4:56am (CST) <-- important for the timestamp on the iteration

`================================================================================
|         Iteration : 25                                                       |
|         Timestamp : 2021-05-01 05:20:00                                      |
--------------------------------------------------------------------------------
|             Close : 58352.01                                                 |
|             EMA12 : 58065.97                                                 |
|             EMA26 : 58064.77                                                 |
|    Crossing Above : True                                                     |
|   Currently Above : True                                                     |
|    Crossing Below : False                                                    |
|   Currently Below : False                                                    |
|         Condition : EMA12 is currently crossing above EMA26                  |
|             SMA20 : 58055.25                                                 |
|            SMA200 : 57083.69                                                 |
--------------------------------------------------------------------------------
|              MACD : 1.19                                                     |
|            Signal : -25.21                                                   |
|   Currently Above : True                                                     |
|   Currently Below : False                                                    |
|         Condition : MACD is currently above Signal and has crossed over      |
--------------------------------------------------------------------------------
|            Action : BUY                                                      |
================================================================================
--------------------------------------------------------------------------------
|                      *** Executing LIVE Buy Order ***                        |
--------------------------------------------------------------------------------
BTC balance before order: 0.0
USDT balance before order: 36.6357
Order quantity after rounding and fees: 0.000156
30-04-2021 23:24:02 Binance marketBuy APIError(code=-1013): Filter failure: MIN_NOTIONAL
BTC balance after order: 0.0
USDT balance after order: 36.6357`

My (config.json) configuration:

`        "config" : {
            "base_currency" : "",
            "quote_currency" : "",
            "granularity" : "5m",
            "live" : 1,
            "verbose" : 1,
            "sellatloss" : 1,
            "disablebullonly" : 1,
            "disablebuyobv" : 1,
            "disablebuyelderray" : 1,
            "disablebuymacd" : 1,
            "graphs" : 0,
            "sellupperpcnt": 2,
            "selllowerpcnt": -1,
            "trailingstoploss": -1,
            "logdir" : "./logs/",
            "logfile" : "",
            "buypercent" : 25
        }`

**Comment by github-ptaylor** [comment]
The same error occurred again with BTC on another BUY attempt:

================================================================================
|         Iteration : 37                                                       |
|         Timestamp : 2021-05-01 06:25:00                                      |
--------------------------------------------------------------------------------
|             Close : 58131.66                                                 |
|             EMA12 : 58092.3                                                  |
|             EMA26 : 58091.85                                                 |
|    Crossing Above : True                                                     |
|   Currently Above : True                                                     |
|    Crossing Below : False                                                    |
|   Currently Below : False                                                    |
|         Condition : EMA12 is currently crossing above EMA26                  |
|             SMA20 : 58097.99                                                 |
|            SMA200 : 57297.5                                                  |
--------------------------------------------------------------------------------
|              MACD : 0.44                                                     |
|            Signal : 3.73                                                     |
|   Currently Above : False                                                    |
|   Currently Below : True                                                     |
|         Condition : MACD is currently below Signal and has crossed over      |
--------------------------------------------------------------------------------
|            Action : BUY                                                      |
================================================================================
--------------------------------------------------------------------------------
|                      *** Executing LIVE Buy Order ***                        |
--------------------------------------------------------------------------------
BTC balance before order: 0.0
USDT balance before order: 36.6357
Order quantity after rounding and fees: 0.000157
01-05-2021 00:25:20 Binance marketBuy APIError(code=-1013): Filter failure: MIN_NOTIONAL
BTC balance after order: 0.0
USDT balance after order: 36.6357

**Comment by github-ptaylor** [comment]
Hey @whittlem @letsautom8 ,

this error is a result of the trade attempt not meeting the (10 USDT) required by Binance.. my 25% (buypercent) value gave the trade about (9 USDT) in funds.

That's just that but, it seems the bot is storing the Buy trade when it should NOT because the response is given of a FAILED BUY. 

As a result of logging the trade as a BUY, the bot attempts to SELL (as shown in the other issue) on a trade that doesn't exist.

**Comment by letsautom8** [comment]
@github-ptaylor I am quite confused. I believe the bot is independent on every cycle (which occurs every 5 min)The previous action is stored- yes but it should correct its state on the next cycle if the buy fails for some reason. Also i improved it a bit and #92 Has that improvement.

**Comment by github-ptaylor** [comment]
hey @letsautom8 i will try to replicate the issue after your code is pushed out by using less than 10 USDT.

in my head it seems the logic is doing this currently:

1. BUY signal confirmed
2. store that state and related trade data
3. API result states BUY didn't happen due to failed MIN_NOMINAL amount.
4. bot continues to cycle until SELL params are met via config.json settings.
5. SELL signal reached.
6. logic tries to initiate SELL via the API but fails because they BUY data is false (no crypto was actually bought)

**Comment by github-ptaylor** [comment]
issue closed because it is related to [95](https://github.com/whittlem/pycryptobot/issues/95)
