### ISSUE TITLE
BTC - Binance marketSell APIError(code=-1013): Invalid quantity

### ISSUE THREAD

**Issue by github-ptaylor** [whittlem/pycryptobot#95]
This is the subsequent error trying to SELL from a BUY that didn't actually happen on the exchange.

================================================================================
|         Iteration : 35                                                       |
|         Timestamp : 2021-05-01 06:10:00                                      |
--------------------------------------------------------------------------------
|             Close : 58000.0                                                  |
|             EMA12 : 58082.18                                                 |
|             EMA26 : 58088.17                                                 |
|    Crossing Above : False                                                    |
|   Currently Above : False                                                    |
|    Crossing Below : True                                                     |
|   Currently Below : True                                                     |
|         Condition : EMA12 is currently crossing below EMA26                  |
|             SMA20 : 58066.52                                                 |
|            SMA200 : 57255.67                                                 |
--------------------------------------------------------------------------------
|              MACD : -6.0                                                     |
|            Signal : 9.87                                                     |
|   Currently Above : False                                                    |
|   Currently Below : True                                                     |
|         Condition : MACD is currently below Signal and has crossed over      |
--------------------------------------------------------------------------------
|            Action : SELL                                                     |
================================================================================
|            Margin : -0.61%%                                                  |
================================================================================
--------------------------------------------------------------------------------
|                      *** Executing LIVE Sell Order ***                        |
--------------------------------------------------------------------------------
BTC balance before order: 0.0
USDT balance before order: 36.6357
Order quantity after rounding and fees: 0.0
01-05-2021 00:15:04 Binance marketSell APIError(code=-1013): Invalid quantity.
BTC balance after order: 0.0
USDT balance after order: 36.6357

Same (config.json):

        "config" : {
            "base_currency" : "",
            "quote_currency" : "",
            "granularity" : "5m",
            "live" : 1,
            "verbose" : 1,
            "sellatloss" : 1,
            "disablebullonly" : 1,
            "disablebuyobv" : 1,
            "disablebuyelderray" : 1,
            "disablebuymacd" : 1,
            "graphs" : 0,
            "sellupperpcnt": 2,
            "selllowerpcnt": -1,
            "trailingstoploss": -1,
            "logdir" : "./logs/",
            "logfile" : "",
            "buypercent" : 25
        }

**Comment by github-ptaylor** [comment]
Update:

This scenario won't happen if the bot doesn't log a "false" BUY as a result of the API call to Binance stating the funds were insufficent (MIN_NOTIONAL).

**Comment by github-ptaylor** [comment]
hey @letsautom8  i will try to replicate the issue after your code is pushed out by using less than 10 USDT.

in my head it seems the logic is doing this currently:

BUY signal confirmed
store that state and related trade data
API result states BUY didn't happen due to failed MIN_NOMINAL amount.
bot continues to cycle until SELL params are met via config.json settings.
SELL signal reached.
logic tries to initiate SELL via the API but fails because they BUY data is false (no crypto was actually bought)
@github-ptaylor

**Comment by whittlem** [comment]
Is this an open issue? Can it be closed?

**Comment by github-ptaylor** [comment]
It can be closed.
